import { createSheet } from '@/shared/ui/create-sheet';
import { lightColors } from '@/theme/tokens/colors';


export const styles = createSheet({
  container: { flex: 1, backgroundColor: lightColors.semantic.obsidian },
  scrollView: { flex: 1 },
  header: { padding: 20, paddingBottom: 16 },
  title: { fontSize: 28, fontWeight: 'bold', color: lightColors.text.inverse, marginBottom: 8 },
  subtitle: { fontSize: 16, color: lightColors.text.muted },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: 16, fontSize: 16, color: lightColors.text.muted },
  errorContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  errorText: { fontSize: 16, color: lightColors.semantic.danger, textAlign: 'center', marginBottom: 16 },
  retryButton: { backgroundColor: lightColors.accent.blue, paddingVertical: 12, paddingHorizontal: 24, borderRadius: 8 },
  retryButtonText: { color: lightColors.text.inverse, fontWeight: '600' },
  section: { paddingHorizontal: 20, marginBottom: 24 },
  sectionTitle: { fontSize: 18, fontWeight: '600', color: lightColors.text.inverse, marginBottom: 12 },
  summaryCard: {
    backgroundColor: lightColors.semantic.obsidian,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: lightColors.semantic.obsidian,
  },
  summaryText: { fontSize: 15, lineHeight: 24, color: lightColors.border.light, marginBottom: 16 },
  keyConcepts: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  conceptTag: { backgroundColor: lightColors.semantic.obsidian, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  conceptText: { fontSize: 13, color: lightColors.text.muted },
  taskCard: {
    backgroundColor: lightColors.semantic.obsidian,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: lightColors.semantic.obsidian,
  },
  taskHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  taskNumber: {
    width: 28, height: 28, borderRadius: 14, backgroundColor: lightColors.accent.blue,
    color: lightColors.text.inverse, fontSize: 14, fontWeight: '600',
    textAlign: 'center', lineHeight: 28, marginRight: 12,
  },
  priorityBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  priorityText: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase' },
  taskContent: { fontSize: 15, color: lightColors.text.inverse, lineHeight: 22, marginBottom: 8 },
  taskEstimate: { fontSize: 13, color: lightColors.text.muted },
  quizCard: {
    backgroundColor: lightColors.semantic.obsidian,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: lightColors.semantic.obsidian,
  },
  quizHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  quizNumber: { fontSize: 14, fontWeight: '600', color: lightColors.accent.blue, marginRight: 12 },
  difficultyBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  difficultyText: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase' },
  quizQuestion: { fontSize: 15, color: lightColors.text.inverse, lineHeight: 22, marginBottom: 12 },
  optionsList: { marginBottom: 12 },
  optionItem: { flexDirection: 'row', marginBottom: 8 },
  optionLabel: { fontSize: 14, color: lightColors.text.muted, width: 24 },
  optionText: { fontSize: 14, color: lightColors.border.light, flex: 1 },
  answerToggle: {
    alignSelf: 'flex-start', paddingVertical: 8, paddingHorizontal: 12,
    backgroundColor: lightColors.semantic.obsidian, borderRadius: 8,
  },
  answerToggleText: { fontSize: 14, color: lightColors.accent.blue, fontWeight: '500' },
  answerContainer: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: lightColors.semantic.obsidian },
  answerLabel: { fontSize: 13, color: lightColors.text.muted, marginBottom: 4 },
  answerText: { fontSize: 15, color: lightColors.accent.green, fontWeight: '500', marginBottom: 12 },
  explanationLabel: { fontSize: 13, color: lightColors.text.muted, marginBottom: 4 },
  explanationText: { fontSize: 14, color: lightColors.text.muted, lineHeight: 20 },
  sessionCard: {
    backgroundColor: lightColors.semantic.obsidian,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: lightColors.semantic.obsidian,
  },
  sessionRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 16 },
  sessionInfo: { flex: 1, marginLeft: 12 },
  sessionLabel: { fontSize: 13, color: lightColors.text.muted, marginBottom: 4 },
  sessionValue: { fontSize: 16, fontWeight: '500', color: lightColors.text.inverse },
  focusAreas: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  focusAreaTag: { backgroundColor: lightColors.semantic.warning + '20', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  focusAreaText: { fontSize: 12, color: lightColors.semantic.warning },
  ratingContainer: { paddingHorizontal: 20, marginBottom: 24, alignItems: 'center' },
  ratingTitle: { fontSize: 16, color: lightColors.text.muted, marginBottom: 12 },
  ratingStars: { flexDirection: 'row', gap: 8 },
  starButton: { padding: 4 },
  star: { fontSize: 32, color: lightColors.semantic.obsidian },
  starFilled: { color: lightColors.semantic.warning },
  ratingThanks: { fontSize: 16, color: lightColors.accent.green },
  bottomSpacer: { height: 100 },
  fabContainer: { position: 'absolute', bottom: 20, left: 20, right: 20 },
  fab: {
    backgroundColor: lightColors.accent.blue, borderRadius: 16, paddingVertical: 18,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    shadowColor: lightColors.accent.blue, shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 8, elevation: 8,
  },
  fabDisabled: { opacity: 0.7 },
  fabText: { fontSize: 17, fontWeight: '600', color: lightColors.text.inverse, marginLeft: 8 },
  icon: { fontSize: 20 },
});
