import { createSheet } from '@/shared/ui/create-sheet';
import { launchColors } from '@theme/tokens/launch-colors';

export const styles = createSheet({
  container: { flex: 1, backgroundColor: launchColors.hex_0f0f0f },
  scrollView: { flex: 1 },
  header: { padding: 20, paddingBottom: 16 },
  title: { fontSize: 28, fontWeight: 'bold', color: launchColors.hex_ffffff, marginBottom: 8 },
  subtitle: { fontSize: 16, color: launchColors.hex_9ca3af },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  loadingText: { marginTop: 16, fontSize: 16, color: launchColors.hex_9ca3af },
  errorContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  errorText: { fontSize: 16, color: launchColors.hex_ef4444, textAlign: 'center', marginBottom: 16 },
  retryButton: { backgroundColor: launchColors.hex_3b82f6, paddingVertical: 12, paddingHorizontal: 24, borderRadius: 8 },
  retryButtonText: { color: launchColors.hex_ffffff, fontWeight: '600' },
  section: { paddingHorizontal: 20, marginBottom: 24 },
  sectionTitle: { fontSize: 18, fontWeight: '600', color: launchColors.hex_ffffff, marginBottom: 12 },
  summaryCard: {
    backgroundColor: launchColors.hex_1a1a1a,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: launchColors.hex_2a2a2a,
  },
  summaryText: { fontSize: 15, lineHeight: 24, color: launchColors.hex_d1d5db, marginBottom: 16 },
  keyConcepts: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  conceptTag: { backgroundColor: launchColors.hex_2a2a2a, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 20 },
  conceptText: { fontSize: 13, color: launchColors.hex_9ca3af },
  taskCard: {
    backgroundColor: launchColors.hex_1a1a1a,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: launchColors.hex_2a2a2a,
  },
  taskHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  taskNumber: {
    width: 28, height: 28, borderRadius: 14, backgroundColor: launchColors.hex_3b82f6,
    color: launchColors.hex_ffffff, fontSize: 14, fontWeight: '600',
    textAlign: 'center', lineHeight: 28, marginRight: 12,
  },
  priorityBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  priorityText: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase' },
  taskContent: { fontSize: 15, color: launchColors.hex_ffffff, lineHeight: 22, marginBottom: 8 },
  taskEstimate: { fontSize: 13, color: launchColors.hex_6b7280 },
  quizCard: {
    backgroundColor: launchColors.hex_1a1a1a,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: launchColors.hex_2a2a2a,
  },
  quizHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  quizNumber: { fontSize: 14, fontWeight: '600', color: launchColors.hex_3b82f6, marginRight: 12 },
  difficultyBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  difficultyText: { fontSize: 12, fontWeight: '600', textTransform: 'uppercase' },
  quizQuestion: { fontSize: 15, color: launchColors.hex_ffffff, lineHeight: 22, marginBottom: 12 },
  optionsList: { marginBottom: 12 },
  optionItem: { flexDirection: 'row', marginBottom: 8 },
  optionLabel: { fontSize: 14, color: launchColors.hex_9ca3af, width: 24 },
  optionText: { fontSize: 14, color: launchColors.hex_d1d5db, flex: 1 },
  answerToggle: {
    alignSelf: 'flex-start', paddingVertical: 8, paddingHorizontal: 12,
    backgroundColor: launchColors.hex_2a2a2a, borderRadius: 8,
  },
  answerToggleText: { fontSize: 14, color: launchColors.hex_3b82f6, fontWeight: '500' },
  answerContainer: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: launchColors.hex_2a2a2a },
  answerLabel: { fontSize: 13, color: launchColors.hex_6b7280, marginBottom: 4 },
  answerText: { fontSize: 15, color: launchColors.hex_10b981, fontWeight: '500', marginBottom: 12 },
  explanationLabel: { fontSize: 13, color: launchColors.hex_6b7280, marginBottom: 4 },
  explanationText: { fontSize: 14, color: launchColors.hex_9ca3af, lineHeight: 20 },
  sessionCard: {
    backgroundColor: launchColors.hex_1a1a1a,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: launchColors.hex_2a2a2a,
  },
  sessionRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 16 },
  sessionInfo: { flex: 1, marginLeft: 12 },
  sessionLabel: { fontSize: 13, color: launchColors.hex_6b7280, marginBottom: 4 },
  sessionValue: { fontSize: 16, fontWeight: '500', color: launchColors.hex_ffffff },
  focusAreas: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  focusAreaTag: { backgroundColor: launchColors.hex_f59e0b20, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  focusAreaText: { fontSize: 12, color: launchColors.hex_f59e0b },
  ratingContainer: { paddingHorizontal: 20, marginBottom: 24, alignItems: 'center' },
  ratingTitle: { fontSize: 16, color: launchColors.hex_9ca3af, marginBottom: 12 },
  ratingStars: { flexDirection: 'row', gap: 8 },
  starButton: { padding: 4 },
  star: { fontSize: 32, color: launchColors.hex_3a3a3a },
  starFilled: { color: launchColors.hex_f59e0b },
  ratingThanks: { fontSize: 16, color: launchColors.hex_10b981 },
  bottomSpacer: { height: 100 },
  fabContainer: { position: 'absolute', bottom: 20, left: 20, right: 20 },
  fab: {
    backgroundColor: launchColors.hex_3b82f6, borderRadius: 16, paddingVertical: 18,
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    shadowColor: launchColors.hex_3b82f6, shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 8, elevation: 8,
  },
  fabDisabled: { opacity: 0.7 },
  fabText: { fontSize: 17, fontWeight: '600', color: launchColors.hex_ffffff, marginLeft: 8 },
  icon: { fontSize: 20 },
});
