import { createSheet } from "@/shared/ui/create-sheet";

export const styles = createSheet({
  uploadContainer: {
    borderWidth: 2,
    borderStyle: "dashed",
    borderRadius: 12,
    padding: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  uploadContainerDisabled: { opacity: 0.5 },
  uploadIcon: { marginBottom: 12 },
  uploadTitle: { fontSize: 16, fontWeight: "600", marginBottom: 4 },
  uploadSubtitle: { fontSize: 14 },
  fileCard: { borderWidth: 1, borderRadius: 12, padding: 16, gap: 12 },
  fileInfo: { flexDirection: "row", alignItems: "center", gap: 12 },
  fileDetails: { flex: 1, gap: 2 },
  fileName: { fontSize: 15, fontWeight: "500" },
  fileMeta: { fontSize: 13 },
  progressContainer: { flexDirection: "row", alignItems: "center", gap: 12 },
  progressBar: { flex: 1, height: 4, borderRadius: 2, overflow: "hidden" },
  progressFill: { height: "100%", borderRadius: 2 },
  progressText: { fontSize: 12, minWidth: 35, textAlign: "right" },
  errorContainer: { gap: 4 },
  errorText: { fontSize: 13 },
  retryText: { fontSize: 13, fontWeight: "500", marginTop: 4 },
  warningContainer: { gap: 4 },
  warningText: { fontSize: 13 },
  fileActions: { flexDirection: "row", justifyContent: "flex-end" },
});
