import { createSheet } from "@/shared/ui/create-sheet";

export const quizPanelStyles = createSheet({
  container: { gap: 12 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: { flexDirection: "row", alignItems: "center", gap: 8 },
  title: { fontSize: 16, fontWeight: "600" },
  scoreBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 16 },
  scoreText: { fontSize: 14, fontWeight: "600" },
  quizList: { maxHeight: 500 },
  quizCard: {
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 12,
    gap: 12,
  },
  questionHeader: { flexDirection: "row", alignItems: "center", gap: 8 },
  questionNumber: { fontSize: 12, fontWeight: "500" },
  difficultyBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 4,
  },
  difficultyText: { fontSize: 11, fontWeight: "500" },
  conceptTag: { flex: 1, alignItems: "flex-end" },
  conceptText: { fontSize: 12 },
  question: { fontSize: 15, fontWeight: "500", lineHeight: 22 },
  optionsContainer: { gap: 8 },
  optionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
  },
  optionText: { fontSize: 14, flex: 1 },
  shortAnswerContainer: { gap: 8 },
  shortAnswerInput: {
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    minHeight: 80,
    textAlignVertical: "top",
  },
  revealButton: { alignSelf: "flex-start", paddingVertical: 8 },
  revealText: { fontSize: 14, fontWeight: "500" },
  answerReveal: { padding: 12, borderRadius: 8, gap: 4 },
  answerLabel: { fontSize: 12 },
  answerText: { fontSize: 15, fontWeight: "600" },
  explanationContainer: { padding: 12, borderRadius: 8, gap: 4 },
  explanationLabel: { fontSize: 12 },
  explanationText: { fontSize: 14, lineHeight: 20 },
});
