import { createSheet } from '@/shared/ui/create-sheet';

export const styles = createSheet({
  container: { gap: 12 },
  header: { gap: 8 },
  headerTitle: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  title: { fontSize: 16, fontWeight: '600' },
  progressInfo: { gap: 8 },
  progressBar: { height: 6, borderRadius: 3, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 3 },
  timeText: { fontSize: 13 },
  taskList: { maxHeight: 400 },
  taskCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 8,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  taskContent: { flex: 1, gap: 8 },
  taskText: { fontSize: 15, lineHeight: 22 },
  taskMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  priorityBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 4 },
  priorityText: { fontSize: 11, fontWeight: '500' },
  durationBadge: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  durationText: { fontSize: 12 },
  dependencyBadge: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  dependencyText: { fontSize: 12 },
});
