/**
 * Squads Service Constants
 */

import type { SquadRole, SquadPermission } from '../schemas';

export const MAX_SQUAD_MEMBERS = 50;
export const DEFAULT_SQUAD_SIZE = 10;
export const SYNERGY_POINTS_PER_LEVEL = [0, 100, 250, 500, 1000, 1750, 2750, 4000, 5500, 7250, 9250];

export const ROLE_HIERARCHY: SquadRole[] = ['FOUNDER', 'ADMIN', 'MODERATOR', 'MEMBER', 'GUEST'];

export const ROLE_PERMISSIONS: Record<SquadRole, SquadPermission[]> = {
  FOUNDER: ['VIEW_SQUAD', 'INVITE_MEMBERS', 'KICK_MEMBERS', 'MANAGE_ROLES', 'EDIT_SQUAD', 'DELETE_SQUAD', 'START_SESSION', 'MANAGE_CHALLENGE', 'MANAGE_BOSS', 'VIEW_ANALYTICS', 'PIN_MESSAGES', 'MODERATE_CHAT', 'USE_SYERGY_BOOST'],
  ADMIN: ['VIEW_SQUAD', 'INVITE_MEMBERS', 'KICK_MEMBERS', 'MANAGE_ROLES', 'EDIT_SQUAD', 'START_SESSION', 'MANAGE_CHALLENGE', 'MANAGE_BOSS', 'VIEW_ANALYTICS', 'PIN_MESSAGES', 'MODERATE_CHAT', 'USE_SYERGY_BOOST'],
  MODERATOR: ['VIEW_SQUAD', 'INVITE_MEMBERS', 'KICK_MEMBERS', 'START_SESSION', 'PIN_MESSAGES', 'MODERATE_CHAT', 'USE_SYERGY_BOOST'],
  MEMBER: ['VIEW_SQUAD', 'START_SESSION', 'USE_SYERGY_BOOST'],
  GUEST: ['VIEW_SQUAD'],
};
