import { StyleSheet } from "react-native";
import { createSheet } from "@/shared/ui/create-sheet";

export const styles = createSheet({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  skeletonContainer: { width: "100%" },
  skeletonBase: {},
  spinner: { marginBottom: 16 },
  progressContainer: { width: "100%", alignItems: "center" },
  progressBarBackground: {
    width: "100%",
    height: 8,
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 8,
  },
  progressBarFill: { height: "100%", borderRadius: 4 },
  progressText: { fontSize: 14, fontWeight: "600" },
  loadingMessage: { fontSize: 16, fontWeight: "600", textAlign: "center" },
  loadingSubmessage: { fontSize: 14, textAlign: "center", marginTop: 8 },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  emptyIcon: { fontSize: 64, marginBottom: 16 },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
  },
  emptySubtitle: {
    fontSize: 14,
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 20,
  },
  emptyActions: { flexDirection: "row", gap: 12 },
  primaryButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  primaryButtonText: { fontSize: 16, fontWeight: "600" },
  secondaryButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  secondaryButtonText: { fontSize: 16 },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  errorIconContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
  },
  errorIcon: { fontSize: 40 },
  errorTitle: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
  },
  errorDetails: {
    fontSize: 14,
    textAlign: "center",
    marginBottom: 24,
    paddingHorizontal: 16,
  },
  errorActions: { flexDirection: "row", gap: 12 },
  retryButton: { paddingHorizontal: 24, paddingVertical: 12, borderRadius: 12 },
  retryButtonText: { fontSize: 16, fontWeight: "600" },
  dismissButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  dismissButtonText: { fontSize: 16 },
  successContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 32,
  },
  successIcon: { fontSize: 64, marginBottom: 16 },
  successTitle: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 8,
  },
  successSubtitle: { fontSize: 14, textAlign: "center", marginBottom: 24 },
  successButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  successButtonText: { fontSize: 16, fontWeight: "600" },
  disabledContainer: { position: "relative" },
  disabledOverlay: {
    ...StyleSheet.absoluteFill,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
  },
  disabledReasonContainer: {
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  disabledReasonIcon: { fontSize: 24, marginBottom: 8 },
  disabledReasonText: { fontSize: 14, textAlign: "center" },
});
