/**
 * Jest Configuration for VEX App
 * 
 * Expo SDK 56 + React Native + TypeScript Testing Setup
 */

const legacyFailingTests = require('./jest.legacy-failing-tests');

module.exports = {
  preset: 'jest-expo',
  testEnvironment: 'node',
  moduleFileExtensions: ['mjs', 'ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@theme/(.*)$': '<rootDir>/src/theme/$1',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@navigation/(.*)$': '<rootDir>/src/navigation/$1',
    '^@store/(.*)$': '<rootDir>/src/store/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@overlays/(.*)$': '<rootDir>/src/overlays/$1',
    '^@animation/(.*)$': '<rootDir>/src/animation/$1',
    '^@icons/(.*)$': '<rootDir>/src/icons/$1',
    '^@a11y/(.*)$': '<rootDir>/src/a11y/$1',
    '^@events/(.*)$': '<rootDir>/src/events/$1',
    '^@analytics/(.*)$': '<rootDir>/src/analytics/$1',
    '^react-native-gesture-handler$': '<rootDir>/__mocks__/react-native-gesture-handler.js',
    '^@featureFlags/(.*)$': '<rootDir>/src/featureFlags/$1',
    '^@settings/(.*)$': '<rootDir>/src/settings/$1',
    '^@persistence/(.*)$': '<rootDir>/src/persistence/$1',
    '^@hooks$': '<rootDir>/src/hooks/index.ts',
    '^@network/(.*)$': '<rootDir>/src/network/$1',
    '^@network$': '<rootDir>/src/network/index.ts',
    '^@errors/(.*)$': '<rootDir>/src/errors/$1',
    '^@states/(.*)$': '<rootDir>/src/states/$1',
    '^@shell/(.*)$': '<rootDir>/src/shell/$1',
    '^@app/(.*)$': '<rootDir>/src/app/$1',
    '^@screens/(.*)$': '<rootDir>/src/screens/$1',
    '^@validation/(.*)$': '<rootDir>/src/validation/$1',
    '^expo-modules-core/src/Refs$': '<rootDir>/src/__tests__/mocks/expo-modules-core-Refs.ts',
    '^expo-modules-core/src/web/index.web$': '<rootDir>/src/__tests__/mocks/expo-modules-core-web-index.ts',
    '^expo-haptics$': '<rootDir>/src/__tests__/mocks/expo-haptics.ts',
    '^expo-status-bar$': '<rootDir>/src/__tests__/mocks/expo-status-bar.ts',
    '^react-native/Libraries/Animated/NativeAnimatedHelper$': '<rootDir>/src/__tests__/mocks/native-animated-helper.ts',
    '^@sentry/node$': '<rootDir>/src/__tests__/mocks/sentry-node.ts',
    '^expo-crypto$': '<rootDir>/__mocks__/expo-crypto.js',
  },
  setupFiles: ['<rootDir>/src/__tests__/setupNativeBridge.js'],
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/setupTests.ts'],
  transform: { '^.+\\.(mjs|js|jsx|ts|tsx)$': 'babel-jest' },
  transformIgnorePatterns: [
    'node_modules/(?!((react-native|@react-native|@react-navigation|@gorhom|react-native-reanimated|react-native-gesture-handler|react-native-svg|styled-components|@tanstack|expo|expo-modules-core|expo-crypto|@expo|expo-document-picker|msw|@mswjs|@open-draft|rettime|until-async|headers-polyfill|outvariant|strict-event-emitter|is-node-process|graphql|@revenuecat)/))',
  ],
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.test.ts',
    '<rootDir>/src/**/__tests__/**/*.test.tsx',
    '<rootDir>/src/app_root/**/__tests__/**/*.test.ts',
    '<rootDir>/src/app_root/**/__tests__/**/*.test.tsx',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/archive/',
    '<rootDir>/jobs/',
    '<rootDir>/e2e/',
    '<rootDir>/tmp/',
    '<rootDir>/coverage/',
    ...legacyFailingTests,
    '<rootDir>/src/archive/',
    '<rootDir>/src/features/battle-pass/',

    '<rootDir>/src/features/challenges/',
    '<rootDir>/src/features/inventory/',
    '<rootDir>/src/features/shop/',
    '<rootDir>/src/features/squads/',
    '<rootDir>/src/features/themes/',
  ],
  collectCoverageFrom: [
    'src/**/*.{service,repository,hooks,analytics,events}.{ts,tsx}',
    'src/features/{session-start,session-completion,focus-contract,focus-identity,daily-mission,streaks,rewards,companion,personal-bests,account-deletion}/**/*.{ts,tsx}',
    'src/session/**/*.{ts,tsx}',
    'src/shared/monetization/**/*.{ts,tsx}',
    'src/privacy/**/*.{ts,tsx}',
    'src/navigation/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    '!src/**/__tests__/**',
    '!src/**/*.test.ts',
    '!src/**/*.test.tsx',
    '!src/features/{battle-pass,boss,challenges,inventory,shop,squads,themes}/**',
    '!src/types/supabase.ts',
  ],
  coveragePathIgnorePatterns: ['/node_modules/', '/__tests__/', '/__mocks__/'],
  coverageThreshold: { global: { branches: 70, functions: 70, lines: 70, statements: 70 } },
  moduleDirectories: ['node_modules', 'src'],
  clearMocks: true,
  restoreMocks: true,
  verbose: true,
  testTimeout: 10000,
  globals: { 'ts-jest': { tsconfig: { jsx: 'react-jsx' } } },
};
