import { getApiClient, type ApiError } from '../api/client'; import { getMMKVStorageAdapter } from '../persistence/MMKVStorageAdapter'; import { useAuthStore } from '../store'; import type { Nullable } from '../types/global'; import type { User } from '../types/models'; import { createDebugger } from '../utils/debug'; import { captureSilentFailure } from '../utils/silent-failure'; import { authenticateLocally, checkLocalBiometricAvailability } from './auth-local-auth'; import { RefreshResponseSchema, TokenResponseSchema, transformAuthUser, type RefreshResponse, type TokenResponse } from './auth-schemas'; import { STORAGE_KEYS, type AuthTokens, type LoginCredentials, type RegisterData, type SessionInfo } from './auth-types';
const authDebug = createDebugger('auth'); export type { AuthTokens, LoginCredentials, RegisterData, SessionInfo };
export class AuthService { private refreshPromise: Promise<boolean> | null = null; private tokens: Nullable<AuthTokens> = null; private biometricAvailable = false;
constructor() { this.checkBiometricAvailability(); getApiClient().setAuthProvider({ getAccessToken: this.getAccessToken.bind(this), refreshToken: this.refreshToken.bind(this), logout: this.logout.bind(this) }); }
private async checkBiometricAvailability(): Promise<void> { try { this.biometricAvailable = await checkLocalBiometricAvailability(); authDebug.debug('Biometric available: %s', String(this.biometricAvailable)); } catch (error) { authDebug.debug('Biometric check failed: %s', (error as Error).message); this.biometricAvailable = false; } }
async initialize(): Promise<void> { authDebug.debug('Initializing auth service'); const storage = getMMKVStorageAdapter(); try { const [accessToken, refreshToken, expiresStr] = await Promise.all([storage.getItem(STORAGE_KEYS.ACCESS_TOKEN), storage.getItem(STORAGE_KEYS.REFRESH_TOKEN), storage.getItem(STORAGE_KEYS.TOKEN_EXPIRES)]); if (!accessToken || !refreshToken || !expiresStr) return; const expiresAt = parseInt(expiresStr, 10); this.tokens = { accessToken, refreshToken, expiresAt }; if (this.isTokenExpired(expiresAt) && !(await this.refreshToken())) { await this.clearTokens(); return; } const userData = await storage.getItem(STORAGE_KEYS.USER_DATA); if (!userData) return; const user = JSON.parse(userData) as User; useAuthStore.getState().login(user.id, this.tokens?.accessToken || ''); authDebug.debug('Auth restored from storage'); } catch (error) { authDebug.error('Auth initialization failed', error as Error); await this.clearTokens(); } }
async login(credentials: LoginCredentials): Promise<User> { authDebug.debug('Attempting login for: %s', credentials.email); try { const response = await getApiClient().post<TokenResponse>('/auth/login', credentials, { schema: TokenResponseSchema, skipAuth: true }); return await this.applyAuthResponse(response, 'Login'); } catch (error) { authDebug.error('Login failed', error as Error); throw this.formatError(error as ApiError); } }
async register(data: RegisterData): Promise<User> { authDebug.debug('Attempting registration for: %s', data.email); try { const body = { email: data.email, password: data.password, firstName: data.firstName, lastName: data.lastName }; const response = await getApiClient().post<TokenResponse>('/auth/register', body, { schema: TokenResponseSchema, skipAuth: true }); return await this.applyAuthResponse(response, 'Registration'); } catch (error) { authDebug.error('Registration failed', error as Error); throw this.formatError(error as ApiError); } }
async logout(): Promise<void> { authDebug.debug('Logging out user'); try { getApiClient().post('/auth/logout').catch(() => {}); } catch (error) { captureSilentFailure(error, { feature: 'services', operation: 'network-fallback', type: 'network' }); } await this.clearTokens(); useAuthStore.getState().logout(); authDebug.debug('Logout complete'); }
async getAccessToken(): Promise<Nullable<string>> { if (!this.tokens) return null; if (this.tokens.expiresAt - Date.now() >= 300000) return this.tokens.accessToken; return (await this.refreshToken()) ? this.tokens?.accessToken || null : null; }
async refreshToken(): Promise<boolean> { if (this.refreshPromise) return this.refreshPromise; this.refreshPromise = this.performRefresh(); try { return await this.refreshPromise; } finally { this.refreshPromise = null; } }
async validateSession(): Promise<boolean> { const token = await this.getAccessToken(); if (!token) return false; try { await getApiClient().get('/auth/validate'); return true; } catch (error) { captureSilentFailure(error, { feature: 'services', operation: 'network-fallback', type: 'network' }); return false; } }
async getSessionInfo(): Promise<SessionInfo> { const storage = getMMKVStorageAdapter(); const sessionStart = await storage.getItem(STORAGE_KEYS.SESSION_START); const sessionDuration = sessionStart ? Date.now() - parseInt(sessionStart, 10) : 0; if (!this.tokens) return { isValid: false, expiresAt: null, timeRemaining: 0, sessionDuration }; const timeRemaining = Math.max(0, this.tokens.expiresAt - Date.now()); return { isValid: timeRemaining > 0, expiresAt: this.tokens.expiresAt, timeRemaining, sessionDuration }; }
isBiometricAvailable(): boolean { return this.biometricAvailable; }
async authenticateWithBiometrics(promptMessage = 'Authenticate'): Promise<boolean> { if (!this.biometricAvailable) return false; try { return await authenticateLocally(promptMessage); } catch (error) { authDebug.error('Biometric auth failed', error as Error); return false; } }
async setBiometricEnabled(enabled: boolean): Promise<void> { await getMMKVStorageAdapter().setItem(STORAGE_KEYS.BIOMETRIC_ENABLED, JSON.stringify(enabled)); }
async isBiometricEnabled(): Promise<boolean> { const value = await getMMKVStorageAdapter().getItem(STORAGE_KEYS.BIOMETRIC_ENABLED); return value ? JSON.parse(value) : false; }
private async applyAuthResponse(response: TokenResponse, action: string): Promise<User> { const { accessToken, refreshToken, expiresIn, user } = response; await this.storeTokens({ accessToken, refreshToken, expiresAt: Date.now() + expiresIn * 1000 }); const storage = getMMKVStorageAdapter(); await storage.setItem(STORAGE_KEYS.USER_DATA, JSON.stringify(user)); await storage.setItem(STORAGE_KEYS.SESSION_START, Date.now().toString()); const fullUser = transformAuthUser(user); useAuthStore.getState().login(fullUser.id, accessToken); authDebug.debug('%s successful for user: %s', action, fullUser.id); return fullUser; }
private async storeTokens(tokens: AuthTokens): Promise<void> { this.tokens = tokens; const storage = getMMKVStorageAdapter(); await Promise.all([storage.setItem(STORAGE_KEYS.ACCESS_TOKEN, tokens.accessToken), storage.setItem(STORAGE_KEYS.REFRESH_TOKEN, tokens.refreshToken), storage.setItem(STORAGE_KEYS.TOKEN_EXPIRES, tokens.expiresAt.toString())]); }
private async clearTokens(): Promise<void> { this.tokens = null; const storage = getMMKVStorageAdapter(); await Promise.all([storage.removeItem(STORAGE_KEYS.ACCESS_TOKEN), storage.removeItem(STORAGE_KEYS.REFRESH_TOKEN), storage.removeItem(STORAGE_KEYS.TOKEN_EXPIRES), storage.removeItem(STORAGE_KEYS.USER_DATA)]); }
private async performRefresh(): Promise<boolean> { if (!this.tokens?.refreshToken) { authDebug.debug('No refresh token available'); return false; } try { const response = await getApiClient().post<RefreshResponse>('/auth/refresh', { refreshToken: this.tokens.refreshToken }, { schema: RefreshResponseSchema, skipAuth: true, retries: 1 }); this.tokens = { ...this.tokens, accessToken: response.accessToken, expiresAt: Date.now() + response.expiresIn * 1000 }; await getMMKVStorageAdapter().setItem(STORAGE_KEYS.ACCESS_TOKEN, response.accessToken); await getMMKVStorageAdapter().setItem(STORAGE_KEYS.TOKEN_EXPIRES, this.tokens.expiresAt.toString()); authDebug.debug('Token refreshed successfully'); return true; } catch (error) { authDebug.error('Token refresh failed', error as Error); await this.clearTokens(); return false; } }
private isTokenExpired(expiresAt: number): boolean { return Date.now() >= expiresAt; }
private formatError(error: ApiError): Error { const messages: Partial<Record<string, string>> = { AUTH_ERROR: 'Invalid email or password', VALIDATION_ERROR: 'Please check your input and try again', NETWORK_ERROR: 'Network error. Please check your connection.', RATE_LIMIT: 'Too many attempts. Please try again later.', }; const formattedError = new Error(messages[error.code] ?? error.message); formattedError.name = error.code; (formattedError as Error & { status: number }).status = error.status; return formattedError; } }
export { getAuthService, resetAuthService } from './auth-service-singleton';
