export type RecommendationType =
  | "OPTIMAL_TIME"
  | "STREAK_PROTECTION"
  | "COMEBACK_BUILDER"
  | "DIFFICULTY_ADJUST"
  | "CHALLENGE_SYNC"
  | "BOSS_PREP"
  | "HABIT_BUILDER"
  | "ENERGY_BASED";
