import { createSheet } from '@/shared/ui/create-sheet';

export const paywallStyles = createSheet({
  screen: { flex: 1 },
  content: { paddingHorizontal: 20, gap: 20 },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
    alignItems: 'flex-start',
  },
  headerCopy: { flex: 1, gap: 6 },
  eyebrow: {
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  title: { fontSize: 32, fontWeight: '800', lineHeight: 38 },
  featureCard: { borderRadius: 24, padding: 20, gap: 10 },
  featureIconBadge: {
    alignItems: 'center',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  featureTitle: { fontSize: 22, fontWeight: '800' },
  featureBenefit: { fontSize: 15, lineHeight: 22 },
  heroCard: { borderRadius: 24, padding: 18, gap: 12 },
  heroTitle: { fontSize: 24, fontWeight: '800' },
  heroCopy: { fontSize: 15, lineHeight: 22 },
  planList: { gap: 12 },
  planCard: { borderRadius: 22, padding: 18, gap: 10 },
  planHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 16,
  },
  planTitle: { fontSize: 22, fontWeight: '800' },
  planSubtitle: { fontSize: 14, lineHeight: 20, marginTop: 2 },
  planPrice: { fontSize: 28, fontWeight: '800' },
  footerActions: { flexDirection: 'row', gap: 12, flexWrap: 'wrap' },
  boundaryCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
  },
  boundaryText: { fontSize: 14, lineHeight: 20, flex: 1 },
  errorContainer: { gap: 16 },
  supportSection: { alignItems: 'center', gap: 8 },
  supportText: { fontSize: 13, textAlign: 'center' },
  badgeContainer: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  trialBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  trialBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  planBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  planBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  trialText: { fontSize: 13, fontWeight: '600', marginTop: 4 },
  featuresList: { gap: 10 },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 16,
  },
  featureIconShell: {
    alignItems: 'center',
    borderRadius: 14,
    height: 28,
    justifyContent: 'center',
    width: 28,
  },
  featureTextContainer: { flex: 1, gap: 2 },
  featureRowTitle: { fontSize: 16, fontWeight: '700' },
  featureRowDescription: { fontSize: 13, lineHeight: 18 },
  skeletonContainer: { gap: 20, paddingHorizontal: 20 },
  skeletonHeader: { gap: 12, marginTop: 20 },
  skeletonFeatures: { gap: 12, marginTop: 20 },
});
