import React, { useState, useEffect, useCallback } from "react"; import { Modal, Dimensions } from "react-native"; import Animated, { useAnimatedStyle, withSpring, withTiming, withSequence, withRepeat, FadeIn, FadeInUp, FadeOut } from "react-native-reanimated"; import { Box } from "../../../components/primitives/Box"; import { Text } from "../../../components/primitives/Text"; import { Button } from "../../../components/primitives/Button"; import { useTheme } from "../../../theme";
const { width: SCREEN_WIDTH } = Dimensions.get("window");
export interface DailyReward { day: number; type: "coins" | "gems" | "boost" | "chest"; amount: number; label: string; icon: string; }
export interface DailyLoginModalProps { visible: boolean; currentDay: number; streakDays: number; isClaimed: boolean; onClaim: () => void; onDismiss: () => void; }
const REWARD_SCHEDULE: DailyReward[] = [ { day: 1, type: "coins", amount: 50, label: "50 Coins", icon: "🪙" }, { day: 2, type: "coins", amount: 75, label: "75 Coins", icon: "🪙" }, { day: 3, type: "gems", amount: 5, label: "5 Gems", icon: "💎" }, { day: 4, type: "coins", amount: 100, label: "100 Coins", icon: "🪙" }, { day: 5, type: "boost", amount: 1, label: "XP Boost", icon: "⚡" }, { day: 6, type: "gems", amount: 10, label: "10 Gems", icon: "💎" }, { day: 7, type: "chest", amount: 1, label: "Mystery Chest", icon: "🎁" }, ];
function DayRewardItem({ reward, status, index }: { reward: DailyReward; status: "past" | "current" | "future"; index: number }): JSX.Element { const { theme } = useTheme();
const getStatusColor = () => { switch (status) { case "past": return theme.colors.success.DEFAULT; case "current": return theme.colors.primary[500]; default: return theme.colors.background.tertiary; } };
const getStatusIcon = () => { switch (status) { case "past": return "✓"; case "current": return "★"; default:
        return `${reward.day}`;
} };
const scaleStyle = useAnimatedStyle(() => ({ transform: [ { scale: status === "current" ? withRepeat(withSequence(withSpring(1.05, { damping: 10 }), withSpring(1, { damping: 10 })), -1, true) : 1, }, ], }));
return ( <Animated.View entering={FadeIn.duration(300).delay(index * 50)} style={[ { width: (SCREEN_WIDTH - 60) / 7 - 4, alignItems: "center", }, ]} > <Box width={28} height={28} borderRadius="full" bg={status === "current" ? "primary.500" : "background.tertiary"} justifyContent="center" alignItems="center" mb="xs"> <Text fontSize={12} color={status === "current" ? "text.inverse" : "text.tertiary"} fontWeight={status === "current" ? "700" : "400"}> {getStatusIcon()} </Text> </Box>
      <Box width={40} height={40} borderRadius="lg" bg={status === "current" ? `${theme.colors.primary[500]}30` : "background.secondary"} borderWidth={status === "current" ? 2 : 0} borderColor={status === "current" ? "primary.500" : undefined} justifyContent="center" alignItems="center">
<Text fontSize={20}>{reward.icon}</Text> </Box>
<Text variant="caption" color={status === "current" ? "primary.500" : "text.tertiary"} fontWeight={status === "current" ? "600" : "400"} textAlign="center" mt="xs" numberOfLines={1} style={{ fontSize: 10 }}> {reward.label} </Text> </Animated.View> ); }
function FlyingReward({ reward, onComplete }: { reward: DailyReward; onComplete: () => void }): JSX.Element { const flyStyle = useAnimatedStyle(() => ({ transform: [ { translateY: withSequence(withTiming(-50, { duration: 300 }), withTiming(-150, { duration: 500 })), }, { scale: withSequence(withSpring(1.5, { damping: 5 }), withTiming(0.8, { duration: 400 })), }, ], opacity: withSequence(withTiming(1, { duration: 100 }), withTiming(0, { duration: 600 })), }));
useEffect(() => { const timer = setTimeout(onComplete, 800); return () => clearTimeout(timer); }, [onComplete]);
return ( <Animated.View style={[ { position: "absolute", top: "50%", left: "50%", marginLeft: -30, marginTop: -30, }, flyStyle, ]} > <Box width={60} height={60} borderRadius="full" bg="primary.500" justifyContent="center" alignItems="center"> <Text fontSize={32}>{reward.icon}</Text> </Box> </Animated.View> ); }
export function DailyLoginModal({ visible, currentDay, streakDays, isClaimed, onClaim, onDismiss }: DailyLoginModalProps): JSX.Element { const { theme } = useTheme(); const [claimed, setClaimed] = useState(isClaimed); const [showFlyingReward, setShowFlyingReward] = useState(false);
const currentReward = REWARD_SCHEDULE[currentDay - 1]!;
useEffect(() => { if (visible && claimed) { const timer = setTimeout(onDismiss, 2000); return () => clearTimeout(timer); } if (visible && !claimed) { const timer = setTimeout(onDismiss, 5000); return () => clearTimeout(timer); } return undefined; }, [visible, claimed, onDismiss]);
const handleClaim = useCallback(() => { setShowFlyingReward(true); onClaim(); setTimeout(() => setClaimed(true), 800); }, [onClaim]);
const handleFlyingComplete = useCallback(() => { setShowFlyingReward(false); }, []);
return ( <Modal visible={visible} transparent animationType="fade" statusBarTranslucent>
      <Box flex={1} bg={`${theme.colors.background.primary}F0`} justifyContent="center" alignItems="center">
<Animated.View entering={FadeInUp.duration(400)} exiting={FadeOut.duration(300)} style={{ width: SCREEN_WIDTH - 40, maxWidth: 400 }}> <Box bg="background.secondary" borderRadius="2xl" borderWidth={1} borderColor="border.light" overflow="hidden"> <Box p="xl" bg="primary.500" alignItems="center"> <Text fontSize={48} mb="sm"> 🎁 </Text> <Text variant="h2" color="text.inverse" textAlign="center"> Daily Login </Text> <Text variant="body" color="text.secondary" textAlign="center" style={{ opacity: 0.8 }}> Day {currentDay} of 7 </Text> {streakDays >= 7 && ( <Box mt="sm" px="md" py="xs" borderRadius="full" bg="accent.orange"> <Text variant="caption" color="text.inverse" fontWeight="700"> 🔥 {streakDays}-Day Streak! </Text> </Box> )} </Box>
<Box p="lg"> <Box flexDirection="row" justifyContent="space-between"> {REWARD_SCHEDULE.map((reward, index) => { const day = index + 1; const status: "past" | "current" | "future" = day < currentDay ? "past" : day === currentDay ? "current" : "future"; return <DayRewardItem key={reward.day} reward={reward} status={status} index={index} />; })} </Box> </Box>
<Box p="lg" alignItems="center"> <Text variant="caption" color="text.tertiary" mb="sm"> TODAY'S REWARD </Text>
              <Box flexDirection="row" alignItems="center" gap="md" p="lg" borderRadius="xl" bg={`${theme.colors.primary[500]}15`} borderWidth={2} borderColor="primary.500">
<Text fontSize={48}>{currentReward.icon}</Text> <Box> <Text variant="h3" color="text.primary" fontWeight="700"> {currentReward.label} </Text> <Text variant="caption" color="text.tertiary"> {currentReward.type === "coins" && "Spend in the shop"} {currentReward.type === "gems" && "Premium currency"} {currentReward.type === "boost" && "2x XP for 1 hour"} {currentReward.type === "chest" && "Contains random rewards"} </Text> </Box> </Box> </Box>
<Box p="xl" style={{ borderTopWidth: 1, borderTopColor: theme.colors.border.light, }} > {claimed ? ( <Box alignItems="center"> <Text variant="h4" color="success.DEFAULT"> ✅ Claimed! </Text> <Text variant="caption" color="text.tertiary" mt="sm"> Come back tomorrow for more </Text> </Box> ) : ( <Button variant="primary" size="lg" fullWidth onPress={handleClaim} accessibilityLabel="🎁 Claim Reward button" accessibilityRole="button" accessibilityHint="Activates this control"> 🎁 Claim Reward </Button> )} </Box>
{showFlyingReward && currentReward && <FlyingReward reward={currentReward} onComplete={handleFlyingComplete} />} </Box> </Animated.View> </Box> </Modal> ); }
export default DailyLoginModal;
