import type { SessionPreset } from "../types";

export const DEFAULT_PRESETS: Omit<
  SessionPreset,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "Quick Focus",
    description: "Short burst of focused work - perfect for quick tasks",
    duration: 15 * 60,
    breakDuration: 2 * 60,
    longBreakDuration: 5 * 60,
    intervals: 1,
    longBreakInterval: 4,
    isDefault: true,
    category: "quick",
    tags: ["quick", "focus"],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: false,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
  },
  {
    name: "Pomodoro Classic",
    description: "Traditional Pomodoro technique - 25 min work, 5 min break",
    duration: 25 * 60,
    breakDuration: 5 * 60,
    longBreakDuration: 15 * 60,
    intervals: 4,
    longBreakInterval: 4,
    isDefault: true,
    category: "work",
    tags: ["pomodoro", "classic", "work"],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: true,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
  },
  {
    name: "Deep Work",
    description: "Extended focus session for complex tasks",
    duration: 50 * 60,
    breakDuration: 10 * 60,
    longBreakDuration: 30 * 60,
    intervals: 2,
    longBreakInterval: 2,
    isDefault: true,
    category: "deep",
    tags: ["deep", "focus", "complex"],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: true,
    strictMode: true,
    autoStartBreaks: false,
    autoStartNextInterval: false,
  },
  {
    name: "Study Sprint",
    description: "Intense study session with regular breaks",
    duration: 45 * 60,
    breakDuration: 8 * 60,
    longBreakDuration: 20 * 60,
    intervals: 3,
    longBreakInterval: 3,
    isDefault: true,
    category: "study",
    tags: ["study", "learning", "education"],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: true,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
  },
  {
    name: "Creative Flow",
    description: "Uninterrupted creative work time",
    duration: 90 * 60,
    breakDuration: 15 * 60,
    longBreakDuration: 30 * 60,
    intervals: 1,
    longBreakInterval: 1,
    isDefault: true,
    category: "creative",
    tags: ["creative", "flow", "art", "design"],
    soundEnabled: true,
    vibrationEnabled: false,
    dndEnabled: true,
    strictMode: true,
    autoStartBreaks: false,
    autoStartNextInterval: false,
  },
  {
    name: "Meeting Prep",
    description: "Quick preparation before important meetings",
    duration: 10 * 60,
    breakDuration: 2 * 60,
    longBreakDuration: 5 * 60,
    intervals: 1,
    longBreakInterval: 1,
    isDefault: true,
    category: "work",
    tags: ["meeting", "prep", "quick"],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: false,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
  },
  {
    name: "Coding Block",
    description: "Focused development time with strategic breaks",
    duration: 55 * 60,
    breakDuration: 10 * 60,
    longBreakDuration: 25 * 60,
    intervals: 3,
    longBreakInterval: 3,
    isDefault: true,
    category: "development",
    tags: ["coding", "development", "engineering"],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: true,
    strictMode: true,
    autoStartBreaks: false,
    autoStartNextInterval: false,
  },
  {
    name: "Reading Session",
    description: "Focused reading and comprehension time",
    duration: 30 * 60,
    breakDuration: 5 * 60,
    longBreakDuration: 15 * 60,
    intervals: 2,
    longBreakInterval: 2,
    isDefault: true,
    category: "learning",
    tags: ["reading", "learning", "books"],
    soundEnabled: true,
    vibrationEnabled: false,
    dndEnabled: true,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
  },
  {
    name: "Writing Sprint",
    description: "Intense writing focus with recovery breaks",
    duration: 40 * 60,
    breakDuration: 8 * 60,
    longBreakDuration: 20 * 60,
    intervals: 3,
    longBreakInterval: 3,
    isDefault: true,
    category: "creative",
    tags: ["writing", "content", "creation"],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: true,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
  },
  {
    name: "Meditation",
    description: "Mindfulness and meditation practice",
    duration: 20 * 60,
    breakDuration: 5 * 60,
    longBreakDuration: 10 * 60,
    intervals: 1,
    longBreakInterval: 1,
    isDefault: true,
    category: "wellness",
    tags: ["meditation", "mindfulness", "wellness"],
    soundEnabled: true,
    vibrationEnabled: false,
    dndEnabled: true,
    strictMode: true,
    autoStartBreaks: false,
    autoStartNextInterval: false,
  },
];
