import { createSheet } from '@/shared/ui/create-sheet';
import { lightColors } from '@/theme/tokens/colors';


export const styles = createSheet({
  container: {
    backgroundColor: lightColors.text.inverse,
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    marginHorizontal: 12,
    borderLeftWidth: 4,
    shadowColor: lightColors.text.primary,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  header: { flexDirection: 'row', alignItems: 'flex-start' },
  icon: { fontSize: 24, marginRight: 12 },
  info: { flex: 1 },
  title: { fontSize: 16, fontWeight: '600', color: lightColors.semantic.backgroundMuted },
  subtitle: { fontSize: 13, color: lightColors.text.muted, marginTop: 2 },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  statusText: { fontSize: 12, fontWeight: '600' },
  progressSection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    gap: 12,
  },
  progressBarContainer: {
    flex: 1,
    height: 6,
    backgroundColor: lightColors.border.light,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBar: { height: '100%', borderRadius: 3 },
  progressText: {
    fontSize: 14,
    fontWeight: '600',
    color: lightColors.text.muted,
    minWidth: 40,
  },
  fileInfo: {
    marginTop: 12,
    padding: 12,
    backgroundColor: lightColors.surface.button,
    borderRadius: 8,
  },
  fileSize: { fontSize: 14, fontWeight: '500', color: lightColors.text.muted },
  fileUrl: { fontSize: 12, color: lightColors.text.muted, marginTop: 4 },
  errorSection: {
    marginTop: 12,
    padding: 12,
    backgroundColor: lightColors.error[50],
    borderRadius: 8,
  },
  errorText: { fontSize: 13, color: lightColors.semantic.danger },
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 16,
    gap: 12,
  },
  button: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    minWidth: 100,
    alignItems: 'center',
  },
  cancelButton: { backgroundColor: lightColors.surface.button },
  cancelButtonText: { color: lightColors.text.muted, fontWeight: '500' },
  loadingIndicator: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  skeletonPill: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: lightColors.border.light,
  },
  loadingText: {
    fontSize: 14,
    color: lightColors.accent.blue,
    fontWeight: '500',
  },
  downloadButton: { backgroundColor: lightColors.accent.green },
  downloadButtonText: { color: lightColors.text.inverse, fontWeight: '600' },
  retryButton: { backgroundColor: lightColors.accent.blue },
  retryButtonText: { color: lightColors.text.inverse, fontWeight: '600' },
});
