import { createSheet } from '@/shared/ui/create-sheet';
import { lightColors } from '@/theme/tokens/colors';


export const styles = createSheet({
  container: { marginVertical: 8 },
  label: {
    fontSize: 12,
    fontWeight: '500',
    color: lightColors.text.muted,
    marginBottom: 8,
    marginLeft: 4,
  },
  selector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 8,
    backgroundColor: lightColors.surface.button,
    borderWidth: 1,
    borderColor: lightColors.border.light,
  },
  selectorDisabled: { opacity: 0.5 },
  selectedContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    flex: 1,
    gap: 6,
  },
  selectedChip: {
    backgroundColor: lightColors.primary[50],
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  selectedChipText: {
    fontSize: 12,
    color: lightColors.semantic.primaryPressed,
    fontWeight: '500',
  },
  placeholder: { color: lightColors.text.muted, fontSize: 14 },
  chevron: { fontSize: 12, color: lightColors.text.muted, marginLeft: 8 },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: lightColors.text.inverse,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: lightColors.border.light,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: lightColors.semantic.backgroundMuted,
  },
  closeButton: {
    fontSize: 16,
    color: lightColors.semantic.primary,
    fontWeight: '500',
  },
  modalScroll: { padding: 16 },
  categorySection: { marginBottom: 20 },
  categoryTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: lightColors.text.muted,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  metricOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  metricOptionSelected: { backgroundColor: lightColors.surface.button },
  metricOptionDisabled: { opacity: 0.4 },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: lightColors.border.light,
    marginRight: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxSelected: {
    backgroundColor: lightColors.semantic.primary,
    borderColor: lightColors.semantic.primary,
  },
  checkmark: {
    color: lightColors.text.inverse,
    fontSize: 12,
    fontWeight: '700',
  },
  metricLabel: { fontSize: 14, color: lightColors.text.muted },
  metricLabelSelected: { color: lightColors.semantic.backgroundMuted, fontWeight: '500' },
  metricLabelDisabled: { color: lightColors.text.muted },
});
