import { createSheet } from '@/shared/ui/create-sheet';
import { lightColors } from '@/theme/tokens/colors';

export const styles = createSheet({
  container: { flex: 1, backgroundColor: lightColors.semantic.obsidian },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: lightColors.semantic.obsidian,
  },
  loadingText: { marginTop: 16, color: lightColors.text.muted, fontSize: 16 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: lightColors.semantic.obsidian,
    borderBottomWidth: 1,
    borderBottomColor: lightColors.semantic.obsidian,
  },
  coachInfo: { flex: 1 },
  coachName: {
    fontSize: 20,
    fontWeight: '700',
    color: lightColors.text.inverse,
  },
  statusBadge: { marginTop: 4 },
  statusText: { fontSize: 12, color: lightColors.text.muted },
  stateIndicator: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  stateDot: { width: 8, height: 8, borderRadius: 4 },
  stateLabel: { fontSize: 12, color: lightColors.text.muted },
  recommendationCard: {
    margin: 16,
    padding: 16,
    backgroundColor: lightColors.semantic.obsidian,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: lightColors.semantic.primary,
  },
  recommendationTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: lightColors.semantic.primary,
    marginBottom: 8,
  },
  recommendationReason: {
    fontSize: 14,
    color: lightColors.border.light,
    marginBottom: 12,
    lineHeight: 20,
  },
  startSessionButton: {
    backgroundColor: lightColors.semantic.primary,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  startSessionButtonText: {
    color: lightColors.text.inverse,
    fontSize: 14,
    fontWeight: '600',
  },
  chatContainer: { flex: 1 },
  chatContent: { padding: 16, paddingBottom: 100 },
  messageContainer: {
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  coachMessageContainer: { justifyContent: 'flex-start' },
  userMessageContainer: { justifyContent: 'flex-end' },
  systemMessageContainer: { justifyContent: 'center' },
  coachAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: lightColors.semantic.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  coachAvatarText: { fontSize: 16 },
  coachAvatarSmall: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: lightColors.semantic.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  coachAvatarTextSmall: { fontSize: 14 },
  messageBubble: { maxWidth: '80%', padding: 12, borderRadius: 16 },
  coachBubble: {
    backgroundColor: lightColors.semantic.obsidian,
    borderBottomLeftRadius: 4,
  },
  userBubble: {
    backgroundColor: lightColors.semantic.primary,
    borderBottomRightRadius: 4,
  },
  systemBubble: { backgroundColor: lightColors.semantic.obsidian, borderRadius: 8 },
  messageText: { fontSize: 15, lineHeight: 20 },
  coachText: { color: lightColors.text.inverse },
  userText: { color: lightColors.text.inverse },
  systemText: {
    color: lightColors.text.muted,
    fontSize: 12,
    textAlign: 'center',
  },
  actionButton: {
    marginTop: 12,
    backgroundColor: lightColors.semantic.primary,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  actionButtonText: {
    color: lightColors.text.inverse,
    fontSize: 13,
    fontWeight: '600',
  },
  typingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingHorizontal: 16,
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: lightColors.semantic.obsidian,
    padding: 12,
    borderRadius: 16,
    borderBottomLeftRadius: 4,
    gap: 8,
  },
  typingText: { fontSize: 13, color: lightColors.text.muted },
  errorBanner: {
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 12,
    backgroundColor: lightColors.semantic.danger,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  errorText: { color: lightColors.text.inverse, fontSize: 13, flex: 1 },
  errorDismiss: {
    color: lightColors.text.inverse,
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 12,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: 12,
    backgroundColor: lightColors.semantic.obsidian,
    borderTopWidth: 1,
    borderTopColor: lightColors.semantic.obsidian,
  },
  input: {
    flex: 1,
    backgroundColor: lightColors.semantic.obsidian,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    paddingTop: 10,
    color: lightColors.text.inverse,
    fontSize: 15,
    maxHeight: 100,
    marginRight: 8,
  },
  sendButton: {
    backgroundColor: lightColors.semantic.primary,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
  },
  sendButtonDisabled: { backgroundColor: lightColors.text.muted },
  sendButtonText: {
    color: lightColors.text.inverse,
    fontSize: 14,
    fontWeight: '600',
  },
});
