import { createSheet } from "@/shared/ui/create-sheet";
export const styles = createSheet({
  screen: { flex: 1 },
  centeredScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  scrollContent: { gap: 20 },
  fullStepSection: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  fullWidth: { alignSelf: "stretch" },
  centerText: { textAlign: "center" },
  eyebrow: {
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  title: { fontSize: 32, fontWeight: "800", lineHeight: 38 },
  section: { gap: 16 },
  stepTitle: { fontSize: 24, fontWeight: "700", lineHeight: 30 },
  stepSubtitle: { fontSize: 15, lineHeight: 22 },
  choiceGrid: { gap: 12 },
  choiceCard: { borderWidth: 1.5, borderRadius: 20, padding: 16, gap: 8 },
  choiceTitle: { fontSize: 17, fontWeight: "700" },
  choiceDescription: { fontSize: 14, lineHeight: 20 },
  presetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  presetPill: { fontSize: 13, fontWeight: "700" },
  squadHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    alignItems: "center",
  },
  metaPill: { fontSize: 12, fontWeight: "600" },
  skipLink: { alignSelf: "flex-start", paddingVertical: 4 },
  skipText: { fontSize: 14, fontWeight: "600" },
  identityCard: { borderWidth: 1, gap: 18 },
  identityEyebrow: {
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  identityBlock: { gap: 4 },
  identityLabel: {
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  identityValue: { fontSize: 20, fontWeight: "700", lineHeight: 24 },
  identityBody: { fontSize: 14, lineHeight: 20 },
  statPanel: { borderWidth: 1, borderRadius: 18, gap: 10 },
  heroStat: { fontSize: 18, fontWeight: "800", lineHeight: 24 },
  heroStatCaption: { fontSize: 13, fontWeight: "600" },
  progressBar: { marginTop: 4 },
  progressCaption: { fontSize: 12, fontWeight: "600" },
  lockInSection: {
    minHeight: 480,
    borderWidth: 1,
    borderRadius: 28,
    justifyContent: "center",
    gap: 18,
  },
  lockInEyebrow: {
    fontSize: 14,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  lockInTitle: { fontSize: 30, fontWeight: "800", lineHeight: 36 },
  lockInBody: { fontSize: 16, lineHeight: 24 },
  launchCard: { borderWidth: 1, borderRadius: 24, gap: 8 },
  launchGradientCard: { alignSelf: "stretch", gap: 10 },
  launchFallbackCard: { alignSelf: "stretch", borderWidth: 1, gap: 10 },
  launchIcon: { fontSize: 28 },
  launchLabel: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  launchHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  launchTitle: { flex: 1, fontSize: 22, fontWeight: "700", lineHeight: 28 },
  launchDuration: { fontSize: 15, fontWeight: "800" },
  launchDurationLight: { fontSize: 15, fontWeight: "800" },
  launchDescription: { fontSize: 14, lineHeight: 21 },
  progressHint: { fontSize: 12, fontWeight: "600", textAlign: "center" },
  celebrationEmoji: { fontSize: 56, textAlign: "center" },
  celebrationStats: { alignSelf: "stretch", gap: 12 },
  celebrationStatCard: { borderWidth: 1, borderRadius: 18 },
  celebrationStatText: { fontSize: 18, fontWeight: "700", textAlign: "center" },
  lockInActions: { gap: 12 },
  footer: {
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  loader: { marginTop: 32 },
});
