/**
 * Accessibility & Localization
 *
 * Phase 12.5 — WCAG compliance, screen reader support, i18n, RTL
 */

import { I18nManager, AccessibilityInfo, Platform } from 'react-native';

// ============================================================================
// Localization Structure
// ============================================================================
const TRANSLATIONS: Record<SupportedLanguage, TranslationKeys> = {
  en: {
    'app.name': 'VEX',
    'app.tagline': 'Defeat your distractions',
    'button.ok': 'OK',
    'button.cancel': 'Cancel',
    'button.confirm': 'Confirm',
    'button.back': 'Back',
    'button.next': 'Next',
    'button.skip': 'Skip',
    'button.save': 'Save',
    'button.delete': 'Delete',
    'button.edit': 'Edit',
    'nav.home': 'Home',
    'nav.sessions': 'Sessions',
    'nav.bosses': 'Bosses',
    'nav.squad': 'Squad',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.shop': 'Shop',
    'session.start': 'Start Session',
    'session.end': 'End Session',
    'session.pause': 'Pause',
    'session.resume': 'Resume',
    'session.duration': 'Duration',
    'session.quality': 'Quality',
    'session.streak': 'Day Streak',
    'session.focus_time': 'Focus Time',
    'boss.spawned': 'Boss Spawned!',
    'boss.defeated': 'Boss Defeated!',
    'boss.damage_dealt': 'Damage Dealt',
    'boss.time_remaining': 'Time Remaining',
    'boss.escape_warning': 'Boss escaping soon!',
    'squad.war_active': 'War Active',
    'squad.score': 'Score',
    'squad.members': 'Members',
    'squad.invite': 'Invite',
    'squad.leave': 'Leave Squad',
    'onboarding.welcome': 'Welcome to VEX',
    'onboarding.focus_mission': 'Your mission: focus deeply',
    'onboarding.defeat_distractions': 'Defeat distractions with every session',
    'onboarding.join_squad': 'Join a squad for support',
    'onboarding.setup_complete': 'Setup Complete!',
    'error.generic': 'Something went wrong',
    'error.network': 'Network error. Please check your connection.',
    'error.retry': 'Try again',
    'error.offline': 'You are offline',
    'a11y.loading': 'Loading',
    'a11y.success': 'Success',
    'a11y.error': 'Error',
    'a11y.button_hint': 'Double tap to activate',
    'a11y.progress': 'Progress',
  },

  es: {
    'app.name': 'VEX',
    'app.tagline': 'Derrota tus distracciones',
    'button.ok': 'OK',
    'button.cancel': 'Cancelar',
    'button.confirm': 'Confirmar',
    'button.back': 'Atrás',
    'button.next': 'Siguiente',
    'button.skip': 'Omitir',
    'button.save': 'Guardar',
    'button.delete': 'Eliminar',
    'button.edit': 'Editar',
    'nav.home': 'Inicio',
    'nav.sessions': 'Sesiones',
    'nav.bosses': 'Jefes',
    'nav.squad': 'Escuadra',
    'nav.profile': 'Perfil',
    'nav.settings': 'Ajustes',
    'nav.shop': 'Tienda',
    'session.start': 'Iniciar Sesión',
    'session.end': 'Terminar Sesión',
    'session.pause': 'Pausar',
    'session.resume': 'Continuar',
    'session.duration': 'Duración',
    'session.quality': 'Calidad',
    'session.streak': 'Racha Diaria',
    'session.focus_time': 'Tiempo de Enfoque',
    'boss.spawned': '¡Jefe Apareció!',
    'boss.defeated': '¡Jefe Derrotado!',
    'boss.damage_dealt': 'Daño Causado',
    'boss.time_remaining': 'Tiempo Restante',
    'boss.escape_warning': '¡El jefe escapará pronto!',
    'squad.war_active': 'Guerra Activa',
    'squad.score': 'Puntuación',
    'squad.members': 'Miembros',
    'squad.invite': 'Invitar',
    'squad.leave': 'Abandonar Escuadra',
    'onboarding.welcome': 'Bienvenido a VEX',
    'onboarding.focus_mission': 'Tu misión: enfoque profundo',
    'onboarding.defeat_distractions': 'Derrota distracciones con cada sesión',
    'onboarding.join_squad': 'Únete a una escuadra',
    'onboarding.setup_complete': '¡Configuración Completa!',
    'error.generic': 'Algo salió mal',
    'error.network': 'Error de red. Verifica tu conexión.',
    'error.retry': 'Intentar de nuevo',
    'error.offline': 'Estás sin conexión',
    'a11y.loading': 'Cargando',
    'a11y.success': 'Éxito',
    'a11y.error': 'Error',
    'a11y.button_hint': 'Toca dos veces para activar',
    'a11y.progress': 'Progreso',
  },

  // Additional languages would be fully translated
  de: {
    'app.name': 'VEX',
    'app.tagline': 'Besiege deine Ablenkungen',
    'button.ok': 'OK',
    'button.cancel': 'Abbrechen',
    'button.confirm': 'Bestätigen',
    'button.back': 'Zurück',
    'button.next': 'Weiter',
    'button.skip': 'Überspringen',
    'button.save': 'Speichern',
    'button.delete': 'Löschen',
    'button.edit': 'Bearbeiten',
    'nav.home': 'Startseite',
    'nav.sessions': 'Sitzungen',
    'nav.bosses': 'Bosse',
    'nav.squad': 'Team',
    'nav.profile': 'Profil',
    'nav.settings': 'Einstellungen',
    'nav.shop': 'Shop',
    'session.start': 'Sitzung Starten',
    'session.end': 'Sitzung Beenden',
    'session.pause': 'Pause',
    'session.resume': 'Fortsetzen',
    'session.duration': 'Dauer',
    'session.quality': 'Qualität',
    'session.streak': 'Tages-Serie',
    'session.focus_time': 'Fokus-Zeit',
    'boss.spawned': 'Boss Erschienen!',
    'boss.defeated': 'Boss Besiegt!',
    'boss.damage_dealt': 'Schaden',
    'boss.time_remaining': 'Verbleibende Zeit',
    'boss.escape_warning': 'Boss flieht bald!',
    'squad.war_active': 'Krieg Aktiv',
    'squad.score': 'Punktzahl',
    'squad.members': 'Mitglieder',
    'squad.invite': 'Einladen',
    'squad.leave': 'Team Verlassen',
    'onboarding.welcome': 'Willkommen bei VEX',
    'onboarding.focus_mission': 'Deine Mission: tiefes Fokus',
    'onboarding.defeat_distractions': 'Besiege Ablenkungen mit jeder Sitzung',
    'onboarding.join_squad': 'Trete einem Team bei',
    'onboarding.setup_complete': 'Einrichtung Abgeschlossen!',
    'error.generic': 'Etwas ist schief gelaufen',
    'error.network': 'Netzwerkfehler. Bitte Verbindung prüfen.',
    'error.retry': 'Erneut versuchen',
    'error.offline': 'Du bist offline',
    'a11y.loading': 'Laden',
    'a11y.success': 'Erfolg',
    'a11y.error': 'Fehler',
    'a11y.button_hint': 'Zweimal tippen zum Aktivieren',
    'a11y.progress': 'Fortschritt',
  },

  fr: {
    'app.name': 'VEX',
    'app.tagline': 'Vaincs tes distractions',
    'button.ok': 'OK',
    'button.cancel': 'Annuler',
    'button.confirm': 'Confirmer',
    'button.back': 'Retour',
    'button.next': 'Suivant',
    'button.skip': 'Passer',
    'button.save': 'Sauvegarder',
    'button.delete': 'Supprimer',
    'button.edit': 'Modifier',
    'nav.home': 'Accueil',
    'nav.sessions': 'Séances',
    'nav.bosses': 'Boss',
    'nav.squad': 'Équipe',
    'nav.profile': 'Profil',
    'nav.settings': 'Paramètres',
    'nav.shop': 'Boutique',
    'session.start': 'Démarrer',
    'session.end': 'Terminer',
    'session.pause': 'Pause',
    'session.resume': 'Reprendre',
    'session.duration': 'Durée',
    'session.quality': 'Qualité',
    'session.streak': 'Série de Jours',
    'session.focus_time': 'Temps de Concentration',
    'boss.spawned': 'Boss Apparu!',
    'boss.defeated': 'Boss Vaincu!',
    'boss.damage_dealt': 'Dégâts Infligés',
    'boss.time_remaining': 'Temps Restant',
    'boss.escape_warning': 'Le boss s\'échappe bientôt!',
    'squad.war_active': 'Guerre Active',
    'squad.score': 'Score',
    'squad.members': 'Membres',
    'squad.invite': 'Inviter',
    'squad.leave': 'Quitter l\'Équipe',
    'onboarding.welcome': 'Bienvenue sur VEX',
    'onboarding.focus_mission': 'Ta mission: concentration profonde',
    'onboarding.defeat_distractions': 'Vaincs les distractions',
    'onboarding.join_squad': 'Rejoins une équipe',
    'onboarding.setup_complete': 'Configuration Terminée!',
    'error.generic': 'Quelque chose s\'est mal passé',
    'error.network': 'Erreur réseau. Vérifie ta connexion.',
    'error.retry': 'Réessayer',
    'error.offline': 'Tu es hors ligne',
    'a11y.loading': 'Chargement',
    'a11y.success': 'Succès',
    'a11y.error': 'Erreur',
    'a11y.button_hint': 'Appuie deux fois pour activer',
    'a11y.progress': 'Progrès',
  },

  ja: {
    'app.name': 'VEX',
    'app.tagline': '気晴らしを倒せ',
    'button.ok': 'OK',
    'button.cancel': 'キャンセル',
    'button.confirm': '確認',
    'button.back': '戻る',
    'button.next': '次へ',
    'button.skip': 'スキップ',
    'button.save': '保存',
    'button.delete': '削除',
    'button.edit': '編集',
    'nav.home': 'ホーム',
    'nav.sessions': 'セッション',
    'nav.bosses': 'ボス',
    'nav.squad': 'チーム',
    'nav.profile': 'プロフィール',
    'nav.settings': '設定',
    'nav.shop': 'ショップ',
    'session.start': '開始',
    'session.end': '終了',
    'session.pause': '一時停止',
    'session.resume': '再開',
    'session.duration': '時間',
    'session.quality': '品質',
    'session.streak': '連続日数',
    'session.focus_time': '集中時間',
    'boss.spawned': 'ボス出現!',
    'boss.defeated': 'ボス撃破!',
    'boss.damage_dealt': '与ダメージ',
    'boss.time_remaining': '残り時間',
    'boss.escape_warning': 'ボスが逃げるぞ!',
    'squad.war_active': '戦争中',
    'squad.score': 'スコア',
    'squad.members': 'メンバー',
    'squad.invite': '招待',
    'squad.leave': 'チーム脱退',
    'onboarding.welcome': 'VEXへようこそ',
    'onboarding.focus_mission': 'ミッション: 深い集中',
    'onboarding.defeat_distractions': 'セッションで気晴らしを倒せ',
    'onboarding.join_squad': 'チームに参加しよう',
    'onboarding.setup_complete': 'セットアップ完了!',
    'error.generic': 'エラーが発生しました',
    'error.network': 'ネットワークエラー。接続を確認してください。',
    'error.retry': '再試行',
    'error.offline': 'オフラインです',
    'a11y.loading': '読み込み中',
    'a11y.success': '成功',
    'a11y.error': 'エラー',
    'a11y.button_hint': 'ダブルタップで有効化',
    'a11y.progress': '進捗',
  },

  ar: {
    'app.name': 'VEX',
    'app.tagline': 'تغلب على إلهائك',
    'button.ok': 'موافق',
    'button.cancel': 'إلغاء',
    'button.confirm': 'تأكيد',
    'button.back': 'رجوع',
    'button.next': 'التالي',
    'button.skip': 'تخطي',
    'button.save': 'حفظ',
    'button.delete': 'حذف',
    'button.edit': 'تحرير',
    'nav.home': 'الرئيسية',
    'nav.sessions': 'الجلسات',
    'nav.bosses': 'الزعماء',
    'nav.squad': 'الفريق',
    'nav.profile': 'الملف',
    'nav.settings': 'الإعدادات',
    'nav.shop': 'المتجر',
    'session.start': 'بدء الجلسة',
    'session.end': 'إنهاء الجلسة',
    'session.pause': 'إيقاف مؤقت',
    'session.resume': 'استئناف',
    'session.duration': 'المدة',
    'session.quality': 'الجودة',
    'session.streak': 'الأيام المتتالية',
    'session.focus_time': 'وقت التركيز',
    'boss.spawned': 'ظهر الزعيم!',
    'boss.defeated': 'هُزم الزعيم!',
    'boss.damage_dealt': 'الضرر المُسبب',
    'boss.time_remaining': 'الوقت المتبقي',
    'boss.escape_warning': 'الزعيم على وشك الهروب!',
    'squad.war_active': 'الحرب نشطة',
    'squad.score': 'النقاط',
    'squad.members': 'الأعضاء',
    'squad.invite': 'دعوة',
    'squad.leave': 'مغادرة الفريق',
    'onboarding.welcome': 'مرحباً بك في VEX',
    'onboarding.focus_mission': 'مهمتك: تركيز عميق',
    'onboarding.defeat_distractions': 'تغلب على الإلهاءات',
    'onboarding.join_squad': 'انضم إلى فريق',
    'onboarding.setup_complete': 'اكتمل الإعداد!',
    'error.generic': 'حدث خطأ ما',
    'error.network': 'خطأ في الشبكة. يرجى التحقق من الاتصال.',
    'error.retry': 'إعادة المحاولة',
    'error.offline': 'أنت غير متصل',
    'a11y.loading': 'جاري التحميل',
    'a11y.success': 'نجاح',
    'a11y.error': 'خطأ',
    'a11y.button_hint': 'انقر مرتين للتفعيل',
    'a11y.progress': 'التقدم',
  },

  he: {
    'app.name': 'VEX',
    'app.tagline': 'הבס את ההסחות דעת',
    'button.ok': 'אישור',
    'button.cancel': 'ביטול',
    'button.confirm': 'אשר',
    'button.back': 'חזור',
    'button.next': 'הבא',
    'button.skip': 'דלג',
    'button.save': 'שמור',
    'button.delete': 'מחק',
    'button.edit': 'ערוך',
    'nav.home': 'בית',
    'nav.sessions': 'מפגשים',
    'nav.bosses': 'בוסים',
    'nav.squad': 'צוות',
    'nav.profile': 'פרופיל',
    'nav.settings': 'הגדרות',
    'nav.shop': 'חנות',
    'session.start': 'התחל מפגש',
    'session.end': 'סיים מפגש',
    'session.pause': 'השהה',
    'session.resume': 'המשך',
    'session.duration': 'משך',
    'session.quality': 'איכות',
    'session.streak': 'רצף ימים',
    'session.focus_time': 'זמן ריכוז',
    'boss.spawned': 'בוס הופיע!',
    'boss.defeated': 'בוס הובס!',
    'boss.damage_dealt': 'נזק שנגרם',
    'boss.time_remaining': 'זמן נותר',
    'boss.escape_warning': 'הבוס עומד לברוח!',
    'squad.war_active': 'מלחמה פעילה',
    'squad.score': 'ניקוד',
    'squad.members': 'חברים',
    'squad.invite': 'הזמן',
    'squad.leave': 'עזוב צוות',
    'onboarding.welcome': 'ברוך הבא ל-VEX',
    'onboarding.focus_mission': 'המשימה שלך: ריכוז עמוק',
    'onboarding.defeat_distractions': 'הבס הסחות דעת',
    'onboarding.join_squad': 'הצטרף לצוות',
    'onboarding.setup_complete': 'ההגדרה הושלמה!',
    'error.generic': 'משהו השתבש',
    'error.network': 'שגיאת רשת. בדוק את החיבור.',
    'error.retry': 'נסה שוב',
    'error.offline': 'אתה לא מחובר',
    'a11y.loading': 'טוען',
    'a11y.success': 'הצלחה',
    'a11y.error': 'שגיאה',
    'a11y.button_hint': 'הקש פעמיים להפעלה',
    'a11y.progress': 'התקדמות',
  },
};

// ============================================================================
// i18n System
// ============================================================================

let currentLanguage: SupportedLanguage = 'en';
// ============================================================================
// Accessibility Helpers
// ============================================================================
// ============================================================================
// RTL Support
// ============================================================================
// ============================================================================
// Dynamic Type Support
// ============================================================================
// ============================================================================
// WCAG Compliance Helpers
// ============================================================================

function getLuminance(color: string): number {
  // Simplified luminance calculation
  const hex = color.replace('#', '');
  const r = parseInt(hex.substr(0, 2), 16) / 255;
  const g = parseInt(hex.substr(2, 2), 16) / 255;
  const b = parseInt(hex.substr(4, 2), 16) / 255;

  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

// ============================================================================
// Exports
// ============================================================================

export { TRANSLATIONS };
export * from "./index.types";
export * from "./index.part1";
