import type { FeatureKey } from '../../features/liveops-config';

export const HOME_FEATURE_COPY: Record<FeatureKey, { icon: string; title: string; why: string }> = {
  achievements: { icon: '🏅', title: 'Achievements', why: 'Collect milestones that celebrate your journey.' },
  advanced_settings: { icon: '⚙️', title: 'Settings', why: 'Fine-tune your VEX experience.' },
  ai_coach_advanced: { icon: '✨', title: 'Advanced Coach', why: 'Deeper coaching helps the app feel bespoke instead of generic.' },
  ai_coach_basic: { icon: '🧠', title: 'Coach', why: 'Your coach becomes personal once it sees real behavior.' },
  battle_pass: { icon: '🎟️', title: 'Battle Pass', why: 'Seasonal progression makes repeat effort feel premium.' },
  boss_bounties: { icon: '🎯', title: 'Bounties', why: 'Boost your rewards by placing bounties on bosses.' },
  boss_tab: { icon: '🐉', title: 'Boss', why: 'Boss fights turn your focus sessions into high-stakes momentum.' },
  challenges: { icon: '🎯', title: 'Challenges', why: 'Daily and weekly goals to keep you engaged.' },
  companion_detail: { icon: '🤖', title: 'Companion', why: 'Your AI companion for focus and study.' },
  content_study: { icon: '📚', title: 'Study', why: 'Content study expands VEX from habit builder into a serious work tool.' },
  content_study_advanced: { icon: '📖', title: 'Advanced Study', why: 'Deep learning tools for complex material.' },
  economy_advanced: { icon: '💎', title: 'Advanced Rewards', why: 'The deeper economy shows up once the basic loop already feels clean.' },
  economy_basic: { icon: '💰', title: 'Rewards', why: 'Simple rewards make each win feel tangible right away.' },
  focus_session: { icon: '⏱️', title: 'Focus', why: 'The core focus loop keeps getting smoother as you build consistency.' },
  focus_tab: { icon: '🎯', title: 'Focus', why: 'The heart of your focus practice.' },
  gems_prominent: { icon: '💎', title: 'Premium Currency', why: 'Premium rewards for your dedication.' },
  home_tab: { icon: '🏠', title: 'Home', why: 'Your home base for focus and progress.' },
  inventory: { icon: '🎒', title: 'Inventory', why: 'Your collection of earned rewards and items.' },
  premium_paywall: { icon: '⭐', title: 'Premium', why: 'Unlock the full VEX experience.' },
  profile_tab: { icon: '👤', title: 'Profile', why: 'Your personal hub for stats and settings.' },
  progress_view: { icon: '📈', title: 'Progress', why: 'Progress turns each session into visible momentum.' },
  quiz_review_mode: { icon: '❓', title: 'Quiz Mode', why: 'Test your knowledge and reinforce learning.' },
  rankings: { icon: '🏆', title: 'Rankings', why: 'Rankings sharpen ambition once you have real data behind you.' },
  rivals: { icon: '🏁', title: 'Rivals', why: 'Friendly competition to push your limits.' },
  seasonal_features: { icon: '🌟', title: 'Seasonal', why: 'Seasonal moments work best once VEX already feels like your place.' },
  shop: { icon: '🛍️', title: 'Shop', why: 'The shop matters more once rewards already feel earned.' },
  social_tab: { icon: '⚔️', title: 'Arena', why: 'The social layer keeps you accountable when your habit starts to matter.' },
  squads: { icon: '🛡️', title: 'Squads', why: 'Squads make showing up feel shared, not solo.' },
  streak_insurance: { icon: '🛡️', title: 'Streak Insurance', why: 'Protect your hard-earned streaks.' },
  wagers: { icon: '💰', title: 'Wagers', why: 'Bet on your streak for bigger rewards.' },
};
