import type { SessionPreset } from "../../../session/types";

export interface PresetWithIcon extends SessionPreset {
  icon: string;
}

export type SmartSuggestion = {
  preset: PresetWithIcon;
  description: string;
  confidence: number;
};

export const PRESET_CATEGORIES = [
  { key: "quick", label: "Quick", icon: "zap" },
  { key: "standard", label: "Standard", icon: "target" },
  { key: "deep", label: "Deep", icon: "brain" },
  { key: "custom", label: "Custom", icon: "sliders" },
] as const;

export const PRESETS: PresetWithIcon[] = [
  {
    id: "quick",
    name: "Quick Focus",
    duration: 15 * 60,
    category: "quick",
    icon: "zap",
    intervals: 1,
    breakDuration: 300,
    longBreakDuration: 900,
    longBreakInterval: 4,
    isDefault: false,
    tags: [],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: false,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "pomodoro",
    name: "Pomodoro",
    duration: 25 * 60,
    category: "standard",
    icon: "timer",
    intervals: 4,
    breakDuration: 300,
    longBreakDuration: 900,
    longBreakInterval: 4,
    isDefault: true,
    tags: [],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: false,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "deep",
    name: "Deep Work",
    duration: 60 * 60,
    category: "deep",
    icon: "brain",
    intervals: 1,
    breakDuration: 600,
    longBreakDuration: 1800,
    longBreakInterval: 2,
    isDefault: false,
    tags: [],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: true,
    strictMode: true,
    autoStartBreaks: false,
    autoStartNextInterval: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "study",
    name: "Study Session",
    duration: 45 * 60,
    category: "deep",
    icon: "book",
    intervals: 2,
    breakDuration: 300,
    longBreakDuration: 900,
    longBreakInterval: 4,
    isDefault: false,
    tags: [],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: false,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "creative",
    name: "Creative Flow",
    duration: 90 * 60,
    category: "deep",
    icon: "palette",
    intervals: 1,
    breakDuration: 0,
    longBreakDuration: 0,
    longBreakInterval: 1,
    isDefault: false,
    tags: [],
    soundEnabled: false,
    vibrationEnabled: false,
    dndEnabled: true,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: "custom",
    name: "Custom",
    duration: 30 * 60,
    category: "custom",
    icon: "sliders",
    intervals: 1,
    breakDuration: 300,
    longBreakDuration: 900,
    longBreakInterval: 4,
    isDefault: false,
    tags: [],
    soundEnabled: true,
    vibrationEnabled: true,
    dndEnabled: false,
    strictMode: false,
    autoStartBreaks: false,
    autoStartNextInterval: false,
    createdAt: 0,
    updatedAt: 0,
  },
];
