import { z } from "zod";
import type { MasteryState } from "../../../features/mastery/types"; import type { SessionPreset } from "../../../session/types";
export interface PresetWithIcon extends SessionPreset { icon: string; }
export type SmartSuggestion = { preset: PresetWithIcon; description: string; confidence: number; };
export const PRESET_CATEGORIES = [ { key: "quick", label: "Quick", icon: "zap" }, { key: "standard", label: "Standard", icon: "target" }, { key: "deep", label: "Deep", icon: "brain" }, { key: "custom", label: "Custom", icon: "sliders" }, ] as const;
export const PRESETS: PresetWithIcon[] = [ { id: "quick", name: "Quick Focus", duration: 15 * 60, category: "quick", icon: "zap", intervals: 1, breakDuration: 300, longBreakDuration: 900, longBreakInterval: 4, isDefault: false, tags: [], soundEnabled: true, vibrationEnabled: true, dndEnabled: false, strictMode: false, autoStartBreaks: false, autoStartNextInterval: false, createdAt: 0, updatedAt: 0, }, { id: "pomodoro", name: "Pomodoro", duration: 25 * 60, category: "standard", icon: "timer", intervals: 4, breakDuration: 300, longBreakDuration: 900, longBreakInterval: 4, isDefault: true, tags: [], soundEnabled: true, vibrationEnabled: true, dndEnabled: false, strictMode: false, autoStartBreaks: false, autoStartNextInterval: false, createdAt: 0, updatedAt: 0, }, { id: "deep", name: "Deep Work", duration: 60 * 60, category: "deep", icon: "brain", intervals: 1, breakDuration: 600, longBreakDuration: 1800, longBreakInterval: 2, isDefault: false, tags: [], soundEnabled: true, vibrationEnabled: true, dndEnabled: true, strictMode: true, autoStartBreaks: false, autoStartNextInterval: false, createdAt: 0, updatedAt: 0, }, { id: "study", name: "Study Session", duration: 45 * 60, category: "deep", icon: "book", intervals: 2, breakDuration: 300, longBreakDuration: 900, longBreakInterval: 4, isDefault: false, tags: [], soundEnabled: true, vibrationEnabled: true, dndEnabled: false, strictMode: false, autoStartBreaks: false, autoStartNextInterval: false, createdAt: 0, updatedAt: 0, }, { id: "creative", name: "Creative Flow", duration: 90 * 60, category: "deep", icon: "palette", intervals: 1, breakDuration: 0, longBreakDuration: 0, longBreakInterval: 1, isDefault: false, tags: [], soundEnabled: false, vibrationEnabled: false, dndEnabled: true, strictMode: false, autoStartBreaks: false, autoStartNextInterval: false, createdAt: 0, updatedAt: 0, }, { id: "custom", name: "Custom", duration: 30 * 60, category: "custom", icon: "sliders", intervals: 1, breakDuration: 300, longBreakDuration: 900, longBreakInterval: 4, isDefault: false, tags: [], soundEnabled: true, vibrationEnabled: true, dndEnabled: false, strictMode: false, autoStartBreaks: false, autoStartNextInterval: false, createdAt: 0, updatedAt: 0, }, ];
export const SESSION_DRAFT_MAX_AGE_MS = 60 * 60 * 1000;
export const SessionDraftSchema = z.object({ savedAt: z.number(), presetId: z.string(), selectedCategory: z.string(), customDuration: z.number().int().min(1), selectedThemeId: z.string(), showAdvanced: z.boolean(), goal: z.string().optional(), });
export const MasteryStateSchema = z.object({ userId: z.string().optional(), totalMasteryPoints: z.number().optional(), rank: z.enum(["APPRENTICE", "ADEPT", "EXPERT", "MASTER", "GRANDMASTER"]).optional(), techniques: z.object({ durationMastery: z.number(), purityMastery: z.number(), consistencyMastery: z.number(), comebackMastery: z.number(), bossMastery: z.number(), }), activeChallenges: z.array( z.object({ id: z.string(), technique: z.enum(["durationMastery", "purityMastery", "consistencyMastery", "comebackMastery", "bossMastery"]), title: z.string(), description: z.string(), difficulty: z.enum(["EASY", "MEDIUM", "HARD", "ELITE"]), target: z.number(), current: z.number(), unit: z.string(), masteryPoints: z.number(), status: z.enum(["ACTIVE", "COMPLETED", "CLAIMED"]), completedAt: z.number().nullable(), }), ), unlockedFeatures: z.array(z.string()).optional(), updatedAt: z.number().optional(), });
export function getPresetById(presetId: string): PresetWithIcon { return PRESETS.find((preset) => preset.id === presetId) ?? PRESETS[1]!; }
export function resolveSmartSuggestion(mastery: z.infer<typeof MasteryStateSchema> | null, currentStreak: number): SmartSuggestion | null { if (!mastery) { return null; }
if (mastery.techniques.purityMastery < 5) { return { preset: getPresetById("quick"), description: "Your purity scores suggest shorter sessions build better habits right now", confidence: 0.85, }; }
if (mastery.techniques.durationMastery > 15) { return { preset: getPresetById("deep"), description: "You've consistently finished long sessions and you're ready for deep work", confidence: 0.82, }; }
if (mastery.techniques.consistencyMastery < 5 && currentStreak > 0) { return { preset: getPresetById("pomodoro"), description: "The Pomodoro keeps streaks alive and it's the most consistent preset", confidence: 0.76, }; }
return null; }
export function buildPreviewGradient(previewColor: string): readonly [string, string] {
  return [previewColor, `${previewColor}99`];
}
export function hydrateMasteryState(mastery: z.infer<typeof MasteryStateSchema>, userId: string): MasteryState { return { userId: mastery.userId ?? userId, totalMasteryPoints: mastery.totalMasteryPoints ?? 0, rank: mastery.rank ?? "APPRENTICE", techniques: mastery.techniques, activeChallenges: mastery.activeChallenges, unlockedFeatures: mastery.unlockedFeatures ?? [], updatedAt: mastery.updatedAt ?? Date.now(), }; }
