/**
 * Feature Groups
 *
 * Organization of feature flags into logical groups for admin UI and launch management.
 */

import { FEATURE_FLAGS } from './feature-flags';

export const FEATURE_GROUPS = {
  // Core Launch Features (always enabled)
  core: [
    FEATURE_FLAGS.SESSIONS,
    FEATURE_FLAGS.SESSION_GRADING,
    FEATURE_FLAGS.FOCUS_SCORE,
    FEATURE_FLAGS.DAILY_MISSION,
    FEATURE_FLAGS.COMPANION,
    FEATURE_FLAGS.STREAKS,
    FEATURE_FLAGS.COMEBACK_QUEST,
    FEATURE_FLAGS.BASIC_REWARDS,
    FEATURE_FLAGS.XP_PROGRESSION,
    FEATURE_FLAGS.AI_COACH_BASICS,
    FEATURE_FLAGS.PAYWALL,
    FEATURE_FLAGS.SETTINGS,
  ],
  // Optional Launch Features (enable if stable)
  optional: [
    FEATURE_FLAGS.BASIC_SOLO_BOSS,
    FEATURE_FLAGS.BASIC_CHALLENGES,
    FEATURE_FLAGS.SQUADS_ACCOUNTABILITY,
    FEATURE_FLAGS.MONTHLY_REPORT,
  ],
  // Disabled Features (never show at launch)
  disabled: [
    FEATURE_FLAGS.SOCIAL_FEED,
    FEATURE_FLAGS.DUELS,
    FEATURE_FLAGS.RANKINGS,
    FEATURE_FLAGS.SQUAD_WARS,
    FEATURE_FLAGS.RIVALS,
    FEATURE_FLAGS.TRADING,
    FEATURE_FLAGS.EMERGENCY_GEM_SINKS,
    FEATURE_FLAGS.COMPLEX_CRAFTING,
    FEATURE_FLAGS.AR_EXPERIMENTAL,
  ],
  // Legacy Groups
  ui: [
    FEATURE_FLAGS.DARK_MODE,
    FEATURE_FLAGS.DARK_MODE_TOGGLE,
    FEATURE_FLAGS.CUSTOM_THEMES,
    FEATURE_FLAGS.REDUCED_MOTION,
  ],
  auth: [
    FEATURE_FLAGS.BIOMETRIC_LOGIN,
    FEATURE_FLAGS.SOCIAL_LOGIN,
    FEATURE_FLAGS.TWO_FACTOR_AUTH,
  ],
  social: [
    FEATURE_FLAGS.FRIENDS,
    FEATURE_FLAGS.DIRECT_MESSAGES,
    FEATURE_FLAGS.GROUP_MESSAGES,
  ],
  economy: [
    FEATURE_FLAGS.WALLET,
    FEATURE_FLAGS.TRANSFERS,
    FEATURE_FLAGS.REWARDS,
    FEATURE_FLAGS.MARKETPLACE,
  ],
  experimental: [
    FEATURE_FLAGS.BETA_FEATURES,
    FEATURE_FLAGS.EXPERIMENTAL_UI,
    FEATURE_FLAGS.EARLY_ACCESS,
  ],
} as const;
