import { createSheet } from '@/shared/ui/create-sheet';


export const styles = createSheet({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    padding: 24,
  },
  container: {
    backgroundColor: '#1a1a2e',
    borderRadius: 20,
    padding: 24,
  },
  header: { alignItems: 'center', marginBottom: 24 },
  icon: { fontSize: 48, marginBottom: 12 },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
    marginBottom: 8,
  },
  subtitle: { fontSize: 16, color: '#9e9e9e' },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9e9e9e',
    marginBottom: 12,
    textTransform: 'uppercase',
  },
  options: { gap: 12 },
  optionCard: {
    backgroundColor: '#2a2a3e',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#3a3a4e',
  },
  optionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  optionIcon: { fontSize: 24, marginRight: 12 },
  optionInfo: { flex: 1 },
  optionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginBottom: 2,
  },
  optionDescription: { fontSize: 13, color: '#9e9e9e' },
  penaltyBadge: {
    backgroundColor: 'rgba(244,67,54,0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    alignSelf: 'flex-start',
  },
  penaltyText: { fontSize: 12, color: '#f44336' },
  abandonSection: { marginTop: 24, alignItems: 'center' },
  orText: { color: '#666', marginBottom: 12 },
  abandonButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderWidth: 1,
    borderColor: '#e94560',
    borderRadius: 8,
    alignItems: 'center',
  },
  abandonText: {
    color: '#e94560',
    fontSize: 16,
    fontWeight: '600',
  },
  abandonPenalty: {
    fontSize: 12,
    color: '#e9456080',
    marginTop: 4,
  },
  helpText: {
    marginTop: 20,
    fontSize: 13,
    color: '#666',
    textAlign: 'center',
    lineHeight: 18,
  },
});
