

const styles = {
  container: { flex: 1, backgroundColor: '#1a1a2e' },
  content: { padding: 24 },
  header: { alignItems: 'center' as const, marginBottom: 24 },
  title: {
    fontSize: 28,
    fontWeight: '700' as const,
    color: '#fff',
    marginBottom: 8,
  },
  subtitle: { fontSize: 16, color: '#9e9e9e' },
  scoreCircle: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 8,
    alignSelf: 'center' as const,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    marginBottom: 32,
  },
  scoreLetter: { fontSize: 48, fontWeight: '700' as const },
  scoreNumber: {
    fontSize: 32,
    fontWeight: '700' as const,
    color: '#fff',
  },
  scoreLabel: { fontSize: 14, color: '#9e9e9e' },
  rewardsSection: { marginBottom: 24 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: '#fff',
    marginBottom: 12,
  },
  rewardsRow: { flexDirection: 'row' as const, gap: 12 },
  rewardBadge: {
    flex: 1,
    backgroundColor: '#2a2a3e',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center' as const,
  },
  rewardIcon: { fontSize: 24, marginBottom: 4 },
  rewardValue: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: '#ffd700',
  },
  rewardLabel: { fontSize: 12, color: '#9e9e9e' },
  streakBanner: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#ff6b35',
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
  },
  streakEmoji: { fontSize: 24, marginRight: 8 },
  streakText: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: '#fff',
  },
  streakBonus: {
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: 'rgba(255,255,255,0.3)',
    borderRadius: 4,
    color: '#fff',
    fontSize: 12,
    fontWeight: '600' as const,
  },
  bonusesSection: { marginBottom: 24 },
  bonusItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: '#2a2a3e',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  bonusIcon: { fontSize: 20, marginRight: 12 },
  bonusInfo: { flex: 1 },
  bonusType: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: '#fff',
    textTransform: 'capitalize' as const,
  },
  bonusDescription: { fontSize: 12, color: '#9e9e9e' },
  bonusAmount: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: '#4caf50',
  },
  actions: { gap: 12 },
  shareButton: {
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#2a2a3e',
    alignItems: 'center' as const,
  },
  shareButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600' as const,
  },
  newSessionButton: {
    paddingVertical: 16,
    borderRadius: 8,
    backgroundColor: '#4caf50',
    alignItems: 'center' as const,
  },
  newSessionButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700' as const,
  },
  closeButton: {
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center' as const,
  },
  closeButtonText: { color: '#9e9e9e', fontSize: 16 },
};

export default styles;
