export const THRESHOLDS = {
  MAX_TIME_JUMP: 30_000,
  MIN_TICK_INTERVAL: 900,
  MAX_TICK_INTERVAL: 1_100,
  MAX_SESSION_DURATION: 8 * 60 * 60 * 1_000,
  MIN_SESSION_DURATION: 60 * 1_000,
  MAX_COMPLETION_SPEED: 1.5,
  MAX_PAUSE_RATIO: 0.7,
  MIN_FOCUS_VARIANCE: 0.1,
  MAX_TICK_HISTORY: 1_000,
  MAX_TICK_HISTORY_TRIM: 500,
  MIN_TICK_PATTERN_SAMPLE: 10,
  VARIANCE_SAMPLE_THRESHOLD: 30,
  MAX_SUSPENSION_MS: 30_000,
  MIN_PAUSE_TIME_MS: 5_000,
  TIME_ACCOUNTING_TOLERANCE_MS: 1_000,
  INTERVAL_TIME_DISCREPANCY_RATIO: 0.5,
};

export const PURITY_SCORING = {
  BACKGROUND_SWITCH_PENALTY: 8,
  MANUAL_PAUSE_PENALTY: 5,
  SUSPENSION_PENALTY: 15,
  UNINTERRUPTED_BONUS_PER_MINUTE: 2,
  MAX_SCORE: 100,
  MIN_SCORE: 0,
  ELITE_THRESHOLD: 90,
  GOOD_THRESHOLD: 70,
  OKAY_THRESHOLD: 45,
};

export const FLAG_CRITICAL_THRESHOLD = 5;
