import type { TableClassification } from './schema-classification-types';

export const ARCHIVED_TABLES: TableClassification[] = [
  {
    table: 'squads',
    class: 'disabled',
    feature: 'squads',
    notes: 'Archived until separately approved',
  },
  { table: 'squad_members', class: 'disabled', feature: 'squads' },
  { table: 'squad_invites', class: 'disabled', feature: 'squads' },
  { table: 'squad_join_requests', class: 'disabled', feature: 'squads' },
  { table: 'squad_activities', class: 'disabled', feature: 'squads' },
  { table: 'squad_challenges', class: 'disabled', feature: 'squads' },
  { table: 'squad_sessions', class: 'disabled', feature: 'squads' },
  { table: 'squad_session_participants', class: 'disabled', feature: 'squads' },
  { table: 'squad_streaks', class: 'disabled', feature: 'squads' },
  { table: 'squad_synergy', class: 'disabled', feature: 'squads' },
  { table: 'squad_raids', class: 'disabled', feature: 'squads' },
  { table: 'squad_wars', class: 'disabled', feature: 'squads' },
  { table: 'squad_war_damage', class: 'disabled', feature: 'squads' },
  { table: 'raid_participants', class: 'disabled', feature: 'squads' },
  {
    table: 'battle_passes',
    class: 'disabled',
    feature: 'battle_pass',
    notes: 'Archived until separately approved',
  },
  { table: 'battle_pass_tiers', class: 'disabled', feature: 'battle_pass' },
  { table: 'user_battle_pass', class: 'disabled', feature: 'battle_pass' },
  {
    table: 'rivals',
    class: 'disabled',
    feature: 'rivals',
    notes: 'Archived until separately approved',
  },
  {
    table: 'weekly_leaderboard',
    class: 'disabled',
    feature: 'rankings',
    notes: 'Archived until separately approved',
  },
  { table: 'realtime_duels', class: 'disabled', feature: 'rivals' },
  {
    table: 'friends',
    class: 'disabled',
    feature: 'social_tab',
    notes: 'Archived until separately approved',
  },
  { table: 'friend_requests', class: 'disabled', feature: 'social_tab' },
  { table: 'activity_feed', class: 'disabled', feature: 'social_tab' },
  { table: 'feed_likes', class: 'disabled', feature: 'social_tab' },
  { table: 'feed_reactions', class: 'disabled', feature: 'social_tab' },
  { table: 'messages', class: 'disabled', feature: 'social_tab' },
  { table: 'conversations', class: 'disabled', feature: 'social_tab' },
  { table: 'circle_activities', class: 'disabled', feature: 'social_tab' },
  { table: 'circle_invites', class: 'disabled', feature: 'social_tab' },
  { table: 'circle_members', class: 'disabled', feature: 'social_tab' },
  { table: 'circle_weekly_checks', class: 'disabled', feature: 'social_tab' },
  { table: 'study_circles', class: 'disabled', feature: 'social_tab' },
  { table: 'study_buddies', class: 'disabled', feature: 'social_tab' },
  { table: 'study_buddy_check_ins', class: 'disabled', feature: 'social_tab' },
  {
    table: 'study_buddy_encouragements',
    class: 'disabled',
    feature: 'social_tab',
  },
  {
    table: 'study_buddy_shared_goals',
    class: 'disabled',
    feature: 'social_tab',
  },
  { table: 'trading_listings', class: 'disabled', feature: 'inventory' },
  { table: 'victory_cards', class: 'disabled', feature: 'squads' },
  { table: 'synergy_activities', class: 'disabled', feature: 'squads' },
  { table: 'refund_requests', class: 'disabled', feature: 'shop' },
  { table: 'purchase_attempts', class: 'disabled', feature: 'shop' },
  { table: 'admin_users', class: 'internal' },
  { table: 'aggregated_stats', class: 'internal' },
  { table: 'export_jobs', class: 'internal' },
  { table: 'dashboard_layouts', class: 'internal' },
  { table: 'dashboard_widgets', class: 'internal' },
  { table: 'referrals', class: 'deprecated', notes: 'Referral system removed' },
  {
    table: 'shop',
    class: 'disabled',
    feature: 'shop',
    notes: 'Archived until separately approved',
  },
];
