import type { TableClassification } from "./schema-classification-types";

export const CORE_TABLES: TableClassification[] = [
  { table: "sessions", class: "core" },
  { table: "user_sessions", class: "core" },
  { table: "session_completion_ledgers", class: "core" },
  { table: "session_ledgers", class: "core" },
  { table: "streaks", class: "core" },
  { table: "user_streaks", class: "core" },
  { table: "progression", class: "core" },
  { table: "xp_history", class: "core" },
  { table: "users", class: "core" },
  { table: "focus_scores", class: "core" },
  { table: "focus_score_current", class: "core" },
  { table: "focus_score_history", class: "core" },
  { table: "personal_bests", class: "core" },
  { table: "session_recommendations", class: "core" },
  { table: "coach_messages", class: "core", feature: "ai_coach_basic" },
  { table: "coach_states", class: "core", feature: "ai_coach_basic" },
  { table: "notifications", class: "core" },
  { table: "notifications_sent", class: "core" },
  { table: "user_notification_settings", class: "core" },
  { table: "push_tokens", class: "core" },
  { table: "user_push_tokens", class: "core" },
  { table: "analytics_events", class: "core" },
  { table: "analytics_preferences", class: "core" },
  { table: "feature_flags", class: "core" },
  { table: "liveops_config", class: "core" },
  { table: "difficulty_preferences", class: "core" },
  { table: "difficulty_profiles", class: "core" },
  { table: "focus_contracts", class: "core" },
  { table: "reminder_plans", class: "core" },
  { table: "first_week_progress", class: "core" },
  { table: "focus_identity_profiles", class: "core" },
  { table: "focus_monthly_reports", class: "core" },
  { table: "session_stories", class: "core" },
];
