export type SchemaClass = 'core' | 'progressive' | 'disabled' | 'internal' | 'deprecated';

export interface TableClassification {
  table: string;
  class: SchemaClass;
  feature?: string;
  notes?: string;
}

export const SCHEMA_CLASSIFICATION_DATA: TableClassification[] = [
  { table: 'sessions', class: 'core' },
  { table: 'user_sessions', class: 'core' },
  { table: 'session_completion_ledgers', class: 'core' },
  { table: 'session_ledgers', class: 'core' },
  { table: 'streaks', class: 'core' },
  { table: 'user_streaks', class: 'core' },
  { table: 'progression', class: 'core' },
  { table: 'xp_history', class: 'core' },
  { table: 'users', class: 'core' },
  { table: 'focus_scores', class: 'core' },
  { table: 'focus_score_current', class: 'core' },
  { table: 'focus_score_history', class: 'core' },
  { table: 'personal_bests', class: 'core' },
  { table: 'session_recommendations', class: 'core' },
  { table: 'coach_messages', class: 'core', feature: 'ai_coach_basic' },
  { table: 'coach_states', class: 'core', feature: 'ai_coach_basic' },
  { table: 'notifications', class: 'core' },
  { table: 'notifications_sent', class: 'core' },
  { table: 'user_notification_settings', class: 'core' },
  { table: 'push_tokens', class: 'core' },
  { table: 'user_push_tokens', class: 'core' },
  { table: 'analytics_events', class: 'core' },
  { table: 'analytics_preferences', class: 'core' },
  { table: 'feature_flags', class: 'core' },
  { table: 'liveops_config', class: 'core' },
  { table: 'difficulty_preferences', class: 'core' },
  { table: 'difficulty_profiles', class: 'core' },
  { table: 'focus_contracts', class: 'core' },
  { table: 'reminder_plans', class: 'core' },
  { table: 'first_week_progress', class: 'core' },
  { table: 'focus_identity_profiles', class: 'core' },
  { table: 'focus_monthly_reports', class: 'core' },
  { table: 'session_stories', class: 'core' },
  { table: 'companion_memories', class: 'progressive', feature: 'companion_detail' },
  { table: 'challenges', class: 'progressive', feature: 'challenges' },
  { table: 'challenge_templates', class: 'progressive', feature: 'challenges' },
  { table: 'challenge_rerolls', class: 'progressive', feature: 'challenges' },
  { table: 'user_challenges', class: 'progressive', feature: 'challenges' },
  { table: 'wallets', class: 'progressive', feature: 'economy_basic' },
  { table: 'unified_wallets', class: 'progressive', feature: 'economy_basic' },
  { table: 'transactions', class: 'progressive', feature: 'economy_basic' },
  { table: 'wallet_transactions', class: 'progressive', feature: 'economy_basic' },
  { table: 'rewards', class: 'progressive', feature: 'economy_basic' },
  { table: 'reward_ledger', class: 'progressive', feature: 'economy_basic' },
  { table: 'reward_deliveries', class: 'progressive', feature: 'economy_basic' },
  { table: 'chests', class: 'progressive', feature: 'economy_basic' },
  { table: 'daily_reward_claims', class: 'progressive', feature: 'economy_basic' },
  { table: 'user_daily_rewards', class: 'progressive', feature: 'economy_basic' },
  { table: 'user_achievements', class: 'progressive', feature: 'achievements' },
  { table: 'boss_encounters', class: 'progressive', feature: 'boss_tab' },
  { table: 'boss_templates', class: 'progressive', feature: 'boss_tab' },
  { table: 'boss_cooldowns', class: 'progressive', feature: 'boss_tab' },
  { table: 'boss_defeat_history', class: 'progressive', feature: 'boss_tab' },
  { table: 'coach_memories', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'coach_personas', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'coach_quests', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'coach_message_templates', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'user_coach_preferences', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'mastery_tracks', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'study_content', class: 'progressive', feature: 'content_study' },
  { table: 'study_generations', class: 'progressive', feature: 'content_study' },
  { table: 'study_packs', class: 'progressive', feature: 'content_study' },
  { table: 'journey_seasons', class: 'progressive', feature: 'seasonal_features' },
  { table: 'journey_progress', class: 'progressive', feature: 'seasonal_features' },
  { table: 'journey_milestones', class: 'progressive', feature: 'seasonal_features' },
  { table: 'seasons', class: 'progressive', feature: 'seasonal_features' },
  { table: 'season_history', class: 'progressive', feature: 'seasonal_features' },
  { table: 'season_journeys', class: 'progressive', feature: 'seasonal_features' },
  { table: 'user_journeys', class: 'progressive', feature: 'seasonal_features' },
  { table: 'user_journey_claims', class: 'progressive', feature: 'seasonal_features' },
  { table: 'user_season_progress', class: 'progressive', feature: 'seasonal_features' },
  { table: 'level_up_history', class: 'progressive', feature: 'economy_basic' },
  { table: 'prestige_states', class: 'progressive', feature: 'economy_basic' },
  { table: 'insights', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'intervention_rules', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'intervention_executions', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'behavior_profiles', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'behavior_signals', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'detected_patterns', class: 'progressive', feature: 'ai_coach_advanced' },
  { table: 'currency_conversions', class: 'progressive', feature: 'economy_advanced' },
  { table: 'item_definitions', class: 'progressive', feature: 'inventory' },
  { table: 'inventory_items', class: 'progressive', feature: 'inventory' },
  { table: 'user_items', class: 'progressive', feature: 'inventory' },
  { table: 'streak_shields', class: 'progressive', feature: 'streak_insurance' },
  { table: 'streak_insurance', class: 'progressive', feature: 'streak_insurance' },
  { table: 'streak_repair_quests', class: 'progressive', feature: 'streak_insurance' },
  { table: 'streak_risk_status', class: 'progressive', feature: 'streak_insurance' },
  { table: 'streak_gambles', class: 'progressive', feature: 'wagers' },
  { table: 'stakes_sessions', class: 'progressive', feature: 'wagers' },
  { table: 'user_stakes_preferences', class: 'progressive', feature: 'wagers' },
  { table: 'comeback_plans', class: 'progressive', feature: 'comeback_quests' },
  { table: 'comeback_quests', class: 'progressive', feature: 'comeback_quests' },
  { table: 'comeback_tokens', class: 'progressive', feature: 'comeback_quests' },
  { table: 'daily_dungeons', class: 'progressive', feature: 'challenges' },
  { table: 'user_dungeon_attempts', class: 'progressive', feature: 'challenges' },
  { table: 'mystery_multipliers', class: 'progressive', feature: 'economy_basic' },
  { table: 'drop_tables', class: 'progressive', feature: 'economy_basic' },
  { table: 'limited_offers', class: 'progressive', feature: 'shop' },
  { table: 'user_offer_claims', class: 'progressive', feature: 'shop' },
  { table: 'quick_use_slots', class: 'progressive', feature: 'inventory' },
  { table: 'squads', class: 'disabled', feature: 'squads', notes: 'Archived until separately approved' },
  { table: 'squad_members', class: 'disabled', feature: 'squads' },
  { table: 'squad_invites', class: 'disabled', feature: 'squads' },
  { table: 'squad_join_requests', class: 'disabled', feature: 'squads' },
  { table: 'squad_activities', class: 'disabled', feature: 'squads' },
  { table: 'squad_challenges', class: 'disabled', feature: 'squads' },
  { table: 'squad_sessions', class: 'disabled', feature: 'squads' },
  { table: 'squad_session_participants', class: 'disabled', feature: 'squads' },
  { table: 'squad_streaks', class: 'disabled', feature: 'squads' },
  { table: 'squad_synergy', class: 'disabled', feature: 'squads' },
  { table: 'squad_raids', class: 'disabled', feature: 'squads' },
  { table: 'squad_wars', class: 'disabled', feature: 'squads' },
  { table: 'squad_war_damage', class: 'disabled', feature: 'squads' },
  { table: 'raid_participants', class: 'disabled', feature: 'squads' },
  { table: 'battle_passes', class: 'disabled', feature: 'battle_pass', notes: 'Archived until separately approved' },
  { table: 'battle_pass_tiers', class: 'disabled', feature: 'battle_pass' },
  { table: 'user_battle_pass', class: 'disabled', feature: 'battle_pass' },
  { table: 'rivals', class: 'disabled', feature: 'rivals', notes: 'Archived until separately approved' },
  { table: 'weekly_leaderboard', class: 'disabled', feature: 'rankings', notes: 'Archived until separately approved' },
  { table: 'realtime_duels', class: 'disabled', feature: 'rivals' },
  { table: 'friends', class: 'disabled', feature: 'social_tab', notes: 'Archived until separately approved' },
  { table: 'friend_requests', class: 'disabled', feature: 'social_tab' },
  { table: 'activity_feed', class: 'disabled', feature: 'social_tab' },
  { table: 'feed_likes', class: 'disabled', feature: 'social_tab' },
  { table: 'feed_reactions', class: 'disabled', feature: 'social_tab' },
  { table: 'messages', class: 'disabled', feature: 'social_tab' },
  { table: 'conversations', class: 'disabled', feature: 'social_tab' },
  { table: 'circle_activities', class: 'disabled', feature: 'social_tab' },
  { table: 'circle_invites', class: 'disabled', feature: 'social_tab' },
  { table: 'circle_members', class: 'disabled', feature: 'social_tab' },
  { table: 'circle_weekly_checks', class: 'disabled', feature: 'social_tab' },
  { table: 'study_circles', class: 'disabled', feature: 'social_tab' },
  { table: 'study_buddies', class: 'disabled', feature: 'social_tab' },
  { table: 'study_buddy_check_ins', class: 'disabled', feature: 'social_tab' },
  { table: 'study_buddy_encouragements', class: 'disabled', feature: 'social_tab' },
  { table: 'study_buddy_shared_goals', class: 'disabled', feature: 'social_tab' },
  { table: 'trading_listings', class: 'disabled', feature: 'inventory' },
  { table: 'victory_cards', class: 'disabled', feature: 'squads' },
  { table: 'synergy_activities', class: 'disabled', feature: 'squads' },
  { table: 'refund_requests', class: 'disabled', feature: 'shop' },
  { table: 'purchase_attempts', class: 'disabled', feature: 'shop' },
  { table: 'admin_users', class: 'internal' },
  { table: 'aggregated_stats', class: 'internal' },
  { table: 'export_jobs', class: 'internal' },
  { table: 'dashboard_layouts', class: 'internal' },
  { table: 'dashboard_widgets', class: 'internal' },
  { table: 'referrals', class: 'deprecated', notes: 'Referral system removed' },
  { table: 'shop', class: 'disabled', feature: 'shop', notes: 'Archived until separately approved' },
];
