import React,{useEffect,useRef,useState,useCallback,createContext,useContext}from'react'; import{View,ViewStyle,Dimensions,Pressable}from'react-native'; import Animated,{useSharedValue,useAnimatedStyle,withSpring,withTiming,runOnJS,interpolate,Extrapolation,SlideInUp,SlideOutUp,SlideInDown,SlideOutDown}from'react-native-reanimated'; import{GestureDetector,Gesture}from'react-native-gesture-handler'; import{Text}from'../../../components/primitives/Text'; import{Icon}from'../../../icons'; import type{IconProps}from'../../../icons'; import{useTheme}from'../../../theme'; import{createSheet}from'@/shared/ui/create-sheet'; export type ToastType='success'|'error'|'warning'|'info'; export type ToastPosition='top'|'bottom'|'center'; export interface ToastAction{label:string;onPress:()=>void;variant?:'default'|'destructive'}export interface ToastOptions{id?:string;type?:ToastType;title:string;message?:string;icon?:IconProps['name'];duration?:number;position?:ToastPosition;action?:ToastAction;onDismiss?:()=>void;persistent?:boolean;priority?:'low'|'normal'|'high'}export interface ToastItem extends ToastOptions{id:string;createdAt:number}interface ToastContextValue{show:(options:ToastOptions)=>string;dismiss:(id:string)=>void;dismissAll:()=>void;update:(id:string,options:Partial<ToastOptions>)=>void;toasts:ToastItem[]}interface ToastProviderProps{children:React.ReactNode;position?:ToastPosition;maxToasts?:number}const ToastContext = createContext<ToastContextValue|undefined>(undefined); export const useToast = ():ToastContextValue=>{const context = useContext(ToastContext); if(!context){throw new Error('useToast must be used within a ToastProvider');}return context;}; export const ToastProvider:React.FC<ToastProviderProps> = ({children,position = 'bottom',maxToasts = 3})=>{const[toasts,setToasts] = useState<ToastItem[]>([]); const idCounter = useRef(0); const show = useCallback((options:ToastOptions):string=>{const id = options.id || `toast-${++idCounter.current}-${Date.now()}`; setToasts(prev=>{const filtered = prev.filter(t=>t.id !== id); const newToast:ToastItem = {...options,id,type:options.type || 'info',duration:options.duration || 5000,position:options.position || position,priority:options.priority || 'normal',createdAt:Date.now()}; const newToasts = [...filtered,newToast].sort((a,b)=>{const priorityOrder = {high:0,normal:1,low:2}; return priorityOrder[a.priority!] - priorityOrder[b.priority!];}); return newToasts.slice(0,maxToasts);}); return id;},[maxToasts,position]); const dismiss = useCallback((id:string)=>{setToasts(prev=>prev.filter(t=>t.id !== id));},[]); const dismissAll = useCallback(()=>{setToasts([]);},[]); const update = useCallback((id:string,options:Partial<ToastOptions>)=>{setToasts(prev=>prev.map(t=>t.id === id ? {...t,...options} : t));},[]); const value:ToastContextValue = {show,dismiss,dismissAll,update,toasts}; return<ToastContext.Provider value={value}>
      {children}
      <ToastContainer toasts={toasts}onDismiss={dismiss}/>
      </ToastContext.Provider>;}; interface ToastProps{toast:ToastItem;onDismiss:(id:string)=>void;index:number}const Toast:React.FC<ToastProps> = ({toast,onDismiss,index})=>{const{theme} = useTheme(); const translateY = useSharedValue(0); const opacity = useSharedValue(1); const progress = useSharedValue(1); const scale = useSharedValue(1); const handleDismissRef = useRef<()=>void>(()=>undefined); useEffect(()=>{if(toast.persistent){return;}const duration = toast.duration || 5000; progress.value = withTiming(0,{duration}); const timer = setTimeout(()=>{handleDismissRef.current();},duration); return()=>clearTimeout(timer);},[progress,toast.id,toast.duration,toast.persistent]); const handleDismiss = useCallback(()=>{opacity.value = withTiming(0,{duration:200},finished=>{if(finished){runOnJS(onDismiss)(toast.id); toast.onDismiss?.();}});},[toast,onDismiss,opacity]); handleDismissRef.current = handleDismiss; const gestureHandler = Gesture.Pan().onUpdate(event=>{translateY.value = event.translationY; opacity.value = interpolate(Math.abs(event.translationY),[0,100],[1,0.5],Extrapolation.CLAMP);}).onEnd(event=>{if(Math.abs(event.translationY) > 80){translateY.value = withSpring(event.translationY * 2,{},()=>{runOnJS(handleDismiss)();});}else{translateY.value = withSpring(0); opacity.value = withTiming(1);}}); const getTypeStyles = ()=>{switch(toast.type){case'success':return{backgroundColor:theme.colors.success.DEFAULT,icon:toast.icon ?? 'check-circle',iconColor:'theme.colors.background.primary'}; case'error':return{backgroundColor:theme.colors.error.DEFAULT,icon:toast.icon ?? 'alert-circle',iconColor:'theme.colors.background.primary'}; case'warning':return{backgroundColor:theme.colors.warning.DEFAULT,icon:toast.icon ?? 'alert-triangle',iconColor:'theme.colors.background.primary'}; case'info':default:return{backgroundColor:theme.colors.primary[500],icon:toast.icon ?? 'info',iconColor:'theme.colors.background.primary'};}}; const typeStyles = getTypeStyles(); const animatedStyle = useAnimatedStyle(()=>({transform:[{translateY:translateY.value},{scale:scale.value}],opacity:opacity.value})); const progressStyle = useAnimatedStyle(()=>({width:`${progress.value * 100}%`})); const enteringAnimation = toast.position === 'top' ? SlideInUp : SlideInDown; const exitingAnimation = toast.position === 'top' ? SlideOutUp : SlideOutDown; return<Animated.View entering={enteringAnimation.delay(index * 100)}exiting={exitingAnimation}style={[styles.toastContainer,animatedStyle]}>
      <GestureDetector gesture={gestureHandler}>
        <Animated.View style={[styles.toast,{backgroundColor:typeStyles.backgroundColor}]}>
          {}
          <View style={styles.iconContainer}>
            <Icon name={typeStyles.icon}size="md"color={typeStyles.iconColor}/>
          </View>

          {}
          <View style={styles.content}>
            <Text variant="body"color="text.inverse"style={styles.title}>
              {toast.title}
            </Text>
            {toast.message && <Text variant="caption"color="text.inverse"style={styles.message}>
                {toast.message}
              </Text>}
          </View>

          {}
          {toast.action && <Pressable onPress={()=>{toast.action?.onPress(); handleDismiss();}}style={[styles.action,toast.action.variant === 'destructive' && styles.actionDestructive]}
  accessibilityLabel="Interactive control"
  accessibilityRole="button"
  accessibilityHint="Activates this control">
              <Text variant="caption"style={[styles.actionText,toast.action.variant === 'destructive' && styles.actionTextDestructive]}>
                {toast.action.label}
              </Text>
            </Pressable>}

          {}
          <Pressable onPress={handleDismiss}style={styles.dismissButton}
  accessibilityLabel="Interactive control"
  accessibilityRole="button"
  accessibilityHint="Activates this control">
            <Icon name="x"size="sm"color="theme.colors.background.primary"/>
          </Pressable>
        </Animated.View>
      </GestureDetector>

      {}
      {!toast.persistent && <Animated.View style={[styles.progressBar,{backgroundColor:'rgba(255,255,255,0.3)'},progressStyle]}/>}
    </Animated.View>;}; interface ToastContainerProps{toasts:ToastItem[];onDismiss:(id:string)=>void}const ToastContainer:React.FC<ToastContainerProps> = ({toasts,onDismiss})=>{const{height} = Dimensions.get('window'); const getPositionStyle = (position:ToastPosition):ViewStyle=>{switch(position){case'top':return{top:60}; case'center':return{top:height / 2 - 50}; case'bottom':default:return{bottom:100};}}; const toastsByPosition = toasts.reduce((acc,toast)=>{const pos = toast.position || 'bottom'; acc[pos] = acc[pos] || []; acc[pos].push(toast); return acc;},{}as Record<ToastPosition,ToastItem[]>); return<>
      {(Object.keys(toastsByPosition)as ToastPosition[]).map(position=><View key={position}style={[styles.container,getPositionStyle(position),{zIndex:9999 + (position === 'center' ? 2 : position === 'top' ? 1 : 0)}]}pointerEvents="box-none">
          {toastsByPosition[position].map((toast,index)=><Toast key={toast.id}toast={toast}onDismiss={onDismiss}index={index}/>)}
        </View>)}
    </>;}; export function useToastHelpers(){const{show,dismiss} = useToast(); const success = useCallback((title:string,message?:string,options?:Partial<ToastOptions>)=>{return show({type:'success',title,message,...options});},[show]); const error = useCallback((title:string,message?:string,options?:Partial<ToastOptions>)=>{return show({type:'error',title,message,duration:8000,...options});},[show]); const warning = useCallback((title:string,message?:string,options?:Partial<ToastOptions>)=>{return show({type:'warning',title,message,...options});},[show]); const info = useCallback((title:string,message?:string,options?:Partial<ToastOptions>)=>{return show({type:'info',title,message,...options});},[show]); const promise = useCallback(async<T,>(promise:Promise<T>,messages:{loading:string;success:string|((data:T)=>string);error:string|((error:Error)=>string)},options?:Partial<ToastOptions>):Promise<T>=>{const id = show({type:'info',title:messages.loading,persistent:true,...options}); try{const data = await promise; dismiss(id); show({type:'success',title:typeof messages.success === 'function' ? messages.success(data) : messages.success,...options}); return data;}catch(err){dismiss(id); show({type:'error',title:typeof messages.error === 'function' ? messages.error(err as Error) : messages.error,...options}); throw err;}},[show,dismiss]); return{success,error,warning,info,promise};}const styles = createSheet({container:{position:'absolute',left:16,right:16,alignItems:'center'},toastContainer:{width:'100%',marginBottom:8,borderRadius:12,overflow:'hidden',shadowColor:'theme.colors.text.primary',shadowOffset:{width:0,height:4},shadowOpacity:0.15,shadowRadius:8,elevation:5},toast:{flexDirection:'row',alignItems:'center',padding:16,minHeight:64},iconContainer:{marginRight:12},content:{flex:1},title:{fontWeight:'600'},message:{marginTop:2,opacity:0.9},action:{marginLeft:12,paddingHorizontal:12,paddingVertical:6,backgroundColor:'rgba(255,255,255,0.2)',borderRadius:6},actionDestructive:{backgroundColor:'rgba(239,68,68,0.3)'},actionText:{color:'theme.colors.background.primary',fontWeight:'600'},actionTextDestructive:{color:'theme.colors.primary[500]'},dismissButton:{marginLeft:8,padding:4},progressBar:{height:3,position:'absolute',bottom:0,left:0}}); export{Toast,ToastContainer}; export default ToastProvider;

