export const PENALTY_CONSTANTS = {
  PAUSE_PENALTY_BASE: 5,
  PAUSE_PENALTY_PER_MINUTE: 2,
  PAUSE_PENALTY_MAX: 100,
  INTERRUPTION_PENALTY_BASE: 10,
  INTERRUPTION_PENALTY_SEVERE: 25,
  INTERRUPTION_PENALTY_MINOR: 5,
  INTERRUPTION_PENALTY_MAX: 200,
  POOR_QUALITY_THRESHOLD: 40,
  BAD_QUALITY_THRESHOLD: 20,
  POOR_QUALITY_PENALTY: 50,
  BAD_QUALITY_PENALTY: 100,
  TIME_MANIPULATION_PENALTY: 500,
  DEVICE_CHANGE_PENALTY: 250,
  RAPID_COMPLETION_PENALTY: 300,
  SUSPICIOUS_PATTERN_PENALTY: 400,
  ABANDON_BASE_PENALTY: 100,
  ABANDON_STREAK_RISK_MULTIPLIER: 2,
  ABANDON_PROGRESS_FACTOR: 0.5,
  MAX_TOTAL_PENALTY_PERCENTAGE: 0.8,
} as const;

export const severityRankings: Record<string, number> = {
  LOW: 1,
  MEDIUM: 2,
  HIGH: 3,
  CRITICAL: 4,
};
