import { createSheet } from '@/shared/ui/create-sheet';
import { launchColors } from '@theme/tokens/launch-colors';

export const styles = createSheet({
  container: { flex: 1 },
  content: { padding: 16 },
  loadingText: {
    textAlign: 'center',
    marginTop: 12,
    fontSize: 14,
    color: launchColors.hex_666,
  },
  statsCard: { padding: 16, marginBottom: 12 },
  statsTitle: { fontSize: 16, fontWeight: '600', marginBottom: 12 },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 12,
  },
  statItem: { alignItems: 'center' },
  statValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: launchColors.hex_007aff,
  },
  statLabel: { fontSize: 12, color: launchColors.hex_666, marginTop: 2 },
  overallProgress: { marginTop: 8 },
  filterContainer: { marginBottom: 12 },
  filterContent: { gap: 8, paddingHorizontal: 4 },
  filterTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: launchColors.hex_f0f0f0,
  },
  filterTabActive: { backgroundColor: launchColors.hex_007aff },
  filterText: { fontSize: 13, fontWeight: '500', color: launchColors.hex_666 },
  filterTextActive: { color: launchColors.hex_fff },
  streakCard: {
    padding: 16,
    marginBottom: 12,
    backgroundColor: launchColors.hex_fff8e7,
  },
  streakHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  streakTitle: { fontSize: 16, fontWeight: '600' },
  streakDescription: {
    fontSize: 13,
    color: launchColors.hex_666,
    marginBottom: 12,
  },
  streakDays: { flexDirection: 'row', gap: 8 },
  streakDay: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: launchColors.hex_e0e0e0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  streakDayCompleted: { backgroundColor: launchColors.hex_ff9500 },
  streakDayText: {
    fontSize: 12,
    fontWeight: '600',
    color: launchColors.hex_666,
  },
  streakDayTextCompleted: { color: launchColors.hex_fff },
  listSection: { marginTop: 8 },
  listTitle: { fontSize: 18, fontWeight: '600', marginBottom: 12 },
  emptyCard: { padding: 32, alignItems: 'center' },
  emptyIcon: { fontSize: 48, marginBottom: 12 },
  emptyTitle: { fontSize: 16, fontWeight: '600', marginBottom: 4 },
  emptyText: { fontSize: 14, color: launchColors.hex_666, textAlign: 'center' },
});
