import { StyleSheet } from 'react-native';
import { createSheet } from '@/shared/ui/create-sheet';
import { lightColors } from '@/theme/tokens/colors';


export const levelUpStyles = createSheet({
  container: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  background: { ...StyleSheet.absoluteFill },
  confetti: { position: 'absolute', borderRadius: 2 },
  content: { alignItems: 'center', width: '100%' as const },
  levelBadge: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  badgeGradient: {
    width: 100,
    height: 100,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: lightColors.semantic.vexGold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    elevation: 20,
  },
  badgeRing: {
    ...StyleSheet.absoluteFill,
    borderRadius: 60,
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.3)',
  },
  levelNumber: {
    fontSize: 48,
    fontWeight: 'bold',
    color: lightColors.text.inverse,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
  },
  levelUpText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: lightColors.semantic.vexGold,
    textShadowColor: lightColors.semantic.vexGold,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 20,
    marginBottom: 16,
  },
  levelChangeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  previousLevel: {
    fontSize: 20,
    color: 'rgba(255,255,255,0.5)',
    textDecorationLine: 'line-through',
  },
  arrow: {
    fontSize: 24,
    color: lightColors.semantic.vexGold,
    marginHorizontal: 12,
  },
  newLevel: { fontSize: 28, fontWeight: 'bold' },
  tierTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 24,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  rewardsSection: { alignItems: 'center', marginBottom: 24 },
  rewardsLabel: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.6)',
    marginBottom: 12,
    letterSpacing: 2,
  },
  rewardsRow: { flexDirection: 'row', gap: 12 },
  rewardBadge: {
    width: 80,
    height: 100,
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  rewardGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 8,
  },
  rewardIcon: { fontSize: 24, marginBottom: 4 },
  rewardAmount: {
    fontSize: 16,
    fontWeight: 'bold',
    color: lightColors.text.inverse,
  },
  rewardType: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.7)',
    marginTop: 2,
  },
  unlocksSection: {
    width: '100%',
    marginBottom: 24,
    paddingHorizontal: 24,
  },
  unlocksLabel: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.6)',
    marginBottom: 12,
    textAlign: 'center',
    letterSpacing: 2,
  },
  unlockItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    padding: 12,
    borderRadius: 12,
    marginBottom: 8,
  },
  unlockIcon: { fontSize: 20, marginRight: 12 },
  unlockText: {
    fontSize: 14,
    color: lightColors.text.inverse,
    fontWeight: '500',
  },
  continueButton: {
    width: 200,
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: lightColors.semantic.vexGold,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  continueGradient: { paddingVertical: 16, alignItems: 'center' },
  continueText: {
    color: lightColors.text.inverse,
    fontSize: 18,
    fontWeight: 'bold',
  },
});
