import { withScreenErrorBoundary } from "../../shared/ui/components/ScreenErrorBoundary"; import React, { useRef } from "react"; import { Pressable, ScrollView, View } from "react-native"; import BottomSheet from "@gorhom/bottom-sheet"; import { useNavigation } from "@react-navigation/native"; import type { NativeStackNavigationProp } from "@react-navigation/native-stack"; import { useSafeAreaInsets } from "react-native-safe-area-context"; import { getPremiumCardStyle } from "../../components/premiumStyles"; import { Button } from "../../components/primitives/Button"; import { Text } from "../../components/primitives/Text"; import { useActiveBoss } from "../../features/boss/hooks"; import { useDisclosureAnalytics, useFeatureAccess } from "../../features/liveops-config"; import { getFeatureAvailability } from "../../features/liveops-config/feature-availability"; import { SquadMissionCard } from "../../features/squads"; import { CreateSquadFlow } from "../../features/squads/components/CreateSquadFlow"; import { SquadShareSheet } from "../../features/squads/components/SquadShareSheet"; import { useUserSquads } from "../../features/squads/hooks"; import { useSquadWeeklyStats } from "../../features/squads/hooks/useSquadWeeklyStats"; import type { ExtendedRootStackParams } from "../../navigation/types"; import { useAuthStore } from "../../store"; import { useTheme } from "../../theme";
type Nav = NativeStackNavigationProp<ExtendedRootStackParams>;
const emptyWeeklyStats = { totalSessions: 0, totalFocusMinutes: 0, activeMemberCount: 0 }; const currentBattleDate = new Intl.DateTimeFormat("en-US", { weekday: "short", month: "short", day: "numeric", }).format(new Date());
export function SocialScreen(): JSX.Element { const { theme } = useTheme(); const insets = useSafeAreaInsets(); const navigation = useNavigation<Nav>(); useDisclosureAnalytics(); const shareSheetRef = useRef<BottomSheet>(null); const createSheetRef = useRef<BottomSheet>(null); const userId = useAuthStore((state) => state.user?.id); const featureAccess = useFeatureAccess(); const squadAvailability = getFeatureAvailability(featureAccess.features.squads); const bossAvailability = getFeatureAvailability(featureAccess.features.boss_tab); const canNavigateSquads = squadAvailability.canNavigate; const canNavigateBoss = bossAvailability.canNavigate; const squadsQuery = useUserSquads(squadAvailability.canQuery ? userId : undefined); const primarySquad = squadsQuery.data?.[0] ?? null; const weeklyStatsQuery = useSquadWeeklyStats(primarySquad?.id); const weeklyStats = weeklyStatsQuery.data ?? emptyWeeklyStats; const activeBossQuery = useActiveBoss(bossAvailability.canQuery ? (userId ?? null) : null, primarySquad?.id);
return ( <> <ScrollView style={{ flex: 1, backgroundColor: theme.colors.background.primary }} contentContainerStyle={{ paddingTop: insets.top + theme.spacing[5], paddingBottom: theme.spacing[10], paddingHorizontal: theme.spacing[5], gap: theme.spacing[4], }} showsVerticalScrollIndicator={false} > <View style={{ gap: theme.spacing[2] }}> <Text variant="label" color={theme.colors.primary[500]}> Accountability </Text> <Text variant="h2" color={theme.colors.text.primary}> One place for shared momentum. </Text> <Text variant="body" color={theme.colors.text.secondary}> Social in VEX is here to reinforce your focus habit: squad progress, leaderboard pressure, and one clear reason to show up. </Text> </View>
{squadsQuery.isLoading ? ( <View style={{ padding: theme.spacing[4], ...getPremiumCardStyle("medium") }}> <Text variant="bodySmall" color={theme.colors.text.secondary}> Loading your accountability layer... </Text> </View> ) : null}
{squadsQuery.error instanceof Error ? ( <View style={{ padding: theme.spacing[4], ...getPremiumCardStyle("medium") }}> <Text variant="bodySmall" color={theme.colors.error.DEFAULT}> {squadsQuery.error.message} </Text> </View> ) : null}
{!primarySquad && !squadsQuery.isLoading ? ( <> <View style={{ borderWidth: 1, borderColor: theme.colors.border.light, backgroundColor: theme.colors.background.secondary, padding: theme.spacing[4], gap: theme.spacing[3], ...getPremiumCardStyle("large"), }} > <Text variant="label" color={theme.colors.primary[500]}> Start with one squad </Text> <Text variant="h4" color={theme.colors.text.primary}> No accountability circle yet. </Text> <Text variant="bodySmall" color={theme.colors.text.secondary}> Create a squad when you want visible team momentum, weekly pressure, and a shared reason to keep your streak alive. </Text> <Button onPress={() => createSheetRef.current?.snapToIndex(0)} accessibilityLabel="Create a Squad button" accessibilityRole="button" accessibilityHint="Activates this control"> Create a Squad </Button> </View> <SquadMissionCard /> </> ) : null}
{primarySquad ? ( <> <View style={{ borderWidth: 1, borderColor: theme.colors.border.light, backgroundColor: theme.colors.background.secondary, padding: theme.spacing[4], gap: theme.spacing[3], ...getPremiumCardStyle("large"), }} > <Text variant="label" color={theme.colors.primary[500]}> Primary Squad </Text> <Text variant="h4" color={theme.colors.text.primary}> {primarySquad.name} </Text> <Text variant="bodySmall" color={theme.colors.text.secondary}>
                {`${primarySquad.memberCount}/${primarySquad.maxMembers} members • ${primarySquad.focusMultiplier.toFixed(1)}x focus multiplier`}
</Text>
{weeklyStatsQuery.isLoading ? ( <Text variant="bodySmall" color={theme.colors.text.secondary}> Loading this week&apos;s momentum... </Text> ) : null} {weeklyStatsQuery.error instanceof Error ? ( <Text variant="bodySmall" color={theme.colors.error.DEFAULT}> {weeklyStatsQuery.error.message} </Text> ) : null} {!weeklyStatsQuery.isLoading && !(weeklyStatsQuery.error instanceof Error) ? ( <View style={{ gap: theme.spacing[2] }}> <Text variant="bodySmall" color={theme.colors.text.primary}>
                    {`${weeklyStats.totalSessions} sessions logged this week`}
</Text> <Text variant="bodySmall" color={theme.colors.text.primary}>
                    {`${Math.round(weeklyStats.totalFocusMinutes / 60)} total focus hours`}
</Text> <Text variant="bodySmall" color={theme.colors.text.primary}>
                    {`${weeklyStats.activeMemberCount} active members`}
</Text> {weeklyStats.activeMemberCount === 0 ? ( <Text variant="bodySmall" color={theme.colors.text.secondary}> No one has logged a session yet this week. Be the one who starts the push. </Text> ) : null} </View> ) : null}
<View style={{ flexDirection: "row", gap: theme.spacing[3], flexWrap: "wrap", }} > <Button variant="outline" onPress={() => { navigation.navigate("Main", { screen: "Home" }); }} accessibilityLabel="Open squad button" accessibilityRole="button" accessibilityHint="Activates this control" > Open squad </Button> <Button variant="secondary" onPress={() => shareSheetRef.current?.snapToIndex(0)} accessibilityLabel="Share this week button" accessibilityRole="button" accessibilityHint="Activates this control"> Share this week </Button> </View> </View>
<View style={{ gap: theme.spacing[3] }}> <Text variant="h4" color={theme.colors.text.primary}>
                {`Today's push • ${currentBattleDate}`}
</Text> <SquadMissionCard squadId={primarySquad.id} /> </View>
{activeBossQuery.data && canNavigateBoss ? ( <Pressable onPress={() => navigation.navigate("Boss")} style={{ borderWidth: 1, borderColor: theme.colors.primary[500], backgroundColor: theme.colors.background.secondary, padding: theme.spacing[4], gap: theme.spacing[2], ...getPremiumCardStyle("medium"), }} accessibilityLabel="Boss is live Even one focused session moves the encounter forward. button" accessibilityRole="button" accessibilityHint="Activates this control" > <Text variant="label" color={theme.colors.primary[500]}> Boss is live </Text> <Text variant="h4" color={theme.colors.text.primary}> {activeBossQuery.data.bossName} </Text> <Text variant="bodySmall" color={theme.colors.text.secondary}> Even one focused session moves the encounter forward. </Text> </Pressable> ) : null}
<View style={{ borderWidth: 1, borderColor: theme.colors.border.light, backgroundColor: theme.colors.background.secondary, padding: theme.spacing[4], gap: theme.spacing[3], ...getPremiumCardStyle("medium"), }} > <Text variant="label" color={theme.colors.text.secondary}> Activity feed </Text> <Text variant="bodySmall" color={theme.colors.text.secondary}> Detailed feed and deeper competitive modes are still here, but your main job is simpler: keep your squad moving. </Text> <Text variant="bodySmall" color={theme.colors.text.secondary} style={{ marginTop: 8 }}> Feed feature removed for simplified launch. Focus on your squad missions. </Text> </View> </> ) : null} </ScrollView>
<SquadShareSheet bottomSheetRef={shareSheetRef} squad={primarySquad} weeklyStats={weeklyStats} /> {userId ? <CreateSquadFlow bottomSheetRef={createSheetRef} userId={userId} /> : null} </> ); }
export default withScreenErrorBoundary(SocialScreen, "Social");
