import { createSheet } from '@/shared/ui/create-sheet';
import { lightColors } from '@/theme/tokens/colors';


export const errorStateStyles = createSheet({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: lightColors.text.inverse,
    borderRadius: 12,
    margin: 16,
  },
  degradedContainer: {
    backgroundColor: lightColors.warning[50],
    borderWidth: 1,
    borderColor: lightColors.semantic.warning,
  },
  icon: { fontSize: 48, marginBottom: 12 },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: lightColors.semantic.obsidian,
    textAlign: 'center',
    marginBottom: 8,
  },
  message: {
    fontSize: 14,
    color: lightColors.text.muted,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 16,
  },
  errorCodeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 16,
  },
  errorCodeLabel: { fontSize: 12, color: lightColors.text.disabled },
  errorCode: {
    fontSize: 12,
    color: lightColors.text.disabled,
    fontFamily: 'monospace',
    backgroundColor: lightColors.surface.button,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  attemptsText: { fontSize: 12, color: lightColors.text.disabled, marginBottom: 12 },
  actions: { gap: 8, width: '100%' },
  retryButton: {
    backgroundColor: lightColors.semantic.danger,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
    minWidth: 120,
  },
  retryButtonText: {
    color: lightColors.text.inverse,
    fontSize: 16,
    fontWeight: '600',
  },
  buttonDisabled: { opacity: 0.6 },
  dismissButton: { paddingVertical: 12, alignItems: 'center' },
  dismissButtonText: {
    color: lightColors.text.muted,
    fontSize: 14,
    fontWeight: '500',
  },
  maxRetriesText: {
    fontSize: 12,
    color: lightColors.text.disabled,
    textAlign: 'center',
    marginTop: 8,
  },
  degradedBadge: {
    backgroundColor: lightColors.semantic.warning,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    marginTop: 12,
  },
  degradedBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: lightColors.text.secondary,
  },
  inlineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: 8,
    backgroundColor: lightColors.error[50],
    borderRadius: 6,
    marginTop: 4,
  },
  inlineIcon: { fontSize: 14 },
  inlineText: { fontSize: 12, color: lightColors.semantic.danger, flex: 1 },
});
