import { createSheet } from '@/shared/ui/create-sheet';
import { launchColors } from '@theme/tokens/launch-colors';

export const styles = createSheet({
  progressContainer: { overflow: 'hidden', width: '100%' },
  progressFill: { height: '100%' },
  progressText: {
    fontSize: 12,
    color: launchColors.hex_666,
    marginTop: 4,
    textAlign: 'right',
  },
  segmentedContainer: { flexDirection: 'row', width: '100%' },
  segment: { flex: 1 },
  circularContainer: { justifyContent: 'center', alignItems: 'center' },
  circularSvg: { position: 'relative' },
  circularBackground: { position: 'absolute' },
  circularProgress: { position: 'absolute', transform: [{ rotate: '0deg' }] },
  circularText: {
    position: 'absolute',
    fontWeight: '700',
    color: launchColors.hex_333,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loadingMessage: {
    fontSize: 16,
    fontWeight: '600',
    color: launchColors.hex_333,
    marginTop: 16,
  },
  loadingSubmessage: {
    fontSize: 14,
    color: launchColors.hex_666,
    marginTop: 8,
    textAlign: 'center',
  },
  loadingProgress: { width: '100%', maxWidth: 200, marginTop: 16 },
  dotsContainer: { flexDirection: 'row', gap: 8, alignItems: 'center' },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: launchColors.hex_4ecdc4,
  },
  stepsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  stepItem: { alignItems: 'center', flex: 1 },
  stepCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: launchColors.hex_e1e4e8,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  stepCircleCompleted: { backgroundColor: launchColors.hex_4ecdc4 },
  stepCircleCurrent: { backgroundColor: launchColors.hex_ffd93d },
  stepNumber: { fontSize: 14, fontWeight: '600', color: launchColors.hex_666 },
  stepNumberActive: { color: launchColors.hex_fff },
  stepCheck: { fontSize: 16, color: launchColors.hex_fff, fontWeight: '700' },
  stepLabel: { fontSize: 12, color: launchColors.hex_999, textAlign: 'center' },
  stepLabelCompleted: { color: launchColors.hex_4ecdc4 },
  stepLabelCurrent: { color: launchColors.hex_333, fontWeight: '600' },
  stepLine: {
    position: 'absolute',
    top: 15,
    left: '50%',
    width: '100%',
    height: 2,
    backgroundColor: launchColors.hex_e1e4e8,
    zIndex: -1,
  },
  stepLineCompleted: { backgroundColor: launchColors.hex_4ecdc4 },
  successContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  successIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: launchColors.hex_4ecdc4,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  successIconText: {
    fontSize: 40,
    color: launchColors.hex_fff,
    fontWeight: '700',
  },
  successTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: launchColors.hex_333,
    marginBottom: 8,
  },
  successMessage: {
    fontSize: 16,
    color: launchColors.hex_666,
    textAlign: 'center',
  },
  processingContainer: { gap: 16, padding: 16 },
  processingItem: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  processingDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: launchColors.hex_e1e4e8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  processingDotCompleted: { backgroundColor: launchColors.hex_4ecdc4 },
  processingDotError: { backgroundColor: launchColors.hex_ff6b6b },
  processingDotProcessing: { backgroundColor: launchColors.hex_ffd93d },
  processingCheck: {
    fontSize: 12,
    color: launchColors.hex_fff,
    fontWeight: '700',
  },
  processingError: {
    fontSize: 12,
    color: launchColors.hex_fff,
    fontWeight: '700',
  },
  processingLabel: { fontSize: 14, color: launchColors.hex_999 },
  processingLabelCompleted: {
    color: launchColors.hex_4ecdc4,
    textDecorationLine: 'line-through',
  },
  processingLabelError: { color: launchColors.hex_ff6b6b },
});
