

export const COMBAT_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'achievement-first-boss',
    title: 'Boss Slayer',
    description: 'Defeat your first boss',
    category: 'BOSS',
    rarity: 'COMMON',
    icon: '⚔️',
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: 'BOSS_DEFEAT',
      target: 1,
      comparator: 'GREATER_THAN',
    },
    reward: { coins: 150, xp: 300, badge: 'Boss Slayer' },
    pointValue: 15,
    shareText: 'First boss defeated! Boss Slayer ⚔️',
    unlockRate: 0.7,
  },
  {
    id: 'achievement-10-bosses',
    title: 'Boss Hunter',
    description: 'Defeat 10 different bosses',
    category: 'BOSS',
    rarity: 'UNCOMMON',
    icon: '🏹',
    isHidden: false,
    progressMax: 10,
    unlockCondition: {
      type: 'BOSS_DEFEAT_UNIQUE',
      target: 10,
      comparator: 'GREATER_THAN',
    },
    reward: { coins: 500, xp: 1000, badge: 'Boss Hunter' },
    pointValue: 30,
    shareText: '10 bosses hunted! Boss Hunter 🏹',
    unlockRate: 0.25,
  },
  {
    id: 'achievement-squad-war-win',
    title: 'War Victor',
    description: 'Win a squad war',
    category: 'SOCIAL',
    rarity: 'UNCOMMON',
    icon: '🏴',
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: 'SQUAD_WAR_WIN',
      target: 1,
      comparator: 'GREATER_THAN',
    },
    reward: { coins: 300, xp: 600, badge: 'War Victor' },
    pointValue: 30,
    shareText: 'Squad war victory! War Victor 🏴',
    unlockRate: 0.3,
  },
  {
    id: 'achievement-duel-win-10',
    title: 'Duelist',
    description: 'Win 10 duels',
    category: 'SOCIAL',
    rarity: 'RARE',
    icon: '🤺',
    isHidden: false,
    progressMax: 10,
    unlockCondition: {
      type: 'DUEL_WIN',
      target: 10,
      comparator: 'GREATER_THAN',
    },
    reward: { coins: 600, xp: 1200, badge: 'Duelist', title: 'Champion' },
    pointValue: 50,
    shareText: '10 duels won! Duelist Champion 🤺',
    unlockRate: 0.15,
  },
  {
    id: 'achievement-mvp',
    title: 'MVP',
    description: 'Become MVP in a squad war',
    category: 'SOCIAL',
    rarity: 'EPIC',
    icon: '🌟',
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: 'SQUAD_WAR_MVP',
      target: 1,
      comparator: 'GREATER_THAN',
    },
    reward: { coins: 1000, xp: 2000, badge: 'MVP', title: 'Most Valuable' },
    pointValue: 100,
    shareText: 'War MVP! Most Valuable Player 🌟',
    unlockRate: 0.08,
  },
];

export const SOCIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'achievement-join-squad',
    title: 'Squad Member',
    description: 'Join a squad',
    category: 'SOCIAL',
    rarity: 'COMMON',
    icon: '👥',
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: 'SQUAD_JOIN',
      target: 1,
      comparator: 'GREATER_THAN',
    },
    reward: { coins: 100, xp: 200 },
    pointValue: 10,
    shareText: 'Joined a squad! Squad Member 👥',
    unlockRate: 0.65,
  },
  {
    id: 'achievement-recruit-friend',
    title: 'Recruiter',
    description: 'Recruit a friend to the app',
    category: 'SOCIAL',
    rarity: 'UNCOMMON',
    icon: '📢',
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: 'FRIEND_RECRUIT',
      target: 1,
      comparator: 'GREATER_THAN',
    },
    reward: { coins: 300, xp: 500, badge: 'Recruiter' },
    pointValue: 25,
    shareText: 'Friend recruited! Spread the word 📢',
    unlockRate: 0.2,
  },
  {
    id: 'achievement-top-squad',
    title: 'Elite Squad',
    description: 'Reach top 10 on squad leaderboard',
    category: 'SOCIAL',
    rarity: 'RARE',
    icon: '🏛️',
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: 'LEADERBOARD_RANK',
      target: 10,
      comparator: 'LESS_THAN',
      context: { type: 'squad' },
    },
    reward: { coins: 800, xp: 1500, badge: 'Elite Squad' },
    pointValue: 50,
    shareText: 'Top 10 squad! Elite Squad 🏛️',
    unlockRate: 0.05,
  },
];