import type { FeatureClassificationEntry } from "./final-release-classification";

export const ARCHIVED_ECONOMY: FeatureClassificationEntry[] = [
  {
    systemId: "shop",
    folder: "shop",
    status: "archived_or_deactivated",
    featureKey: "shop",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Shop UI + economy. Deactivated.",
  },
  {
    systemId: "inventory",
    folder: "inventory",
    status: "archived_or_deactivated",
    featureKey: "inventory",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Item inventory. Deactivated.",
  },
  {
    systemId: "wallet",
    folder: "wallet",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Wallet UI. Deactivated.",
  },
  {
    systemId: "items",
    folder: "items",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Items data. Deactivated.",
  },
  {
    systemId: "battle_pass",
    folder: "battle-pass",
    status: "archived_or_deactivated",
    featureKey: "battle_pass",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Battle pass. Deactivated.",
  },
  {
    systemId: "economy_user_facing",
    folder: "economy",
    status: "archived_or_deactivated",
    featureKey: "economy_basic",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "User wallet/shop/rewards UI. XP ledger (internal) is active.",
  },
];
