import type { FeatureClassificationEntry } from './final-release-classification';

export const ARCHIVED_SOCIAL_COMPETITIVE: FeatureClassificationEntry[] = [
  {
    systemId: 'squads',
    folder: 'squads',
    status: 'archived_or_deactivated',
    featureKey: 'squads',
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: 'Squads. Deactivated.',
  },
  {
    systemId: 'boss_realtime',
    folder: 'boss-realtime',
    status: 'archived_or_deactivated',
    featureKey: 'boss_bounties',
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: 'Community boss realtime. Deactivated.',
  },
  {
    systemId: 'spectacle',
    folder: 'spectacle',
    status: 'archived_or_deactivated',
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: 'Visual spectacle. Deactivated.',
  },
  {
    systemId: 'live_ops',
    folder: 'live-ops',
    status: 'archived_or_deactivated',
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: 'Live ops. Deactivated.',
  },
  {
    systemId: 'social',
    folder: 'social',
    status: 'archived_or_deactivated',
    featureKey: 'social_tab',
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: 'Social feed. Deactivated.',
  },
  {
    systemId: 'mastery',
    folder: 'mastery',
    status: 'archived_or_deactivated',
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: 'Mastery. Deactivated.',
  },
];
