import type { FeatureClassificationEntry } from "./final-release-classification";

export const ARCHIVED_RETENTION: FeatureClassificationEntry[] = [
  {
    systemId: "daily_mission",
    folder: "daily-mission",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Daily missions. Deactivated.",
  },
  {
    systemId: "weekly_quests",
    folder: "weekly-quests",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Weekly quests. Deactivated.",
  },
  {
    systemId: "retention",
    folder: "retention",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Retention hooks. Deactivated.",
  },
  {
    systemId: "emotion_retention",
    folder: "emotion-retention",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Emotional retention. Deactivated.",
  },
  {
    systemId: "monthly_report",
    folder: "monthly-report",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Monthly report. Deactivated.",
  },
  {
    systemId: "seasons",
    folder: "seasons",
    status: "archived_or_deactivated",
    featureKey: "seasonal_features",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Seasonal systems. Deactivated.",
  },
  {
    systemId: "session_story",
    folder: "session-story",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "PostSessionStory route. NOT session_completion narrative.",
  },
  {
    systemId: "themes_shop",
    folder: "themes",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Theme shop. Same folder as themes_visual.",
  },
];
