import type { FeatureClassificationEntry } from "./final-release-classification";

export const ARCHIVED: FeatureClassificationEntry[] = [
  {
    systemId: "shop",
    folder: "shop",
    status: "archived_or_deactivated",
    featureKey: "shop",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Shop UI + economy. Deactivated.",
  },
  {
    systemId: "inventory",
    folder: "inventory",
    status: "archived_or_deactivated",
    featureKey: "inventory",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Item inventory. Deactivated.",
  },
  {
    systemId: "wallet",
    folder: "wallet",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Wallet UI. Deactivated.",
  },
  {
    systemId: "items",
    folder: "items",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Items data. Deactivated.",
  },
  {
    systemId: "battle_pass",
    folder: "battle-pass",
    status: "archived_or_deactivated",
    featureKey: "battle_pass",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Battle pass. Deactivated.",
  },
  {
    systemId: "squads",
    folder: "squads",
    status: "archived_or_deactivated",
    featureKey: "squads",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Squads. Deactivated.",
  },
  {
    systemId: "boss_realtime",
    folder: "boss-realtime",
    status: "archived_or_deactivated",
    featureKey: "boss_bounties",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Community boss realtime. Deactivated.",
  },
  {
    systemId: "spectacle",
    folder: "spectacle",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Visual spectacle. Deactivated.",
  },
  {
    systemId: "live_ops",
    folder: "live-ops",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Live ops. Deactivated.",
  },
  {
    systemId: "social",
    folder: "social",
    status: "archived_or_deactivated",
    featureKey: "social_tab",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Social feed. Deactivated.",
  },
  {
    systemId: "mastery",
    folder: "mastery",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Mastery. Deactivated.",
  },
  {
    systemId: "daily_mission",
    folder: "daily-mission",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Daily missions. Deactivated.",
  },
  {
    systemId: "weekly_quests",
    folder: "weekly-quests",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Weekly quests. Deactivated.",
  },
  {
    systemId: "retention",
    folder: "retention",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Retention hooks. Deactivated.",
  },
  {
    systemId: "emotion_retention",
    folder: "emotion-retention",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Emotional retention. Deactivated.",
  },
  {
    systemId: "monthly_report",
    folder: "monthly-report",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Monthly report. Deactivated.",
  },
  {
    systemId: "seasons",
    folder: "seasons",
    status: "archived_or_deactivated",
    featureKey: "seasonal_features",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Seasonal systems. Deactivated.",
  },
  {
    systemId: "session_story",
    folder: "session-story",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "PostSessionStory route. NOT session_completion narrative.",
  },
  {
    systemId: "themes_shop",
    folder: "themes",
    status: "archived_or_deactivated",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Theme shop. Same folder as themes_visual.",
  },
  {
    systemId: "economy_user_facing",
    folder: "economy",
    status: "archived_or_deactivated",
    featureKey: "economy_basic",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "User wallet/shop/rewards UI. XP ledger (internal) is active.",
  },
];
