import type { FeatureClassificationEntry } from "./final-release-classification";

export const ACTIVE: FeatureClassificationEntry[] = [
  {
    systemId: "focus_session",
    folder: "session",
    status: "final_release_active",
    featureKey: "focus_session",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Core session loop.",
  },
  {
    systemId: "session_start",
    folder: "session-start",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Session start flow.",
  },
  {
    systemId: "session_completion",
    folder: "session-completion",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes:
      "Completion ledger + adaptive payoff. Does NOT include PostSessionStory (archived).",
  },
  {
    systemId: "home_experience",
    folder: "home-experience",
    status: "final_release_active",
    featureKey: "home_tab",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Adaptive Home.",
  },
  {
    systemId: "home_spine",
    folder: "home-spine",
    status: "final_release_active",
    featureKey: "home_tab",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Home navigation spine.",
  },
  {
    systemId: "today_system",
    folder: "today-system",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: false,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Minimal lane Today Strip. Home-only, no standalone route.",
  },
  {
    systemId: "ai_coach_basic",
    folder: "ai-coach",
    status: "final_release_active",
    featureKey: "ai_coach_basic",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Coach presence + basic companion. Advanced coach is progressive.",
  },
  {
    systemId: "coach_presence",
    folder: "coach-presence",
    status: "final_release_active",
    featureKey: "ai_coach_basic",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Coach presence rendering.",
  },
  {
    systemId: "progression",
    folder: "progression",
    status: "final_release_active",
    featureKey: "progress_view",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Streak/XP/level. Always active.",
  },
  {
    systemId: "streaks",
    folder: "streaks",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Streak tracking.",
  },
  {
    systemId: "focus_contract",
    folder: "focus-contract",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Session contracts.",
  },
  {
    systemId: "focus_identity",
    folder: "focus-identity",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Focus score.",
  },
  {
    systemId: "lane_engine",
    folder: "lane-engine",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Canonical lane resolver. Internal decision boundary.",
  },
  {
    systemId: "focus_profile",
    folder: "focus-profile",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes:
      "Typed focus profile. Local-first until Supabase persistence is added.",
  },
  {
    systemId: "rescue_mode",
    folder: "rescue-mode",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: false,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Short recovery plans. Entry from session setup/home only.",
  },
  {
    systemId: "notification_policy",
    folder: "notification-policy",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: true,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Nudge budget and lane notification rules.",
  },
  {
    systemId: "personal_bests",
    folder: "personal-bests",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Personal best tracking.",
  },
  {
    systemId: "session_history",
    folder: "session-history",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Past session viewing.",
  },
  {
    systemId: "session_recommendation",
    folder: "session-recommendation",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Next session suggestions.",
  },
  {
    systemId: "session_events",
    folder: "session-events",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Session event bus. System-only.",
  },
  {
    systemId: "learning_execution",
    folder: "learning-execution",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Learning execution layer.",
  },
  {
    systemId: "notifications_system",
    folder: "notifications",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Notification system.",
  },
  {
    systemId: "onboarding",
    folder: "onboarding",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "One-time onboarding flow.",
  },
  {
    systemId: "personalization",
    folder: "personalization",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Motivation adaptation engine. Internal.",
  },
  {
    systemId: "themes_visual",
    folder: "themes",
    status: "final_release_active",
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Visual themes only. Shop modal is archived.",
  },
];
