import type { FeatureClassificationEntry } from './final-release-classification';

export const SESSION_FEATURES: FeatureClassificationEntry[] = [
  {
    systemId: 'focus_session',
    folder: 'session',
    status: 'final_release_active',
    featureKey: 'focus_session',
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: 'Core session loop.',
  },
  {
    systemId: 'session_start',
    folder: 'session-start',
    status: 'final_release_active',
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: 'Session start flow.',
  },
  {
    systemId: 'session_completion',
    folder: 'session-completion',
    status: 'final_release_active',
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes:
      'Completion ledger + adaptive payoff. Does NOT include PostSessionStory (archived).',
  },
  {
    systemId: 'session_history',
    folder: 'session-history',
    status: 'final_release_active',
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: 'Past session viewing.',
  },
  {
    systemId: 'session_recommendation',
    folder: 'session-recommendation',
    status: 'final_release_active',
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: 'Next session suggestions.',
  },
  {
    systemId: 'session_events',
    folder: 'session-events',
    status: 'final_release_active',
    minSessions: 0,
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: 'Session event bus. System-only.',
  },
  {
    systemId: 'learning_execution',
    folder: 'learning-execution',
    status: 'final_release_active',
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: 'Learning execution layer.',
  },
  {
    systemId: 'notifications_system',
    folder: 'notifications',
    status: 'final_release_active',
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: 'Notification system.',
  },
  {
    systemId: 'onboarding',
    folder: 'onboarding',
    status: 'final_release_active',
    minSessions: 0,
    routeAllowed: true,
    homeAllowed: false,
    queryAllowed: false,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: 'One-time onboarding flow.',
  },
];
