import type { FeatureClassificationEntry } from "./final-release-classification";

export const INTERNAL: FeatureClassificationEntry[] = [
  {
    systemId: "reward_ledger",
    folder: "reward-ledger",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Internal reward accounting.",
  },
  {
    systemId: "rewards_service",
    folder: "rewards",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Reward delivery engine.",
  },
  {
    systemId: "economy_xp_ledger",
    folder: "economy",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "XP/streak ledger. User-facing wallet/shop/gems are archived.",
  },
  {
    systemId: "monetization_layer",
    folder: "monetization",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "RevenueCat + paywall layer. User-facing paywall is progressive.",
  },
  {
    systemId: "feature_gate",
    folder: "feature-gate",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Feature gate runtime.",
  },
  {
    systemId: "liveops_config",
    folder: "liveops-config",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Feature availability + health checks.",
  },
  {
    systemId: "analytics_telemetry",
    folder: "analytics",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Telemetry + Sentry.",
  },
  {
    systemId: "account_deletion",
    folder: "account-deletion",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Account management.",
  },
  {
    systemId: "integration",
    folder: "integration",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "External integration layer.",
  },
  {
    systemId: "companion_promise",
    folder: "companion-promise",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Companion promise infrastructure.",
  },
  {
    systemId: "unlock_explainer",
    folder: "unlock-explainer",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Unlock decision explainer service. No UI.",
  },
  {
    systemId: "memory_candidate",
    folder: "memory-candidate",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Memory candidate store for session completion memories.",
  },
  {
    systemId: "study_intelligence",
    folder: "study-intelligence",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "Study intelligence analytics. Internal.",
  },
  {
    systemId: "vex_actions",
    folder: "vex-actions",
    status: "final_release_internal",
    routeAllowed: false,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes: "VEX action definitions and executors.",
  },
];