import type { FeatureClassificationEntry } from "./final-release-classification";

export const PROGRESSIVE_ADVANCED: FeatureClassificationEntry[] = [
  {
    systemId: "project_focus",
    folder: "project-focus",
    status: "final_release_progressive",
    featureKey: "content_study",
    minSessions: 12,
    routeAllowed: false,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: true,
    appStoreCopyAllowed: false,
    notes:
      "Deep/creative project thread model. Uses content study gate until route ships.",
  },
  {
    systemId: "focus_run",
    folder: "focus-run",
    status: "final_release_progressive",
    featureKey: "boss_tab",
    minSessions: 7,
    routeAllowed: false,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes:
      "Game-like lane run model. Home/completion only until dedicated route ships.",
  },
  {
    systemId: "ai_coach_advanced",
    folder: "ai-coach",
    status: "final_release_progressive",
    featureKey: "ai_coach_advanced",
    minSessions: 8,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: true,
    appStoreCopyAllowed: false,
    notes: "Deep Coach Memory. Premium-gated. Same folder as ai_coach_basic.",
  },
  {
    systemId: "content_study_advanced",
    folder: "content-study",
    status: "final_release_progressive",
    featureKey: "content_study_advanced",
    minSessions: 18,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: true,
    appStoreCopyAllowed: false,
    notes: "Advanced Study OS. Premium-gated.",
  },
  {
    systemId: "quiz_review_mode",
    folder: "content-study",
    status: "final_release_progressive",
    featureKey: "quiz_review_mode",
    minSessions: 10,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: true,
    appStoreCopyAllowed: false,
    notes: "Quiz/review. Premium-gated.",
  },
  {
    systemId: "advanced_settings",
    folder: "settings",
    status: "final_release_progressive",
    featureKey: "advanced_settings",
    minSessions: 12,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Settings & privacy. Unlocks at 12.",
  },
  {
    systemId: "premium_paywall",
    folder: "monetization",
    status: "final_release_progressive",
    featureKey: "premium_paywall",
    minSessions: 40,
    routeAllowed: true,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: false,
    completionAllowed: false,
    premiumCopyAllowed: true,
    appStoreCopyAllowed: false,
    notes: "Premium paywall. minSessions=40 (was 5 in old map — corrected).",
  },
];
