import type { FeatureClassificationEntry } from "./final-release-classification";

export const PROGRESSIVE_EARLY: FeatureClassificationEntry[] = [
  {
    systemId: "memory_console",
    folder: "focus-memory",
    status: "final_release_progressive",
    featureKey: "memory_console",
    minSessions: 3,
    routeAllowed: true,
    homeAllowed: false,
    queryAllowed: true,
    subscriptionAllowed: false,
    notificationAllowed: false,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: false,
    notes:
      "Memory Console unlocks after 3 sessions. Inspectable, editable, deletable memory ledger.",
  },
  {
    systemId: "companion_detail",
    folder: "companion",
    status: "final_release_progressive",
    featureKey: "companion_detail",
    minSessions: 3,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Companion visual detail. Unlocks at 3 sessions.",
  },
  {
    systemId: "challenges",
    folder: "challenges",
    status: "final_release_progressive",
    featureKey: "challenges",
    minSessions: 5,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Challenges. Unlocks at 5.",
  },
  {
    systemId: "achievements",
    folder: "achievements",
    status: "final_release_progressive",
    featureKey: "achievements",
    minSessions: 6,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Achievements. Unlocks at 6.",
  },
  {
    systemId: "boss",
    folder: "boss",
    status: "final_release_progressive",
    featureKey: "boss_tab",
    minSessions: 7,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Boss momentum. Unlocks at 7.",
  },
  {
    systemId: "content_study",
    folder: "content-study",
    status: "final_release_progressive",
    featureKey: "content_study",
    minSessions: 12,
    routeAllowed: true,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: false,
    appStoreCopyAllowed: true,
    notes: "Study/Deep Work entry. Unlocks at 12.",
  },
  {
    systemId: "study_os",
    folder: "study-os",
    status: "final_release_progressive",
    featureKey: "content_study",
    minSessions: 12,
    routeAllowed: false,
    homeAllowed: true,
    queryAllowed: true,
    subscriptionAllowed: true,
    notificationAllowed: true,
    completionAllowed: true,
    premiumCopyAllowed: true,
    appStoreCopyAllowed: false,
    notes: "Student lane Study OS model. Uses content study gate.",
  },
];
