import { createSheet } from '@/shared/ui/create-sheet';


export const styles = createSheet({
  container: {
    backgroundColor: 'white',
    borderRadius: 12,
    overflow: 'hidden',
    margin: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  header: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  phaseName: { fontSize: 16, fontWeight: 'bold', color: 'white' },
  enragedBadge: {
    backgroundColor: 'rgba(0,0,0,0.3)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  enragedText: { color: 'white', fontSize: 12, fontWeight: 'bold' },
  progressSection: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  thresholds: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  thresholdContainer: { alignItems: 'center' },
  thresholdDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#e2e8f0',
  },
  thresholdDotActive: { backgroundColor: '#4a5568' },
  thresholdDotPhase: {
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#4a5568',
  },
  thresholdLabel: {
    fontSize: 10,
    color: '#a0aec0',
    marginTop: 4,
  },
  thresholdLabelActive: { color: '#4a5568', fontWeight: '600' },
  healthBarContainer: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  healthBarBackground: {
    flex: 1,
    height: 12,
    backgroundColor: '#e2e8f0',
    borderRadius: 6,
    overflow: 'hidden',
  },
  healthBar: { height: '100%', borderRadius: 6 },
  healthPercent: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4a5568',
    minWidth: 45,
  },
  nextPhaseText: {
    fontSize: 12,
    color: '#718096',
    marginTop: 8,
    fontStyle: 'italic',
  },
  descriptionSection: {
    padding: 16,
    backgroundColor: '#f7fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  description: {
    fontSize: 14,
    color: '#4a5568',
    fontStyle: 'italic',
  },
  mechanicWarning: {
    backgroundColor: '#fed7d7',
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  mechanicTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#c53030',
  },
  mechanicTimer: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#c53030',
  },
  tipsSection: { padding: 16 },
  tipsHeader: {
    fontSize: 12,
    fontWeight: '600',
    color: '#718096',
    marginBottom: 8,
  },
  tip: {
    fontSize: 12,
    color: '#4a5568',
    marginBottom: 4,
    lineHeight: 18,
  },
});
