import type { Achievement } from './types';

export const STUDY_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'achievement-first-study-plan',
    title: 'Study Planner',
    description: 'Create your first AI study plan',
    category: 'STUDY',
    rarity: 'COMMON',
    icon: '📚',
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: 'STUDY_PLAN_CREATE',
      target: 1,
      comparator: 'GREATER_THAN',
    },
    reward: { coins: 100, xp: 200 },
    pointValue: 10,
    shareText: 'First study plan created! Let the learning begin 📚',
    unlockRate: 0.7,
  },
  {
    id: 'achievement-plan-complete-5',
    title: 'Plan Finisher',
    description: 'Complete 5 AI study plans',
    category: 'STUDY',
    rarity: 'UNCOMMON',
    icon: '✅',
    isHidden: false,
    progressMax: 5,
    unlockCondition: {
      type: 'STUDY_PLAN_COMPLETE',
      target: 5,
      comparator: 'CUMULATIVE',
    },
    reward: { coins: 300, xp: 600, badge: 'Plan Finisher' },
    pointValue: 25,
    shareText: '5 study plans conquered! Plan Finisher ✅',
    unlockRate: 0.3,
  },
  {
    id: 'achievement-cards-mastered-50',
    title: 'Flashcard Master',
    description: 'Master 50 flashcards (100% recall)',
    category: 'STUDY',
    rarity: 'RARE',
    icon: '🧠',
    isHidden: false,
    progressMax: 50,
    unlockCondition: {
      type: 'FLASHCARD_MASTER',
      target: 50,
      comparator: 'CUMULATIVE',
    },
    reward: { coins: 500, xp: 1000, badge: 'Flashcard Master' },
    pointValue: 40,
    shareText: '50 cards mastered! Knowledge absorbed 🧠',
    unlockRate: 0.15,
  },
  {
    id: 'achievement-study-streak-7',
    title: 'Study Streaker',
    description: 'Study 7 days in a row using AI plans',
    category: 'STUDY',
    rarity: 'UNCOMMON',
    icon: '📖',
    isHidden: false,
    progressMax: 7,
    unlockCondition: {
      type: 'STUDY_STREAK',
      target: 7,
      comparator: 'GREATER_THAN',
    },
    reward: { coins: 400, xp: 800, badge: 'Study Streaker' },
    pointValue: 30,
    shareText: '7 days of focused studying! Study Streaker 📖',
    unlockRate: 0.25,
  },
  {
    id: 'achievement-perfect-plan',
    title: 'Perfect Student',
    description: 'Complete a study plan with 100% task completion',
    category: 'STUDY',
    rarity: 'RARE',
    icon: '💯',
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: 'STUDY_PLAN_PERFECT',
      target: 1,
      comparator: 'GREATER_THAN',
    },
    reward: { coins: 600, xp: 1200, badge: 'Perfect Student' },
    pointValue: 50,
    shareText: 'Perfect plan completion! Every task done 💯',
    unlockRate: 0.1,
  },
  {
    id: 'achievement-topics-conquered-10',
    title: 'Topic Conqueror',
    description: 'Master 10 different study topics',
    category: 'STUDY',
    rarity: 'EPIC',
    icon: '🎓',
    isHidden: false,
    progressMax: 10,
    unlockCondition: {
      type: 'TOPIC_MASTER',
      target: 10,
      comparator: 'CUMULATIVE',
    },
    reward: {
      coins: 1000,
      xp: 2000,
      badge: 'Topic Conqueror',
      cosmetic: 'scholar-aura',
    },
    pointValue: 75,
    shareText: '10 topics mastered! Scholar status achieved 🎓',
    unlockRate: 0.05,
  },
];
