/**
 * Boss Achievements (8)
 *
 * Achievements related to defeating bosses.
 */

import type { Achievement } from "../types";
import { RARITY_CONFIG } from "./rarity-config";

export const BOSS_ACHIEVEMENTS: Achievement[] = [
  {
    id: "boss-first",
    title: "Boss Slayer",
    description: "Defeat your first boss",
    category: "BOSS",
    rarity: "UNCOMMON",
    icon: "⚔️",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "BOSS_DEFEAT",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 200, xp: 400, badge: "Slayer" },
    shareText: "My first boss down! The journey begins ⚔️",
    unlockRate: 0.7,
  },
  {
    id: "boss-solo",
    title: "Solo Slayer",
    description: "Defeat a boss without squad help",
    category: "BOSS",
    rarity: "RARE",
    icon: "🥷",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "BOSS_SOLO_DEFEAT",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 400, xp: 800, badge: "Solo" },
    shareText: "Solo boss kill! No help needed 🥷",
    unlockRate: 0.4,
  },
  {
    id: "boss-all-6",
    title: "Boss Collector",
    description: "Defeat all 6 bosses",
    category: "BOSS",
    rarity: "EPIC",
    icon: "👹",
    isHidden: false,
    progressMax: 6,
    unlockCondition: {
      type: "BOSS_DEFEAT_ALL",
      target: 6,
      comparator: "EQUALS",
    },
    pointValue: RARITY_CONFIG.EPIC.points,
    reward: { coins: 2000, xp: 4000, title: "Boss Hunter" },
    shareText: "ALL BOSSES DEFEATED! I am the apex predator 👹",
    unlockRate: 0.08,
  },
  {
    id: "boss-10000-damage",
    title: "Damage Dealer",
    description: "Deal 10,000 total damage to bosses",
    category: "BOSS",
    rarity: "RARE",
    icon: "💥",
    isHidden: false,
    progressMax: 10000,
    unlockCondition: {
      type: "BOSS_DAMAGE_CUMULATIVE",
      target: 10000,
      comparator: "CUMULATIVE",
    },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 500, xp: 1000, badge: "Dealer" },
    shareText: "10,000 damage dealt! I bring the pain 💥",
    unlockRate: 0.25,
  },
  {
    id: "boss-critical",
    title: "Critical Striker",
    description: "Land a critical hit on a boss",
    category: "BOSS",
    rarity: "UNCOMMON",
    icon: "⚡",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "BOSS_CRITICAL_HIT",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 150, xp: 300 },
    shareText: "CRITICAL HIT! Maximum damage ⚡",
    unlockRate: 0.55,
  },
  {
    id: "boss-24h-clutch",
    title: "Clutch Defeat",
    description: "Defeat a boss with less than 24 hours remaining",
    category: "BOSS",
    rarity: "RARE",
    icon: "⏰",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "BOSS_CLUTCH_DEFEAT",
      target: 1,
      comparator: "GREATER_THAN",
      context: { hoursRemaining: 24 },
    },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 600, xp: 1200, badge: "Clutch" },
    shareText: "Clutched that boss with hours to spare! ⏰",
    unlockRate: 0.2,
  },
  {
    id: "boss-perfect-session",
    title: "Flawless Victory",
    description: "Defeat a boss with a perfect S-grade session",
    category: "BOSS",
    rarity: "EPIC",
    icon: "✨",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "BOSS_DEFEAT_PERFECT",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.EPIC.points,
    reward: { coins: 1000, xp: 2000, badge: "Flawless" },
    shareText: "Perfect session, perfect boss kill! Flawless ✨",
    unlockRate: 0.12,
  },
  {
    id: "boss-squad",
    title: "Squad Victory",
    description: "Participate in defeating a boss with your squad",
    category: "BOSS",
    rarity: "UNCOMMON",
    icon: "🛡️",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "BOSS_SQUAD_DEFEAT",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 250, xp: 500 },
    shareText: "Squad boss kill! We did it together 🛡️",
    unlockRate: 0.45,
  },
];
