/**
 * Progression Achievements (7)
 *
 * Achievements related to leveling and progression.
 */

import type { Achievement } from "../types";
import { RARITY_CONFIG } from "./rarity-config";

export const PROGRESSION_ACHIEVEMENTS: Achievement[] = [
  {
    id: "prog-level-5",
    title: "Level 5",
    description: "Reach level 5",
    category: "PROGRESSION",
    rarity: "COMMON",
    icon: "🔰",
    isHidden: false,
    progressMax: 5,
    unlockCondition: {
      type: "LEVEL_REACH",
      target: 5,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.COMMON.points,
    reward: { coins: 100, xp: 200 },
    shareText: "Level 5! Just getting started 🔰",
    unlockRate: 0.9,
  },
  {
    id: "prog-level-10",
    title: "Level 10",
    description: "Reach level 10",
    category: "PROGRESSION",
    rarity: "UNCOMMON",
    icon: "🔹",
    isHidden: false,
    progressMax: 10,
    unlockCondition: {
      type: "LEVEL_REACH",
      target: 10,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 200, xp: 400 },
    shareText: "Level 10! Double digits 🔹",
    unlockRate: 0.75,
  },
  {
    id: "prog-level-20",
    title: "Level 20",
    description: "Reach level 20",
    category: "PROGRESSION",
    rarity: "RARE",
    icon: "🔷",
    isHidden: false,
    progressMax: 20,
    unlockCondition: {
      type: "LEVEL_REACH",
      target: 20,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 400, xp: 800, badge: "Level 20" },
    shareText: "Level 20! A fifth of the way to 100 🔷",
    unlockRate: 0.5,
  },
  {
    id: "prog-level-50",
    title: "Level 50",
    description: "Reach level 50",
    category: "PROGRESSION",
    rarity: "EPIC",
    icon: "💠",
    isHidden: false,
    progressMax: 50,
    unlockCondition: {
      type: "LEVEL_REACH",
      target: 50,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.EPIC.points,
    reward: { coins: 1000, xp: 2000, title: "Veteran" },
    shareText: "Level 50! Half century milestone 💠",
    unlockRate: 0.2,
  },
  {
    id: "prog-first-tier",
    title: "Tier Unlock",
    description: "Unlock your first progression tier",
    category: "PROGRESSION",
    rarity: "UNCOMMON",
    icon: "📈",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "TIER_UNLOCK",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 250, xp: 500 },
    shareText: "Unlocked my first tier! Progress feels good 📈",
    unlockRate: 0.7,
  },
  {
    id: "prog-bp-tier-25",
    title: "Battle Pass Master",
    description: "Reach tier 25 in battle pass",
    category: "PROGRESSION",
    rarity: "RARE",
    icon: "🎫",
    isHidden: false,
    progressMax: 25,
    unlockCondition: {
      type: "BATTLE_PASS_TIER",
      target: 25,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 500, xp: 1000, badge: "BP Master" },
    shareText: "Battle Pass tier 25! Halfway to max 🎫",
    unlockRate: 0.3,
  },
  {
    id: "prog-first-prestige",
    title: "Prestige",
    description: "Complete your first prestige",
    category: "PROGRESSION",
    rarity: "LEGENDARY",
    icon: "✨",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "PRESTIGE",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.LEGENDARY.points,
    reward: { coins: 5000, xp: 10000, title: "Prestiged" },
    shareText: "PRESTIGE! I am reborn stronger ✨",
    unlockRate: 0.05,
  },
];
