import type { Achievement } from "../types";
import { RARITY_CONFIG } from "./rarity-config";

export const SESSION_MILESTONE_ACHIEVEMENTS: Achievement[] = [
  {
    id: "session-first",
    title: "First Steps",
    description: "Complete your first focus session",
    category: "SESSION",
    rarity: "COMMON",
    icon: "🌱",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "SESSION_COMPLETE",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.COMMON.points,
    reward: { coins: 50, xp: 100 },
    shareText: "I just started my focus journey! 🌱",
    unlockRate: 0.95,
  },
  {
    id: "session-10",
    title: "Getting Started",
    description: "Complete 10 focus sessions",
    category: "SESSION",
    rarity: "COMMON",
    icon: "🎯",
    isHidden: false,
    progressMax: 10,
    unlockCondition: {
      type: "SESSION_COMPLETE",
      target: 10,
      comparator: "CUMULATIVE",
    },
    pointValue: RARITY_CONFIG.COMMON.points,
    reward: { coins: 100, xp: 200 },
    shareText: "10 sessions complete! Building momentum 🎯",
    unlockRate: 0.75,
  },
  {
    id: "session-50",
    title: "Focus Regular",
    description: "Complete 50 focus sessions",
    category: "SESSION",
    rarity: "UNCOMMON",
    icon: "📚",
    isHidden: false,
    progressMax: 50,
    unlockCondition: {
      type: "SESSION_COMPLETE",
      target: 50,
      comparator: "CUMULATIVE",
    },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 250, xp: 500, badge: "Regular" },
    shareText: "50 sessions! I'm a focus machine 📚",
    unlockRate: 0.45,
  },
  {
    id: "session-100",
    title: "Centurion",
    description: "Complete 100 focus sessions",
    category: "SESSION",
    rarity: "RARE",
    icon: "💯",
    isHidden: false,
    progressMax: 100,
    unlockCondition: {
      type: "SESSION_COMPLETE",
      target: 100,
      comparator: "CUMULATIVE",
    },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 500, xp: 1000, badge: "Centurion" },
    shareText: "100 sessions! Triple digits baby! 💯",
    unlockRate: 0.25,
  },
  {
    id: "session-500",
    title: "Session Master",
    description: "Complete 500 focus sessions",
    category: "SESSION",
    rarity: "EPIC",
    icon: "👑",
    isHidden: false,
    progressMax: 500,
    unlockCondition: {
      type: "SESSION_COMPLETE",
      target: 500,
      comparator: "CUMULATIVE",
    },
    pointValue: RARITY_CONFIG.EPIC.points,
    reward: { coins: 2000, xp: 5000, title: "Master" },
    shareText: "500 sessions! Absolute legend status 👑",
    unlockRate: 0.05,
  },
  {
    id: "session-first-s-grade",
    title: "Perfect Focus",
    description: "Achieve your first S-grade session",
    category: "SESSION",
    rarity: "UNCOMMON",
    icon: "⭐",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "S_GRADE_SESSION",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 150, xp: 300, badge: "Perfect" },
    shareText: "My first perfect session! Flawless focus ⭐",
    unlockRate: 0.6,
  },
  {
    id: "session-10-perfect",
    title: "Perfectionist",
    description: "Complete 10 perfect (S-grade) sessions",
    category: "SESSION",
    rarity: "RARE",
    icon: "🌟",
    isHidden: false,
    progressMax: 10,
    unlockCondition: {
      type: "PERFECT_SESSION",
      target: 10,
      comparator: "CUMULATIVE",
    },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 500, xp: 1000, badge: "Perfectionist" },
    shareText: "10 perfect sessions! I don't miss 🌟",
    unlockRate: 0.2,
  },
];
