/**
 * Social Achievements (7)
 *
 * Achievements related to social interactions and squads.
 */

import type { Achievement } from '../types';
import { RARITY_CONFIG } from './rarity-config';

export const SOCIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'social-join-squad',
    title: 'Squad Member',
    description: 'Join a squad',
    category: 'SOCIAL',
    rarity: 'COMMON',
    icon: '👥',
    isHidden: false,
    progressMax: 1,
    unlockCondition: { type: 'SQUAD_JOIN', target: 1, comparator: 'GREATER_THAN' },
    pointValue: RARITY_CONFIG.COMMON.points,
    reward: { coins: 100, xp: 200 },
    shareText: 'Joined my first squad! Together we rise 👥',
    unlockRate: 0.65,
  },
  {
    id: 'social-create-squad',
    title: 'Squad Leader',
    description: 'Create your own squad',
    category: 'SOCIAL',
    rarity: 'UNCOMMON',
    icon: '🎖️',
    isHidden: false,
    progressMax: 1,
    unlockCondition: { type: 'SQUAD_CREATE', target: 1, comparator: 'GREATER_THAN' },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 300, xp: 600, badge: 'Leader' },
    shareText: 'Created my own squad! Who\'s joining me? 🎖️',
    unlockRate: 0.30,
  },
  {
    id: 'social-invite-join',
    title: 'Recruiter',
    description: 'Invite a friend who joins the app',
    category: 'SOCIAL',
    rarity: 'UNCOMMON',
    icon: '📢',
    isHidden: false,
    progressMax: 1,
    unlockCondition: { type: 'FRIEND_RECRUIT', target: 1, comparator: 'GREATER_THAN' },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 400, xp: 800, badge: 'Recruiter' },
    shareText: 'Recruited a friend! The squad grows 📢',
    unlockRate: 0.25,
  },
  {
    id: 'social-win-duel',
    title: 'Duel Victor',
    description: 'Win a duel against another player',
    category: 'SOCIAL',
    rarity: 'RARE',
    icon: '⚔️',
    isHidden: false,
    progressMax: 1,
    unlockCondition: { type: 'DUEL_WIN', target: 1, comparator: 'GREATER_THAN' },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 300, xp: 600 },
    shareText: 'Won my first duel! I accept all challengers ⚔️',
    unlockRate: 0.35,
  },
  {
    id: 'social-beat-rival',
    title: 'Rival Conquered',
    description: 'Beat your rival in a competition',
    category: 'SOCIAL',
    rarity: 'RARE',
    icon: '🏆',
    isHidden: false,
    progressMax: 1,
    unlockCondition: { type: 'RIVAL_BEAT', target: 1, comparator: 'GREATER_THAN' },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 500, xp: 1000, badge: 'Conqueror' },
    shareText: 'My rival has been defeated! I am supreme 🏆',
    unlockRate: 0.20,
  },
  {
    id: 'social-war-win',
    title: 'War Hero',
    description: 'Win a squad war',
    category: 'SOCIAL',
    rarity: 'EPIC',
    icon: '🏴',
    isHidden: false,
    progressMax: 1,
    unlockCondition: { type: 'SQUAD_WAR_WIN', target: 1, comparator: 'GREATER_THAN' },
    pointValue: RARITY_CONFIG.EPIC.points,
    reward: { coins: 800, xp: 1600, badge: 'War Hero' },
    shareText: 'Squad war victory! We are unstoppable 🏴',
    unlockRate: 0.15,
  },
  {
    id: 'social-squad-level-5',
    title: 'Elite Squad',
    description: 'Reach squad level 5',
    category: 'SOCIAL',
    rarity: 'RARE',
    icon: '⭐',
    isHidden: false,
    progressMax: 5,
    unlockCondition: { type: 'SQUAD_LEVEL', target: 5, comparator: 'GREATER_THAN' },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 600, xp: 1200 },
    shareText: 'Squad level 5! We\'re elite ⭐',
    unlockRate: 0.18,
  },
];
