import type { Achievement } from "../types";
import { RARITY_CONFIG } from "./rarity-config";

export const STREAK_ACHIEVEMENTS_ADVANCED: Achievement[] = [
  {
    id: "streak-100",
    title: "Century Streak",
    description: "Maintain a 100-day streak",
    category: "STREAK",
    rarity: "LEGENDARY",
    icon: "🏆",
    isHidden: false,
    progressMax: 100,
    unlockCondition: {
      type: "STREAK_DAYS",
      target: 100,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.LEGENDARY.points,
    reward: {
      coins: 5000,
      xp: 10000,
      title: "Centurion",
      cosmetic: "century-flame",
    },
    shareText: "100 DAY STREAK! I AM IMMORTAL 🏆",
    unlockRate: 0.01,
  },
  {
    id: "streak-180",
    title: "Half-Year Hero",
    description: "Maintain a 180-day streak",
    category: "STREAK",
    rarity: "LEGENDARY",
    icon: "🌟",
    isHidden: false,
    progressMax: 180,
    unlockCondition: {
      type: "STREAK_DAYS",
      target: 180,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.LEGENDARY.points,
    reward: { coins: 10000, xp: 20000, title: "Immortal" },
    shareText: "Half a year of pure dedication! 🌟",
    unlockRate: 0.005,
  },
  {
    id: "streak-365",
    title: "Year of Focus",
    description: "Maintain a 365-day streak",
    category: "STREAK",
    rarity: "LEGENDARY",
    icon: "👑👑",
    isHidden: false,
    progressMax: 365,
    unlockCondition: {
      type: "STREAK_DAYS",
      target: 365,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.LEGENDARY.points,
    reward: {
      coins: 25000,
      xp: 50000,
      title: "God of Focus",
      cosmetic: "year-aura",
    },
    shareText: "A FULL YEAR! This is my life now 👑👑",
    unlockRate: 0.001,
  },
  {
    id: "streak-phoenix",
    title: "Phoenix Rising",
    description: "Recover your streak after it breaks",
    category: "STREAK",
    rarity: "UNCOMMON",
    icon: "🐦‍🔥",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "STREAK_RECOVER",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 150, xp: 300 },
    shareText: "Risen from the ashes! Streak recovered 🐦‍🔥",
    unlockRate: 0.45,
  },
  {
    id: "streak-weekend-warrior",
    title: "Weekend Warrior",
    description: "Maintain streak through Saturday and Sunday",
    category: "STREAK",
    rarity: "UNCOMMON",
    icon: "🌴",
    isHidden: false,
    progressMax: 1,
    unlockCondition: {
      type: "WEEKEND_STREAK",
      target: 1,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 200, xp: 400 },
    shareText: "Weekend? Still focused. No days off 🌴",
    unlockRate: 0.5,
  },
];
