import type { Achievement } from "../types";
import { RARITY_CONFIG } from "./rarity-config";

export const STREAK_ACHIEVEMENTS_CORE: Achievement[] = [
  {
    id: "streak-3",
    title: "3-Day Streak",
    description: "Maintain a 3-day streak",
    category: "STREAK",
    rarity: "COMMON",
    icon: "🔥",
    isHidden: false,
    progressMax: 3,
    unlockCondition: {
      type: "STREAK_DAYS",
      target: 3,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.COMMON.points,
    reward: { coins: 75, xp: 150 },
    shareText: "3 days in a row! Streak started 🔥",
    unlockRate: 0.85,
  },
  {
    id: "streak-7",
    title: "Week Warrior",
    description: "Maintain a 7-day streak",
    category: "STREAK",
    rarity: "UNCOMMON",
    icon: "🔥🔥",
    isHidden: false,
    progressMax: 7,
    unlockCondition: {
      type: "STREAK_DAYS",
      target: 7,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.UNCOMMON.points,
    reward: { coins: 200, xp: 400, badge: "Week Warrior" },
    shareText: "Full week streak! Unstoppable 🔥🔥",
    unlockRate: 0.6,
  },
  {
    id: "streak-14",
    title: "Fortnight Champion",
    description: "Maintain a 14-day streak",
    category: "STREAK",
    rarity: "RARE",
    icon: "🔥🔥🔥",
    isHidden: false,
    progressMax: 14,
    unlockCondition: {
      type: "STREAK_DAYS",
      target: 14,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.RARE.points,
    reward: { coins: 400, xp: 800, badge: "Fortnight" },
    shareText: "Two weeks! I am the streak 🔥🔥🔥",
    unlockRate: 0.35,
  },
  {
    id: "streak-30",
    title: "Monthly Master",
    description: "Maintain a 30-day streak",
    category: "STREAK",
    rarity: "EPIC",
    icon: "👑",
    isHidden: false,
    progressMax: 30,
    unlockCondition: {
      type: "STREAK_DAYS",
      target: 30,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.EPIC.points,
    reward: { coins: 1000, xp: 2000, title: "Monthly Master" },
    shareText: "30 days! A whole month of focus 👑",
    unlockRate: 0.15,
  },
  {
    id: "streak-60",
    title: "Double Century",
    description: "Maintain a 60-day streak",
    category: "STREAK",
    rarity: "EPIC",
    icon: "💎",
    isHidden: false,
    progressMax: 60,
    unlockCondition: {
      type: "STREAK_DAYS",
      target: 60,
      comparator: "GREATER_THAN",
    },
    pointValue: RARITY_CONFIG.EPIC.points,
    reward: { coins: 2000, xp: 4000, title: "Unstoppable" },
    shareText: "60 days! Legendary dedication 💎",
    unlockRate: 0.05,
  },
];
