import { eventBus } from "../../events"; import { launchColors } from "@theme/tokens/launch-colors";
export type OnboardingStep = "WELCOME" | "QUICK_START" | "FIRST_SESSION" | "POST_SESSION" | "HOME_INTRO" | "FEATURE_UNLOCK" | "COMPLETE";
export interface OnboardingState { userId: string; currentStep: OnboardingStep; sessionsCompleted: number; firstSessionAt: number | null; skippedCustomization: boolean; completedAt: number | null; unlockedFeatures: UnlockedFeature[]; nextFeatureUnlock: FeatureUnlockGate | null; preferences: Partial<UserPreferences>; }
export interface UserPreferences { focusDuration: number; notificationsEnabled: boolean; primaryGoal: string; interestedFeatures: string[]; }
export interface UnlockedFeature { featureId: string; featureName: string; unlockedAt: number; introduced: boolean; }
export interface FeatureUnlockGate { featureId: string; featureName: string; description: string; requiresSessions: number; icon: string; color: string; }
export const FEATURE_UNLOCK_GATES: FeatureUnlockGate[] = [ { featureId: "boss_battles", featureName: "Boss Battles", description: "Defeat bosses representing your productivity challenges", requiresSessions: 4, icon: "⚔️", color: launchColors.hex_e53e3e, }, { featureId: "ai_study_plans", featureName: "AI Study Plans", description: "AI-generated study plans for any topic you want to learn", requiresSessions: 5, icon: "📚", color: launchColors.hex_4299e1, }, { featureId: "squads", featureName: "Squads", description: "Join accountability groups and tackle challenges together", requiresSessions: 7, icon: "👥", color: launchColors.hex_48bb78, }, { featureId: "advanced_analytics", featureName: "Study Analytics", description: "Track your progress and optimize your learning patterns", requiresSessions: 10, icon: "📊", color: launchColors.hex_9f7aea, }, { featureId: "streak_protection", featureName: "Streak Protection", description: "Protect your streak with insurance when life gets busy", requiresSessions: 14, icon: "🛡️", color: launchColors.hex_ed8936, }, { featureId: "coach_personality", featureName: "Coach Personality", description: "Choose your AI coach personality: Mentor, Trainer, Peer, or Professor", requiresSessions: 20, icon: "🤖", color: launchColors.hex_38b2ac, }, ];
const onboardingStates = new Map<string, OnboardingState>();
export function initializeOnboarding(userId: string): OnboardingState { const state: OnboardingState = { userId, currentStep: "WELCOME", sessionsCompleted: 0, firstSessionAt: null, skippedCustomization: false, completedAt: null, unlockedFeatures: [], nextFeatureUnlock: FEATURE_UNLOCK_GATES[0] ?? null, preferences: { focusDuration: 15, notificationsEnabled: true, }, }; onboardingStates.set(userId, state); eventBus.publish("onboarding:started", { userId }); return state; }
export function getOnboardingState(userId: string): OnboardingState | null { return onboardingStates.get(userId) || null; }
export function advanceStep(userId: string): OnboardingState | null { const state = onboardingStates.get(userId); if (!state) { return null; } const stepOrder: OnboardingStep[] = ["WELCOME", "QUICK_START", "FIRST_SESSION", "POST_SESSION", "HOME_INTRO", "FEATURE_UNLOCK", "COMPLETE"]; const currentIndex = stepOrder.indexOf(state.currentStep); if (currentIndex < stepOrder.length - 1) { state.currentStep = stepOrder[currentIndex + 1]!; } if (state.currentStep === "COMPLETE") { state.completedAt = Date.now(); eventBus.publish("onboarding:completed", { userId }); } else { eventBus.publish("onboarding:step_changed", { userId, step: state.currentStep, }); } return state; }
export function skipToFirstSession(userId: string): OnboardingState | null { const state = onboardingStates.get(userId); if (!state) { return null; } state.skippedCustomization = true; state.currentStep = "FIRST_SESSION"; eventBus.publish("onboarding:skipped", { userId, step: "CUSTOMIZATION", timestamp: Date.now(), }); return state; }
export function recordSession(userId: string, durationMinutes: number): OnboardingState | null { const state = onboardingStates.get(userId); if (!state) { return null; } state.sessionsCompleted += 1; if (!state.firstSessionAt) { state.firstSessionAt = Date.now(); state.currentStep = "POST_SESSION"; eventBus.publish("onboarding:first_session_complete", { userId, durationMinutes, }); } checkFeatureUnlocks(state); return state; }
function checkFeatureUnlocks(state: OnboardingState): void { for (const gate of FEATURE_UNLOCK_GATES) { if (state.unlockedFeatures.some((f) => f.featureId === gate.featureId)) { continue; } if (state.sessionsCompleted >= gate.requiresSessions) { const unlocked: UnlockedFeature = { featureId: gate.featureId, featureName: gate.featureName, unlockedAt: Date.now(), introduced: false, }; state.unlockedFeatures.push(unlocked); const nextIndex = FEATURE_UNLOCK_GATES.findIndex((g) => g.featureId === gate.featureId) + 1; state.nextFeatureUnlock = nextIndex < FEATURE_UNLOCK_GATES.length ? (FEATURE_UNLOCK_GATES[nextIndex] ?? null) : null; eventBus.publish("onboarding:feature_unlocked", { userId: state.userId, feature: gate.featureId, featureId: gate.featureId, timestamp: Date.now(), }); } } }
export function markFeatureIntroduced(userId: string, featureId: string): void { const state = onboardingStates.get(userId); if (!state) { return; } const feature = state.unlockedFeatures.find((f) => f.featureId === featureId); if (feature) { feature.introduced = true; } }
export interface StepContent { step: OnboardingStep; title: string; subtitle: string; primaryAction: string; secondaryAction?: string; showSkip?: boolean; content: string; }
export const STEP_CONTENT: Record<OnboardingStep, StepContent> = { WELCOME: { step: "WELCOME", title: "Welcome to Focus", subtitle: "Your journey to better productivity starts here", primaryAction: "Let's Get Started", secondaryAction: "Skip Tutorial", showSkip: true, content: "We help you build focus habits through engaging sessions, boss battles, and study plans. Ready to focus?", }, QUICK_START: { step: "QUICK_START", title: "Quick Start", subtitle: "How would you like to begin?", primaryAction: "Start 15-min Session", secondaryAction: "Customize First", showSkip: false, content: "You can jump right into a 15-minute focus session, or customize your experience first. What feels right?", }, FIRST_SESSION: { step: "FIRST_SESSION", title: "Your First Session", subtitle: "15 minutes of focused work", primaryAction: "Start Focusing", showSkip: false, content: "Pick one task to focus on. We will guide you through 15 minutes of distraction-free work. You have got this!", }, POST_SESSION: { step: "POST_SESSION", title: "Great Job! 🎉", subtitle: "You completed your first session", primaryAction: "Set a Goal", secondaryAction: "Explore Home", showSkip: true, content: "That is one session toward building your focus habit. Want to set a goal, or explore what is next?", }, HOME_INTRO: { step: "HOME_INTRO", title: "Your Home Screen", subtitle: "Everything you need, right here", primaryAction: "Got It", showSkip: false, content: "Your Home shows personalized recommendations based on your activity. The AI Coach suggests what to focus on next.", }, FEATURE_UNLOCK: { step: "FEATURE_UNLOCK", title: "New Feature Unlocked!", subtitle: "Check out what is new", primaryAction: "Try It Out", secondaryAction: "Later", showSkip: true, content: "New features unlock as you build your focus habit. Keep going to discover more!", }, COMPLETE: { step: "COMPLETE", title: "You are All Set!", subtitle: "Welcome to the community", primaryAction: "Start Focusing", showSkip: false, content: "You have completed onboarding. Your focus journey continues from here.", }, };
export function getStepContent(state: OnboardingState): StepContent { const content = STEP_CONTENT[state.currentStep]; if (state.currentStep === "FEATURE_UNLOCK" && state.unlockedFeatures.length > 0) { const latest = state.unlockedFeatures[state.unlockedFeatures.length - 1]!; const gate = FEATURE_UNLOCK_GATES.find((g) => g.featureId === latest.featureId); if (gate) { return { ...content,
        title: `${gate.icon} ${gate.featureName} Unlocked!`,
subtitle: gate.description, }; } } return content; }
export interface OnboardingProgress { stepNumber: number; totalSteps: number; percentComplete: number; currentStep: OnboardingStep; sessionsToNextFeature: number | null; nextFeatureName: string | null; }
export function getOnboardingProgress(userId: string): OnboardingProgress | null { const state = onboardingStates.get(userId); if (!state) { return null; } const stepOrder: OnboardingStep[] = ["WELCOME", "QUICK_START", "FIRST_SESSION", "POST_SESSION", "HOME_INTRO", "FEATURE_UNLOCK", "COMPLETE"]; const currentIndex = stepOrder.indexOf(state.currentStep); const totalSteps = stepOrder.length; let sessionsToNext: number | null = null; let nextFeature: string | null = null; if (state.nextFeatureUnlock) { sessionsToNext = state.nextFeatureUnlock.requiresSessions - state.sessionsCompleted; nextFeature = state.nextFeatureUnlock.featureName; } return { stepNumber: currentIndex + 1, totalSteps, percentComplete: Math.round(((currentIndex + 1) / totalSteps) * 100), currentStep: state.currentStep, sessionsToNextFeature: sessionsToNext, nextFeatureName: nextFeature, }; }
export function shouldShowOnboarding(userId: string): boolean { const state = onboardingStates.get(userId); if (!state) { return true; } if (state.completedAt) { return false; } const unintroduced = state.unlockedFeatures.filter((f) => !f.introduced); if (unintroduced.length > 0) { state.currentStep = "FEATURE_UNLOCK"; return true; } return true; }
export function isFeatureAvailable(userId: string, featureId: string, defaultAvailable: boolean = false): boolean { const state = onboardingStates.get(userId); if (!state) { return defaultAvailable; } return state.unlockedFeatures.some((f) => f.featureId === featureId); }
export function getAvailableFeatures(userId: string): UnlockedFeature[] { const state = onboardingStates.get(userId); if (!state) { return []; } return state.unlockedFeatures; }
export function getNextFeatureUnlock(userId: string): FeatureUnlockGate | null { const state = onboardingStates.get(userId); if (!state) { return FEATURE_UNLOCK_GATES[0] ?? null; } return state.nextFeatureUnlock; }
