/**
 * Personal challenge bank — social, boss combat, and time-of-day challenges.
 */

import type { ChallengeBankTemplate } from './challenge-bank-types';

export const SOCIAL_COMBAT_CHALLENGES: ChallengeBankTemplate[] = [
  {
    id: 'challenge-squad-sync',
    name: 'Squad Sync',
    description: 'Complete a session at the same time as a squad member',
    type: 'SOCIAL',
    difficulty: 'EASY',
    target: 1,
    timeLimit: 7 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 75,
    tags: ['squad', 'social', 'together'],
    seasonal: false,
  },
  {
    id: 'challenge-squad-warrior',
    name: 'Squad War Contributor',
    description:
      'Contribute {{target}} focus minutes to your squad during an active war',
    type: 'FOCUS_TIME',
    difficulty: 'NORMAL',
    target: 120,
    timeLimit: 7 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 150,
    tags: ['squad-war', 'team', 'competitive'],
    seasonal: false,
  },
  {
    id: 'challenge-recruit-friend',
    name: 'Focus Ambassador',
    description: 'Recruit a friend to complete their first session',
    type: 'SOCIAL',
    difficulty: 'NORMAL',
    target: 1,
    timeLimit: 30 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 200,
    tags: ['recruit', 'social', 'growth'],
    seasonal: false,
  },
  {
    id: 'challenge-boss-berserker',
    name: 'Boss Berserker',
    description: 'Deal {{target}} damage to any boss in a single session',
    type: 'BOSS_DAMAGE',
    difficulty: 'CHALLENGING',
    target: 500,
    timeLimit: 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 125,
    tags: ['boss', 'damage', 'combat'],
    seasonal: false,
  },
  {
    id: 'challenge-multi-boss',
    name: 'Boss Slayer',
    description: 'Defeat {{target}} different bosses this week',
    type: 'BOSS_DAMAGE',
    difficulty: 'PUSH',
    target: 3,
    timeLimit: 7 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 250,
    tags: ['boss', 'multiple', 'weekly'],
    seasonal: false,
  },
  {
    id: 'challenge-evening-wind-down',
    name: 'Evening Wind-Down',
    description: 'Complete {{target}} sessions between 6 PM and 10 PM',
    type: 'SESSION_COUNT',
    difficulty: 'EASY',
    target: 2,
    timeLimit: 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 50,
    tags: ['evening', 'routine', 'wind-down'],
    seasonal: false,
  },
  {
    id: 'challenge-night-owl',
    name: 'Night Owl',
    description: 'Focus for {{target}} minutes after 10 PM',
    type: 'FOCUS_TIME',
    difficulty: 'NORMAL',
    target: 45,
    timeLimit: 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 75,
    tags: ['night', 'late', 'owl'],
    seasonal: false,
  },
  {
    id: 'challenge-weekend-warrior',
    name: 'Weekend Warrior',
    description: 'Complete {{target}} sessions on Saturday and Sunday combined',
    type: 'SESSION_COUNT',
    difficulty: 'NORMAL',
    target: 4,
    timeLimit: 2 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 100,
    tags: ['weekend', 'warrior', 'off-day'],
    seasonal: false,
  },
  {
    id: 'challenge-sunday-prep',
    name: 'Sunday Prep',
    description:
      'Focus for {{target}} minutes on Sunday to prepare for the week',
    type: 'FOCUS_TIME',
    difficulty: 'EASY',
    target: 60,
    timeLimit: 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 75,
    tags: ['sunday', 'prep', 'planning'],
    seasonal: false,
  },
];
