/**
 * Seasonal challenge bank — time-limited seasonal challenges.
 */

import type { ChallengeBankTemplate } from './challenge-bank-types';

export const SEASONAL_CHALLENGES: ChallengeBankTemplate[] = [
  {
    id: 'challenge-new-year-resolution',
    name: 'Resolution Starter',
    description: 'Complete {{target}} sessions in the first week of January',
    type: 'SESSION_COUNT',
    difficulty: 'NORMAL',
    target: 7,
    timeLimit: 7 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 150,
    tags: ['new-year', 'january', 'resolution'],
    seasonal: true,
    seasonWindow: { startMonth: 0, endMonth: 0 },
  },
  {
    id: 'challenge-focus-buddy',
    name: 'Focus Buddy',
    description: 'Complete {{target}} sessions with a friend this February',
    type: 'SOCIAL',
    difficulty: 'NORMAL',
    target: 5,
    timeLimit: 28 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 125,
    tags: ['february', 'social', 'valentine'],
    seasonal: true,
    seasonWindow: { startMonth: 1, endMonth: 1 },
  },
  {
    id: 'challenge-spring-cleaning',
    name: 'Mental Spring Cleaning',
    description: 'Clear your mind with {{target}} hours of focus this spring',
    type: 'FOCUS_TIME',
    difficulty: 'NORMAL',
    target: 600,
    timeLimit: 30 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 200,
    tags: ['spring', 'cleaning', 'renewal'],
    seasonal: true,
    seasonWindow: { startMonth: 2, endMonth: 4 },
  },
  {
    id: 'challenge-summer-heat',
    name: 'Summer Heat',
    description: 'Stay focused despite the heat: {{target}} sessions in July',
    type: 'SESSION_COUNT',
    difficulty: 'CHALLENGING',
    target: 20,
    timeLimit: 31 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 250,
    tags: ['summer', 'july', 'heat'],
    seasonal: true,
    seasonWindow: { startMonth: 6, endMonth: 6 },
  },
  {
    id: 'challenge-back-to-routine',
    name: 'Back to Routine',
    description: 'Establish your fall routine: {{target}} consecutive days',
    type: 'STREAK',
    difficulty: 'NORMAL',
    target: 14,
    timeLimit: 21 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 175,
    tags: ['fall', 'september', 'routine', 'school'],
    seasonal: true,
    seasonWindow: { startMonth: 8, endMonth: 9 },
  },
  {
    id: 'challenge-holiday-hustle',
    name: 'Holiday Hustle',
    description:
      'Stay productive during the holidays: {{target}} minutes in December',
    type: 'FOCUS_TIME',
    difficulty: 'CHALLENGING',
    target: 1000,
    timeLimit: 31 * 24 * 60 * 60 * 1000,
    rewardType: 'COINS',
    rewardAmount: 300,
    tags: ['december', 'holiday', 'end-of-year'],
    seasonal: true,
    seasonWindow: { startMonth: 11, endMonth: 11 },
  },
];
