/**
 * Volume challenge bank — focus time and session count challenges.
 */

import type { ChallengeBankTemplate } from "./challenge-bank-types";

export const VOLUME_CHALLENGES: ChallengeBankTemplate[] = [
  {
    id: "challenge-focus-30",
    name: "Half Hour Hero",
    description: "Focus for {{target}} minutes total",
    type: "FOCUS_TIME",
    difficulty: "EASY",
    target: 30,
    timeLimit: 24 * 60 * 60 * 1000,
    rewardType: "COINS",
    rewardAmount: 25,
    tags: ["volume", "quick-win"],
    seasonal: false,
  },
  {
    id: "challenge-focus-120",
    name: "Double Hour",
    description: "Focus for {{target}} minutes total today",
    type: "FOCUS_TIME",
    difficulty: "NORMAL",
    target: 120,
    timeLimit: 24 * 60 * 60 * 1000,
    rewardType: "COINS",
    rewardAmount: 75,
    tags: ["volume", "daily"],
    seasonal: false,
  },
  {
    id: "challenge-focus-240",
    name: "Four Hour Focus",
    description: "Focus for {{target}} minutes total today",
    type: "FOCUS_TIME",
    difficulty: "CHALLENGING",
    target: 240,
    timeLimit: 24 * 60 * 60 * 1000,
    rewardType: "COINS",
    rewardAmount: 150,
    tags: ["volume", "heavy", "intense"],
    seasonal: false,
  },
  {
    id: "challenge-focus-480-week",
    name: "8-Hour Week",
    description: "Focus for {{target}} minutes total this week",
    type: "FOCUS_TIME",
    difficulty: "CHALLENGING",
    target: 480,
    timeLimit: 7 * 24 * 60 * 60 * 1000,
    rewardType: "COINS",
    rewardAmount: 200,
    tags: ["volume", "weekly", "consistent"],
    seasonal: false,
  },
  {
    id: "challenge-sessions-3",
    name: "Triple Threat",
    description: "Complete {{target}} focus sessions today",
    type: "SESSION_COUNT",
    difficulty: "EASY",
    target: 3,
    timeLimit: 24 * 60 * 60 * 1000,
    rewardType: "COINS",
    rewardAmount: 40,
    tags: ["count", "daily", "quick"],
    seasonal: false,
  },
  {
    id: "challenge-sessions-5",
    name: "High Five",
    description: "Complete {{target}} focus sessions today",
    type: "SESSION_COUNT",
    difficulty: "NORMAL",
    target: 5,
    timeLimit: 24 * 60 * 60 * 1000,
    rewardType: "COINS",
    rewardAmount: 75,
    tags: ["count", "daily", "intense"],
    seasonal: false,
  },
  {
    id: "challenge-sessions-10",
    name: "Decade of Focus",
    description: "Complete {{target}} focus sessions today",
    type: "SESSION_COUNT",
    difficulty: "PUSH",
    target: 10,
    timeLimit: 24 * 60 * 60 * 1000,
    rewardType: "COINS",
    rewardAmount: 200,
    tags: ["count", "daily", "extreme"],
    seasonal: false,
  },
  {
    id: "challenge-sessions-20-week",
    name: "Session Machine",
    description: "Complete {{target}} sessions this week",
    type: "SESSION_COUNT",
    difficulty: "CHALLENGING",
    target: 20,
    timeLimit: 7 * 24 * 60 * 60 * 1000,
    rewardType: "COINS",
    rewardAmount: 175,
    tags: ["count", "weekly", "consistent"],
    seasonal: false,
  },
];
