import { z } from "zod";

export const ValidateSessionConfigSchema = z.object({
  presetId: z.string().uuid().optional(),
  customName: z.string().min(1).max(100).optional(),
  duration: z.number().min(60).max(86400),
  breakDuration: z.number().min(0).max(3600),
  longBreakDuration: z.number().min(0).max(7200),
  intervals: z.number().int().min(1).max(20),
  longBreakInterval: z.number().int().min(1).max(10),
  soundEnabled: z.boolean(),
  vibrationEnabled: z.boolean(),
  dndEnabled: z.boolean(),
  strictMode: z.boolean(),
  autoStartBreaks: z.boolean(),
  autoStartNextInterval: z.boolean(),
  category: z.string().max(50).optional(),
  tags: z.array(z.string().max(30)).max(10),
  notes: z.string().max(1000).optional(),
  goal: z.string().max(500).optional(),
  estimatedTaskCount: z.number().int().min(1).max(50).optional(),
  comebackMultiplier: z.number().min(1).max(3).optional(),
});
export const ValidateSessionStateSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().min(1),
  status: z.enum([
    "PREPARING",
    "STARTING",
    "ACTIVE",
    "PAUSED",
    "BACKGROUNDED",
    "INTERRUPTION_RISK",
    "DEGRADED",
    "COMPLETING",
    "COMPLETED",
    "PARTIAL",
    "ABANDONED",
    "FAILED",
    "RECOVERING",
    "CONFLICT",
  ]),
  phase: z.enum([
    "FOCUS",
    "SHORT_BREAK",
    "LONG_BREAK",
    "PREPARATION",
    "REVIEW",
  ]),
  config: ValidateSessionConfigSchema,
  startedAt: z.number().optional(),
  pausedAt: z.number().optional(),
  resumedAt: z.number().optional(),
  completedAt: z.number().optional(),
  abandonedAt: z.number().optional(),
  endedAt: z.number().optional(),
  totalDuration: z.number().min(0),
  elapsedTime: z.number().min(0),
  effectiveTime: z.number().min(0),
  pausedTime: z.number().min(0),
  remainingTime: z.number().min(0),
  currentInterval: z.number().int().min(1),
  totalIntervals: z.number().int().min(1),
  intervalsCompleted: z.number().int().min(0),
  interruptions: z.number().int().min(0),
  pauses: z.number().int().min(0),
  backgroundTime: z.number().min(0),
  baseScore: z.number().min(0),
  timeBonus: z.number().min(0),
  streakBonus: z.number().min(0),
  focusQuality: z.number().min(0).max(100),
  completionPercentage: z.number().min(0).max(100),
  damagePoints: z.number().min(0),
  penaltyMultiplier: z.number().min(0).max(1),
  recoveryAttempts: z.number().int().min(0),
  maxRecoveryAttempts: z.number().int().min(0).max(5),
  lastRecoveryAt: z.number().optional(),
  deviceId: z.string(),
  appVersion: z.string(),
  osVersion: z.string(),
  antiCheatStatus: z.enum(["CLEAN", "WARNING", "FLAGGED", "FAILED"]),
  antiCheatFlags: z.array(z.string()),
  createdAt: z.number(),
  updatedAt: z.number(),
  syncedAt: z.number().optional(),
  isDirty: z.boolean(),
});
export const ValidateSessionSummarySchema = z.object({
  sessionId: z.string().uuid(),
  userId: z.string(),
  status: z.enum([
    "PREPARING",
    "STARTING",
    "ACTIVE",
    "PAUSED",
    "BACKGROUNDED",
    "INTERRUPTION_RISK",
    "DEGRADED",
    "COMPLETING",
    "COMPLETED",
    "PARTIAL",
    "ABANDONED",
    "FAILED",
    "RECOVERING",
    "CONFLICT",
  ]),
  plannedDuration: z.number().min(0),
  actualDuration: z.number().min(0),
  effectiveDuration: z.number().min(0),
  pausedDuration: z.number().min(0),
  completionPercentage: z.number().min(0).max(100),
  focusQuality: z.number().min(0).max(100),
  focusPurityScore: z.number().min(0).max(100).default(100),
  interruptions: z.number().int().min(0),
  pauses: z.number().int().min(0),
  baseScore: z.number().min(0),
  timeBonus: z.number().min(0),
  streakBonus: z.number().min(0),
  finalScore: z.number().min(0),
  xpEarned: z.number().min(0),
  coinsEarned: z.number().min(0),
  gemsEarned: z.number().min(0),
  streakMaintained: z.boolean(),
  streakIncreased: z.boolean(),
  streakDays: z.number().int().min(0),
  userLevel: z.number().int().min(1).default(1),
  isPerfect: z.boolean().default(false),
  damageTaken: z.number().min(0),
  penaltiesApplied: z.array(z.string()),
  vsAverage: z.number(),
  vsBest: z.number(),
  tasksCompleted: z.number().int().min(0).optional(),
  tasksPlanned: z.number().int().min(0).optional(),
  reflection: z.string().max(2000).optional(),
  mood: z.enum(["GREAT", "GOOD", "OKAY", "STRUGGLING", "DIFFICULT"]).optional(),
  createdAt: z.number(),
});
export const ValidateSessionPresetSchema = z.object({
  id: z.string().uuid(),
  name: z.string().min(1).max(100),
  description: z.string().max(500).optional(),
  duration: z.number().min(60).max(86400),
  breakDuration: z.number().min(0).max(3600),
  longBreakDuration: z.number().min(0).max(7200),
  intervals: z.number().int().min(1).max(20),
  longBreakInterval: z.number().int().min(1).max(10),
  isDefault: z.boolean(),
  category: z.string().max(50).optional(),
  tags: z.array(z.string().max(30)).max(10),
  soundEnabled: z.boolean(),
  vibrationEnabled: z.boolean(),
  dndEnabled: z.boolean(),
  strictMode: z.boolean(),
  autoStartBreaks: z.boolean(),
  autoStartNextInterval: z.boolean(),
  createdAt: z.number(),
  updatedAt: z.number(),
  userId: z.string().optional(),
});
