-- Migration: Add provenance column to study_generations
-- Date: 2026-06-16
--
-- All study plan tasks, quizzes, and session plans are generated by an LLM.
-- Adding is_llm_generated marks every row as machine-generated so the client
-- layer can surface provenance to the user and never auto-trigger an action
-- (like scheduling a session, sending a notification, or modifying a user
-- setting) without explicit user confirmation.

ALTER TABLE public.study_generations
  ADD COLUMN IF NOT EXISTS is_llm_generated boolean NOT NULL DEFAULT true;

COMMENT ON COLUMN public.study_generations.is_llm_generated IS
  'All rows are LLM-generated. Client MUST show provenance and require user confirmation before acting on generated output.';
